- kmod/patch/kpatch-macros.h
This warning no longer applies thanks to #398.
> remove obsolete warning for KPATCH_FORCE_UNSAFE

- kmod/patch/kpatch-patch-hook.c
As mentioned on the live-patching mailing list, it is probably a good idea to restrict reading `old_addr` and `new_addr` to root only, to prevent unprivileged users from gaining information about the kernel's address space.
That being said, we could also take this time to double check current permissions in sysfs. Should `checksum` and `enabled` be readable by root only as well? Should the perms on the kpatch directory in sysfs be more stringent?
> Restrict reading old_addr and new_addr to root only

- kpatch-build/create-diff-object.c
2814237 create-diff-object: fix a potential overflow for rela type
f1683eb kpatch-build: fix ERROR: two parent matches for x.o
> fix two bugs

- kmod/patch/Makefile
- kmod/patch/livepatch-patch-hook.c
- kmod/patch/patch-hook.c
Adds a new patch module scaffold for use when building against a kernel
with CONFIG_LIVE_PATCHING=y.
Fixes issue #476
Signed-off-by: Seth Jennings <sjenning@redhat.com>
> add livepatch API support

- README.md
Change the supported Fedora version to F21 and add a new dependency.
For some reason, numactl-devel is needed by "rpmbuild -bp kernel", but
isn't detected by "yum-builddep kernel".
> readme: update dependencies for f21

- kpatch-build/kpatch-build
kpatch-build was failing on centos7 with
mv: cannot stat '/home/vagrant/rpmbuild/BUILD/kernel-*/linux-3.10.0-229.el7.x86_64': No such file or directory
in the error log. This was due to the actual directory being named
linux-3.10.0-229.el7.centos.x86_64. This patch avoids this failure by
adding a wildcard before the arch.
Signed-off-by: Louis Taylor <louis@kragniz.eu>
> Fix kpatch-build failure with srpm on centos

- examples/tcp_cubic-better-follow-cubic-curve-converted.patch
- examples/tcp_cubic-better-follow-cubic-curve-original.patch
examples/tcp_cubic-better-follow-cubic-curve-original.patch is the
original patch, combined from two mainline commits (see the description
in the patch). It cannot be used with Kpatch as it is because the
change is in the initialization of a global structure.
examples/tcp_cubic-better-follow-cubic-curve-converted.patch is a
modification of the patch that Kpatch can process. Still, this
modification has its issues, see the description there.
> examples: Added an example of a problematic patch with an explanation

- kmod/core/shadow.c
The shadow_get function does't consider the case that
'shadow is inpace', and after the shadow->data be set to the data,
it will not be the pointer. This patch fix it.
> kpatch-build: fix shadow_get function

- kpatch-build/create-diff-object.c
If a static variable is a pointer, it has rela section.
Example:
static int *p = &a;
changed to:
static int *p = &b;
so its rela section has changed.
Then this change of data should be found and report error.
But if we don't correlate its rela section, we won't
find this change.
Signed-off-by: Zhou ChengMing <zhouchengming1@outlook.com>
> bugfix: correlate the rela sections of bundled static variables

- kpatch-build/create-diff-object.c
Fix the kpatch_create_dynamic_rela_sections:
s/.rela.kpatch.patches/.rela.kpatch.funcs
> kpatch-build: fix typo s/.rela.kpatch.patches/.rela.kpatch.funcs

- kpatch-build/create-diff-object.c
kpatch_verify_patchability can detect the change of .bss or .data or
.init section, but it must be processed before verify num_changed.
Otherwise, for example, if only .init section changed, it will fail
with 'no changed functions were found', but not 'unsupported section
change(s)'.
With this patch,
for .init section: .init section will not a bundled section, so if
the section changed, not sync the function status, kpatch_verify_patchability
will give 'changed section <secname> not selected for inclusion' and
'unsupported section change(s)' error.
for .bss/.data section: kpatch_verify_patchability will ensure not
including .data or .bss section, otherwise it will give 'data section
<secname> selected for inclusion' and 'unsupported section change(s)'
error.
Signed-off-by: Li Bin …
> kpatch-build: verify bss/data/init section change properly

- kpatch-build/lookup.c
Before this patch, if changed function is weak symbol, it is not
be allowed to create live patch, and it will trigger the following
error:
/usr/local/libexec/kpatch/create-diff-object: ERROR: ***.o:
kpatch_create_patches_sections: 2294: lookup_global_symbol ***
And if the changed function reference the weak symbol, when loading
the patch module will trigger the following error:
module kpatch-***: overflow in relocation type *** val 0
insmod: can't insert 'kpatch-***.ko': invalid module format
This patch fix it and add support for patching weak function.
> kpatch-build: support patching weak function

- kmod/patch/livepatch-patch-hook.c
Fixes issue #494. A null pointer dereference can result with patch modules for multiple objects since the "vmlinux" patch object's "name" field is null. strcmp therefore crashes trying to compare object->name if the current object is vmlinux and the supplied "name" argument is not. 
Check that object->name is not null before invoking strcmp.
> livepatch-patch-hook: check for object->name before calling strcmp

- kpatch-build/kpatch-build
- kpatch-build/kpatch-gcc
Geting the changed objects from the patched dir, in order to support
adding new files in patch.
> kpatch-build: support adding new files in patch

- kpatch-build/kpatch-build
If a source RPM is used to obtain the kernel sources, kpatch-build
executes rpmdev-setuptree to prepare ~/rpmbuild directory tree, installs
the source RPM there. Then it calls 'rpmbuild -bp' to prepare the
kernel source tree.
All this, however, may clobber the existing contents of ~/rpmbuild,
which is very inconvenient if one uses rpmbuild to build other packages.
To avoid that, I could not find a better way than to specify a fake home
directory (~/.kpatch/tempsrc) for that portion of kpatch-build. It seems,
neither rpmdev-setuptree nor rpm have appropriate options for that.
I put the affected commands into a subshell so that the changes in $HOME
could not propagate to other parts of kpatch-build.
> kpatch-build: do not clobber ~/rpmbuild directory

- kpatch-build/kpatch-build
The first commit ensures kpatch-build looks for Module.symvers for the core module in the directory corresponding to the target kernel rather than for the currently running one.
The second one handles the case when Kpatch tools are distributed in a package and the core module is installed to /lib/modules/<kernel_version>/extra/kpatch/
> kpatch-build: a couple of symvers-related fixes

- kpatch-build/kpatch-build
-ffunction-sections and -fdata-sections are needed when building the
original and the patched kernels.
It is not necessary, however, to use these options when building a
patch module itself, its functions and data are OK in the sections they
are.
Let us remove these options from KCGLAGS after the kernels have been
built.
> kpatch-build: do not use -ffunction-sections for a patch module itself

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
Hard-coding the special section group sizes is unreliable.  Instead,
determine them dynamically by finding the related struct definitions in
the DWARF metadata.
Fixes #517.
Fixes #523.
> kpatch-build: detect special section group sizes

- kpatch-build/kpatch-build
It would be very useful to be able to direct build artifacts into specific directories and files. This pull request adds these features to kpatch-build.
> kpatch-build: consolidate build-artifacts and place into CACHEDIR

- kpatch-build/create-diff-object.c
> create-diff-object: Ignore unused CSWTCH static local symbols

- kpatch-build/create-diff-object.c
// Github did not allow me to reopen PR #520 after I force-pushed the changes, so I opened another pull request for these.
create-diff-object now checks if the original functions have fentry calls.
If an original function to be affected by the patch does not have the
fentry call, it cannot be patched. Error is reported in that case.
kpatch_create_mcount_sections() now also takes into account if a changed
or a new function has fentry call. If it does, mcount record is
generated for it as before. If a changed or a new function has no fentry
call, it is not an error in this case.
All this fixes the following issues.
1. If an original function has no fentry call (e.g. a "notrace" function)
but the patched function has it, the original function can not be
patched, but it would only be detected …
> kpatch-build: revisit checking for fentry calls

- kpatch-build/create-diff-object.c
This is a continuation of #535.  It also replaces the two previous attempts at dealing with unused CSWTCH symbols.  See the commit logs for more details.
> Rewrite static local variable correlation logic

- kpatch-build/kpatch-build
readelf -wi may output trailing spaces in the lines with section names ('alt_instr', etc.). 
The regexps should take this into account, otherwise kpatch-build may fail with error:
"can't find special struct size"
> kpatch-build: fix searching for the sizes of special structures

- kpatch-build/kpatch-build
Setting HOME in a subshell is too hacky.  Instead just pass the rpmbuild
directory to the rpm and rpmbuild commands.
> kpatch-build: clean up rpmbuild tmp directory handling

- kmod/core/core.c
When loading a patch module on a kernel with
!CONFIG_DEBUG_SET_MODULE_RONX, the following crash occurs:
loading core module: /root/src/kpatch/kpatch/../kmod/core/kpatch.ko
loading patch module: kpatch-meminfo-string.ko
BUG: unable to handle kernel paging request at ffffffffa0010cc0
IP: [<ffffffff8125ecb0>] do_init_module+0x84/0x1af
PGD 13d3067 PUD 13d4063 PMD 1e1ee067 PTE 1e1a0161
Oops: 0003 [#1]
Modules linked in: kpatch_meminfo_string(O+) kpatch(O)
CPU: 0 PID: 149 Comm: insmod Tainted: G           O  K 4.1.0+ #1
task: ffff88001e17b810 ti: ffff88001e1cc000 task.ti: ffff88001e1cc000
RIP: 0010:[<ffffffff8125ecb0>]  [<ffffffff8125ecb0>] do_init_module+0x84/0x1af
RSP: 0018:ffff88001e1cfda8  EFLAGS: 00010246
RAX: 0000000000000000 RBX: ffffffffa0010cc0 RCX: 0000000080a02001
RDX: …
> kmod/core: fix crash with !CONFIG_DEBUG_SET_MODULE_RONX

- README.md
- kpatch/kpatch
- man/kpatch.1
"kpatch replace" is complex, buggy, and probably unnecessary.  And
upstream livepatch has nothing like it.
Remove it from the kpatch utility, but leave the infrastructure in place
in the patch module and the core module for now.
Fixes: #456
> kpatch: deprecate the replace command

- kpatch-build/kpatch-build
Fix an issue where kpatch-build fails to clean up after hitting CTRL-C
during a remote integration test (make remote).
> kpatch-build: cleanup on SIGHUP

- kpatch-build/kpatch-build
gcc version string format may be 'gcc (xxx xxx) x.x.x [xxx]'
fix gcc_version_check to adapt to it.
> kpatch-build: fix gcc_version_check

- kpatch-build/kpatch-build
When find kobj, it should use 'cat changed_objs' to get the changed
objects, in order to process the following object format:
a/b/c/../../object.o. If using patched dir to get changed object,
the object will be a/object.o, but it is a/b/c/../../object.o in
*.cmd file.
This patch also fix the find_parent_obj that change the format
'a/b/c/../../object.o' to 'a/object.o' in deep find, otherwise
it will fail with "two parent matches for *.o".
> kpatch-build: fix find_parent_obj

- kpatch-build/kpatch-build
Before this patch, kpatch_build dependends on bash version >4.0
that support declare -A. This patch remove this dependency by
replacing dict(declare -A) with array.
> kpatch-build: reduce dependency on bash version >4.0

- kpatch-build/kpatch-build
This fix is an addition to 9fedd0d283 "kpatch-build: fix
gcc_version_check".
On some systems, the GCC version stored in vmlinux may have the
following format:
(GNU) 4.8.3 20140911 (Red Hat 4.8.3-9)
while GCC returns
(GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
As a result, binary patches cannot be built, although the compiler is
the same.
gcc_version_check() now takes this into account.
Signed-off-by: Evgenii Shatokhin <eshatokhin@odin.com>
> kpatch-build: fix gcc_version_check: both "GNU" and "GCC" are possible

- README.md
Add support for Fedora 23, `dnf` finally replaced `yum` as the default package manager.
Tested and confirmed to work on Fedora 23 x86_64 (Server Edition).
> BTW: should we remove Fedora 21 or leave it?
> readme: add support for Fedora 23

- Makefile.inc
- kmod/Makefile
- kmod/core/Makefile
- kpatch-build/Makefile
Here are a series of commits that will make packaging kpatch in distributions such as Debian and Ubuntu a bit easier.
> Changes to make packaging easier

- kmod/patch/kpatch-patch.h
- kmod/patch/livepatch-patch-hook.c
- kpatch-build/create-diff-object.c
- kpatch-build/lookup.c
- kpatch-build/lookup.h
Support for patching objects that have duplicated function names will be
introduced upstream in v4.5. This structure change needs to be handled by
the livepatch patch hook.
In addition, we need to be able to look up the symbol position in order to
populate old_sympos and sympos fields in klp_object and klp_reloc
respectively.
Fixes: #493
Signed-off-by: Chris J Arges <chris.j.arges@canonical.com>
> livepatch-patch-hook: add support for livepatch sympos structures

- kpatch-build/kpatch-build
Process the patch name correctly that only concern the fuffix with
.patch or .diff. Otherwise if the patch name is not end with .patch
or .diff but has it as substring, the fuffix will be removed
unreasonably.
> kpatch-build: process the patch name correctly

- kpatch-build/kpatch-build
kpatch-build currently requires Module.symvers for the Kpatch core
module unconditionally and fails if it is not found. This does not allow
using kpatch-build to prepare livepatch-based patches.
This patch fixes the problem.
> kpatch-build: fix building of livepatch-based patches

- contrib/kpatch.service
It may be convenient to be able to turn off the automatic loading of
the patches that kpatch.service does. This helps, for example, if a
buggy patch is installed and crashes the system at boot.
This commit allows to specify kpatch.enable=0 in the kernel command
line. In this case, the binary patches will not be loaded automatically,
and the users should be able to remove or replace the offending patches
after the system boots.
> contrib/service: allow to turn the service off at boot time

- kmod/core/core.c
Ok, technically it's not livepatch.  But it's close enough, and more
accurate than TAINT_USER.
> kmod/core: TAINT_USER -> TAINT_LIVEPATCH

- kmod/core/core.c
Fixes #584.
Since `kpatch_backtrace_address_verify` returns an int now, `args->ret` isn't used in the new version, since returning an error will prompt `print_context_stack_bp` to stop walking the stack. Tested on 4.5.0 and 4.6.0-rc5.
> kmod/core: fix stacktrace_ops 'address' function prototype for 4.6

- kpatch-build/kpatch-build
While the officially supported distributions all have CONFIG_DEBUG_KERNEL enabled, this is not true for some other distributions.  This option is necessary when kpatch-build retrieves the SPECIAL_VARS using readelf command.
Signed-off-by: Quey-Liang Kao <s101062801@m101.nthu.edu.tw>
> kpatch-build: Add "CONFIG_DEBUG_KERNEL" kernel config checking

- kmod/Makefile
When building against a different kernel from the one that is currently
running, install the kernel module to a directory based on the version
of the target kernel rather than the currently running kernel.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> kmod: Fix install path

- kpatch-build/create-diff-object.c
While looking into #580, I noticed that create-diff-object would automatically include `.altinstr_replacement` if it exists in the object it is handling, even if `.altinstructions` isn't included. It doesn't make sense to include `.altinstr_replacement` by itself, since this section only works in conjunction with `.altinstructions` and only serves to be a memory area for replacement instructions that will be copied when alternatives are applied. So, only include `.altinstr_replacement` if `.altinstructions` is included.
One very simple solution (solution 1) would be to just check if `.altinstructions` is included, and if so, simply include `.altinstr_replacement` in its entirety. One slight issue with this is that we might end up including a bunch of extraneous/unused instructions that …
> Only include .altinstr_replacement if .altinstructions is also included

- doc/patch-author-guide.md
This was discovered when trying to patch a netfilter issue and resulted in the following issue:
https://github.com/dynup/kpatch/issues/599
This patch adds some documentation in case this situation is encountered in the future.
> Add section on removing static local references.

- kpatch-build/kpatch-build
- kpatch-build/kpatch-gcc
The user's environment might have TEMPDIR exported.  If so, then kpatch-build
dies with a bogus "invalid ancestor" error. If you turn those bogus errors into
warnings, then the script goes on to incorrectly put into the generated .ko file
every single function that was compiled in the *original* kernel build, thereby
producing an immense .ko file with more than 64k sections that the linux kernel
cannot load.  This fix makes sure that TEMPDIR is unexported on the build of the
original kernel.  Actually, this fix uses a separate KPATCH_GCC_TEMPDIR variable,
so that if the kernel build is interrupted, the cleanup function in the kpatch-kbuild
script will still have TEMPDIR set correctly.
Signed-off-by: Martin Carroll <martin.carroll@alcatel-lucent.com>
> kpatch-build: do not assume that TEMPDIR is unexported on entry to script

- kmod/core/core.c
ftrace only allows a single user of this flag to register for a given
function.  This prevents kpatch conflicts with kprobes handlers which
also might want to change regs->ip for a function.
We should have done this a few years ago.  Better late than never...
> kmod/core: use FTRACE_OPS_FL_IPMODIFY flag

- kpatch-build/kpatch-build
Add a switch to kpatch-build that provides an opt-out to the cleanup
portion of the script.  This can be handy when debugging $TEMPDIR or
$RPMTOPDIR contents, as well as inspecting the patched source code
itself.
> Add kpatch-build --skip-cleanup option

- kpatch-build/kpatch-build
Source RPMs for recent Fedora kernels have a '.git' subdirectory, which
causes '+' to be appended to the module version magic, causing the
module to fail to load:
kpatch_readdir: version magic '4.8.6-201.fc24.x86_64+ SMP mod_unload ' should be '4.8.6-201.fc24.x86_64 SMP mod_unload '
> kpatch-build: remove ~/.kpatch/src/.git dir on Fedora

- kpatch-build/kpatch-build
I've been noticing that if I reuse the same $SRCDIR for consecutive kpatch-builds, I end up getting '+' appended to the version string, even if kpatch-build leaves $SRCDIR in an ostensibly clean state. It turns out if $SRCDIR is a git repository, `cleanup()` doesn't necessarily leave $SRCDIR in a completely clean state. `scripts/setlocalversion` sees the dirty index (it uses `git diff-index`) and appends the '+' and thus subsequent kpatch-builds end up with the dirty version string. 
This issue can be seen by running the following commands:
```
~/linux $ patch -p < kpatch.patch
~/linux $ git status --short
M       include/linux/module.h
~/linux $ patch -p -R < kpatch.patch
~/linux $ git diff-index --name-status HEAD
M       include/linux/module.h  # hmm...index *still* shows module.h is …
```
> kpatch-build: refresh git index during cleanup if $SRCDIR was a git repository

- kmod/core/core.c
- kmod/core/kpatch.h
- kmod/patch/kpatch-patch-hook.c
Backport the symbol lookup and checking code from upstream livepatch
code that relies on a symbol position enumeration rather than a fixed
memory address.  Kpatch only verifies symbol matches for symbols found
in vmlinux, so drop the parts that deal with module symbols.
Fixes #617.
> Add CONFIG_RANDOMIZE_BASE KASLR support

- kpatch-build/kpatch-build
On RHEL 7 based kernels, copy_user_64.o misuses the .fixup section by
placing a normal function in it.  That confuses create-diff-object.
Work around it by just skipping the file altogether, which is fine to do
because it's an assembly file which should never change anyway.
Fixes #625.
> kpatch-build: fix tree-wide rebuild on RHEL 7

- kpatch-build/kpatch-build
For newer kernels, some new objects have been added to the 'head-y'
build target.  These objects aren't directly traceable to vmlinux so
they have to be added manually.
Fixes #626.
> kpatch-build: fix tree-wide rebuild

- kpatch-build/kpatch-build
- kpatch-build/kpatch-gcc
When building the patched version of the kernel, vmlinux has to be
linked with the '--warn-unresolved-symbols' linker flag.  Otherwise the
link will fail if the patch uses kpatch-specific symbols like
kpatch_shadow_alloc() and friends.
As of upstream Linux commit b36fad65d61f ("kbuild: Initialize exported
variables"), LDFLAGS_vmlinux= no longer works from the command line,
resulting in '--warn-unresolved-symbols' no longer getting set.
Instead we can use kpatch-gcc to pass the flag to the linker.
Fixes #627.
> kpatch-build: fix 'undefined reference to kpatch_shadow_*' errors

- kpatch-build/create-diff-object.c
- kpatch-build/lookup.c
Give a slightly better error message for the dup file+symbol issue.
It's still cryptic but it's good enough to at least give us kpatch
developers a better idea about what went wrong.  This would have helped
diagnose issue #633 much more quickly.
> create-diff-object: better error message for dup file+symbol

- kmod/core/core.c
- kmod/patch/livepatch-patch-hook.c
- kpatch-build/kpatch-build
These patches address Ubuntu specific patches that change livepatch structures in a way that breaks checking for kernel versions strictly on 4.X
FIxes #636
> kpatch and patch module builds fail on Ubuntu 16.04 #636

- kpatch/kpatch
If a kpatch load fails, try again, up to 5 times.
It will usually only fail if the activeness safety check failed, in
which case trying again might work.  Unfortunately, insmod doesn't
return the error reported by the module, so we can't distinguish
activeness safety errors from other types of errors.
> kpatch: retry kpatch load on failure

- kpatch-build/create-diff-object.c
GCC with KASAN instrumentation creates section ".rodata" with some static strings (i.e. some of them go to ".rodata.str1.1" for release build).
This change makes possible to build patch and check if it fixes issue found with KASAN, such as CVE-2016-9555.
> kpatch-build: make patches for debug kernels too

- kpatch-build/create-diff-object.c
With older versions of gcc, string tables were stored in a few
.rodata.str1.* sections:
[ 6] .rodata.str1.1       PROGBITS     0000000000000000 0000005c 00000008  1 AMS    0   0  1
[11] .rodata.str1.8       PROGBITS     0000000000000000 000000a0 00000364  1 AMS    0   0  8
[16] .rodata.meminfo_proc_fops PROGBITS     0000000000000000 000009c0 000000d8  0 A      0   0 32
[17] .rela.rodata.meminfo_proc_fops RELA         0000000000000000 00017a58 00000060 24 I     35  16  8
With gcc 6, there can now be per-function string tables:
[10] .rodata.trace_raw_output_task_newtask.str1.8 PROGBITS     0000000000000000 00000208 00000032  1 AMS    0   0  8
[13] .rodata.trace_raw_output_task_rename.str1.8 PROGBITS     0000000000000000 000002b0 00000030  1 AMS    0   0  8
[24] .rodata.mm_init.str1.1 …
> create-diff-object: support gcc 6 per-function string tables

- kpatch-build/kpatch-build
When passing '-d' to kpatch-build, it prints out some useful information
and keeps the related files around in ~/.kpatch/tmp.  However, it also
passes '-d' to create-diff-object, which spits out way too much
information, drowning out all the other useful messages printed by
kpatch-build.
In my experience, the create-diff-object debug info is overkill for
debugging most issues, so disable it.  The flag can still be used when
running create-diff-object manually.
> kpatch-build: reduce the debug firehose

- kpatch-build/create-diff-object.c
Related to issue #629, print a useful error message at the time of the
original error condition instead of seg faulting later.
> create-diff-object: print error message instead of seg faulting

- kpatch/kpatch
Livepatch modules can be supported with minimal changes to the kpatch
script.  Adjust for appropriate sysfs paths, core-patching code (in
kernel for livepatch, kpatch.ko for kpatch), and checksum verification
(only verify the checksum if it exists).
Fixes #479.
> kpatch: better support for livepatch modules

- kmod/core/core.c
- kmod/patch/kpatch-patch-hook.c
- kmod/patch/livepatch-patch-hook.c
Upstream commit [2992ef29ae01](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=2992ef29ae01) ("livepatch/module: make TAINT_LIVEPATCH module-specific") v4.9+ modified the kernel to add the TAINT_LIVEPATCH flag on module load.  To support this feature, add the "livepatch" module info in the {k,live}patch modules and drop the add_taint() in the core module.
Testing: ran on a RHEL7 kernel with and without a [2992ef29ae01](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=2992ef29ae01) backport and observed the expected results with the backport: ```cat /sys/module/<kpatch_module>/taint``` = ```OEK```.
I did not see this kernel feature backported yet to Ubuntu 16 LTS or Fedora 24, so no kernel version checks are needed for them.
> kmod: let kernel apply TAINT_LIVEPATCH

- kpatch-build/create-diff-object.c
I let the smatch and sparse static code analysers loose on the entire product tree and sparse came up with two new complaints.  These are pretty trivial, so my heart won't be broken if we drop these over the code churn.  After these two changes, the output is relatively* clean as far as I can tell.
\* With a few caveats:
1 - sparse gets confused about ```insn/asm/insn.h :: struct insn :: unsigned char x86_64``` ... if I rename all references to the ```x86_64``` member to ```foo_x86_64```, it's happy.  So it must think that "x86_64" is defined as something else?  This is more than false-negative chatter as the parser gives up on .c files which include insn.h as it counts too many errors.
2 - I had to add ```error``` to smatch's ```no_return_funcs``` file, else it would complain about …
> Sparse smatch round 2

- kpatch-build/kpatch-build
commit eb55adc52d0c ("use livepatch 4.5 features in
Ubuntu Xenial kernel") will trigger following build
failure, while building stock kernel on Ubuntu:
make[2]: Entering directory '/root/.kpatch/obj'
CC [M]  /root/.kpatch/tmp/patch/patch-hook.o
In file included from /root/.kpatch/tmp/patch/livepatch-patch-hook.c:28:0,
from /root/.kpatch/tmp/patch/patch-hook.c:21:
/root/.kpatch/tmp/patch/livepatch-patch-hook.c: In functionpatch_ini:
/root/linux-4.8.15/include/generated/utsrelease.h:2:32: error: too many decimal points in number
#define UTS_UBUNTU_RELEASE_ABI 4.8.15
^
/root/.kpatch/tmp/patch/livepatch-patch-hook.c:252:7: note: in expansion of macro UTS_UBUNTU_RELEASE_ABI
UTS_UBUNTU_RELEASE_ABI >= 7 ) \
^
Stock kernel version string might differ from the ubuntu
kernel versioning format. This …
> kpatch-build: Add UTS_UBUNTU_RELEASE_ABI tag for non-stock kernel

- test/integration/kpatch-test
This is a set of really small fixes for kpatch-test:
* **testing: handle empty glob cases** - found when running ```kpatch-test``` against an empty patch directory.  I could have modified the globbing behavior via ```shopt -s failglob```, but I thought that was a more esoteric fix (and changes default behavior for the rest of the script).
* **testing: skip gcc check** - installed gcc vs kernel build gcc can drift on Vagrant VM boxes.  We could alternatively add a command line switch to ```kpatch-test``` to optionally pass this option along.
* **testing: skip combined test for a single patch** - this cleans up the test output a bit.
* **testing: add full path for /sbin executables** - as seen on a Fedora Vagrant VM box when running a command via ```ssh ... <command>```.  I verified the …
> Small kpatch-test fixups

- kpatch-build/create-diff-object.c
- test/integration/fedora-25/convert-global-local.patch
As reported in PR #658, when patching an exported function which is used
by the patch module init code, the init code will incorrectly link to
the patched version of the function and will call the patched function
before its relocations have been applied.
For example, when patching __kmalloc(), I see:
kpatch_kmalloc: module is marked as livepatch module, but livepatch support is disabled
kernel tried to execute NX-protected page - exploit attempt? (uid: 0)
BUG: unable to handle kernel paging request at ffffc90001d03c58
IP: 0xffffc90001d03c58
PGD 7c8b4067
PUD 7c8b5067
PMD 755f7067
PTE 800000007ad03163
Oops: 0011 [#1] PREEMPT SMP
Modules linked in: kpatch_kmalloc(OE+) kpatch(OE) ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 xt_conntrack cfg80211 rfkill ebtable_nat ebtable_broute bridge stp llc …
> create-diff-object: convert global symbols to local

- .gitignore
- kmod/patch/Makefile
- kmod/patch/kpatch.lds.S
- kmod/patch/livepatch-patch-hook.c
- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
- kpatch-build/create-kpatch-module.c
- kpatch-build/kpatch-build
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
- kpatch-build/kpatch-intermediate.h
- kpatch-build/log.h
- kpatch-build/lookup.c
- kpatch-build/lookup.h
This pull request attempts to bridge the two ways we have of building "dynamic relocations" i.e. dynrelas and klp relas.
I had to scrap the first implementation I had which tried to have create-diff-object create intermediary, implementation-neutral `.kpatch.symbols` and `.kpatch.relocations` sections, which we agreed seemed like the most "correct" way to go about it. But unfortunately I later bumped into a unresolvable limitation: After the final object.o is linked, there was no deterministic way to figure out which entry belonged to which target section just from looking at each entry in `.kpatch.relocations`. The target section is needed to fill in the sh_info field for klp rela sections. Storing the section name in `.kpatch.relocations` wouldn't work since names aren't required to be …
> 4.7 changes (WIP)

- kpatch-build/lookup.c
Use the log.h version of the ERROR macro so the childobj gets printed.
> lookup: use log.h version of ERROR macro

- kmod/core/core.c
- kmod/patch/kpatch-patch-hook.c
Previous commit "kmod: let kernel apply TAINT_LIVEPATCH" modified the
kpatch patch module to set the "livepatch" module info.  This breaks
module loading for kernel config CONFIG_LIVEPATCH=n
kpatch_kmalloc: module is marked as livepatch module, but livepatch support is disabled
kpatch modules can still use TAINT_LIVEPATCH as a per-module taint flag,
but only if it is set after the module loads.
Fixes: 660.
> kmod: fix kpatch patch module load if CONFIG_LIVEPATCH=n

- test/integration/kpatch-test
> testing: remove extra '}' from run_custom_test's prefix variable

- kmod/core/core.c
- kpatch-build/kpatch-build
This is based on @flaming-toast 's [4.7-changes](https://github.com/flaming-toast/kpatch/tree/4.7-changes) branch, so I don't know how well the github review interface will work, but here goes.
* patch 1 - I don't know if this is a kernel config or v4.9 thing, but kpatch-build was complaining about ```initramfs_data.o``` so just skipped the file so I could continue on.
* patch 2 -  adds in v4.9+ support for the shiny new ```unwind_{start,done,next_frame}``` interface.  Much simpler than the deprecated ```dump_trace``` and callback mechanism!  (Good work, @jpoimboe )  My modifications are pretty straightforward, I tested with a patch that changed ```n_tty_read```, which an agetty process will always be sitting on... and verified the safety check detected and returned ```-EBUSY```.
Hope …
> RFC - 4.9 unwinder

- kmod/core/core.c
Upstream 2992ef29ae01 "livepatch/module: make TAINT_LIVEPATCH module-specific"
added a TAINT_LIVEPATCH flag to the module-specific taint flags.  This
commit is v4.9+ and the modules taint field is an unsigned int.
Upstream 7fd8329ba502 "taint/module: Clean up global and module taint
flags handling" modified the modules taint field to be an unsigned long.
This commit is v4.10+.
Adjust the module tainting code in kpatch_register() to consider v4.9
kernels as well as v4.10 (and any distro-specific behavior).
Fixes: #666.
> kmod/core: fix module taint for 4.9 kernel

- kpatch-build/create-diff-object.c
- kpatch-build/lookup.c
- kpatch-build/lookup.h
This patch needs some explanation. When we want to resolve a dup
file+symbol symbol, we first find out our base object in lookup table,
then we can use this information to resolve ambiguous local symbols.
We use resolve_dup_file_symbol to find out the correct base object in
lookup table. If all local symbols of a file can be found in the
kelf_base, we think it's a matched file.
Fixes #604.
Signed-off-by: Zhou Chengming <zhouchengming1@huawei.com>
> support dup file+symbol

- kpatch-build/kpatch-build
This patchset addresses a few issues with ```kpatch-build``` and various kernel config settings:
1. Some versions of gawk do not support the whitespace ```'\s'``` operator.  Drop back to using the ```[[:space:]]``` expression as it's supported in older verisons, too.
2. @marcin-github reported issues building on Gentoo when the kernel was configured with ```CONFIG_DEBUG_INFO_REDUCED```.  This reorders ```readelf -wi``` output a bit, and requires a smarter awk script to parse special structure sizings.
3. @marcin-github also reported problems when ```CONFIG_DEBUG_INFO_SPLIT``` was set.  This configuration stores debuginfo in separate ```.dwo``` files.  Since no major distribution is doing this (yet), just detect and note that this isn't supported.
4. @marcin-github also reported problems …
> kpatch-build fixups for various kernel configs

- kmod/core/core.c
- kmod/core/kpatch.h
- kmod/patch/kpatch-patch-hook.c
- kpatch/kpatch
- test/testmod/doit-client.sh
Restructure kpatch's sysfs interface and mirror the sysfs tree after
livepatch's sysfs layout. With the current sysfs layout, we cannot
distinguish which object a function belongs to, and we cannot tell which
modules/objects are patched. Therefore, restructure the kpatch sysfs tree
such that module/object information is available. With the new layout, each
patched object has its own directory, with each function being a
subdirectory of its object.
Implement this by embedding a kobject struct within the kpatch_module,
kpatch_func, and kpatch_object structs and supplying their ktypes and
kobject release methods.
Before:
```
/sys/kernel/kpatch
└── patches
└── <patch_module>
├── checksum
├── enabled
└── functions
├── <function>    # from <object1>
│    ├── new_addr
│    └── old_addr
├── …
```
> kmod: restructure kpatch sysfs tree

- kmod/core/core.c
When the core module loops through an object's list of dynrelas, it determines whether or not the target location of the dynrela is in a read-only region of the patch module. If it is, the readonly flag is set to 1 and it calls set_memory_{rw,ro} before and after the probe_kernel_write() operation. This flag gets set once, and never gets reset for subsequent iterations. Therefore, if a target happens to be in a RW section of the
patch module, and readonly = 1 had been set before, we may unintentionally set a normally RW page to RO. Fix this by setting the readonly flag with each iteration of the loop.
> kmod/core: ensure the readonly flag is reset correctly

- kpatch-build/lookup.c
A few symbols are discarded in the kernel linking phase, which means
they won't be in the lookup table.  Skip their comparison.
This fixes a bunch of warnings seen when building a patch which triggers
a tree-wide rebuild:
create-diff-object: ERROR: aes_glue.o: find_local_syms: 112: find_local_syms for aes_glue.c: found_none
create-diff-object: ERROR: aesni-intel_glue.o: find_local_syms: 112: find_local_syms for aesni-intel_glue.c: found_none
create-diff-object: ERROR: init.o: find_local_syms: 112: find_local_syms for init.c: found_none
create-diff-object: ERROR: iosf_mbi.o: find_local_syms: 112: find_local_syms for iosf_mbi.c: found_none
create-diff-object: ERROR: setup.o: find_local_syms: 112: find_local_syms for setup.c: found_none
...
After this patch, there's still one warning …
> lookup: skip discarded symbols in local symbol comparison

- kpatch-build/kpatch-build
Once upon a time, kpatch-build did the kernel build in three passes.
The extra pass was done without '-ffunction-sections -fdata-sections',
so it could produce the original vmlinux file.
At that time, there was no ~/.kpatch/obj directory.  The kernel was
built directly in ~/.kpatch/src.  Because the same directory was used
for both the original kernel build and the '-ffunction-sections
-fdata-sections' build, the entire tree had to be rebuilt twice for
every kpatch-build incantation, making it very slow.
That situation was improved with the following commit:
5352d8b01aa1 ("build objects in separate directory to fix caching")
That built the regular and special binaries in ~/.kpatch/obj and
~/.kpatch/obj2, respectively.
Since then we've simplified things so that it only does two build …
> kpatch-build: build the kernel in ~/.kpatch/src again

- kpatch-build/create-diff-object.c
Strip kpatch_ignore_func_* symbols to prevent the inclusion of
.kpatch.ignore.functions.  If this section is included, it creates a
dynrela to the ignored function.  When loaded, the kpatch core module
may change the page protection of this section to read only. This could
cause the patch module's data structures to become read only.
Fixes #681.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> create-diff-object: Strip kpatch_ignore_func_* symbols

- kpatch-build/kpatch-gcc
Upstream kernel commit 7f2084fa55e6 ("[kbuild] handle exports in lib-y
objects reliably") (v4.9+) added temporary dummy .lib_exports.o objects
to the kernel build.  As these ephemeral files don't contain any code,
update the kpatch-gcc glob pattern to ignore them.
(glob pattern suggested by flaming-toast)
Fixes #686.
> kpatch-gcc: update ignorelist to avoid foo/.lib_exports.o files

- contrib/kpatch.spec
- kpatch/kpatch
This release has many fixes and improvements since 0.3.4.  The '0.3' was
bumped to '0.4' because of commit 0bb5c106ef18 ("kmod: restructure
kpatch sysfs tree"), which broke the ABI between the kpatch core module
and the kpatch script, as it changed the sysfs layout.
Other notable changes since 0.3.4:
- The tools underlying kpatch-build have been made more modular, in
preparation for making create-diff-object more generally useful to
other use cases (kernel livepatch, Xen live patching, user space
patching).
- Support for all new upstream kernels up to 4.10.
- KASLR support.
- Many other bug fixes and improvements.
> bump version to 0.4.0

- kpatch-build/kpatch-build
Found a small typo, paravirt_patch_site should be exception_table_entry
> kpatch-build: fix small typo

- doc/patch-author-guide.md
Two small tweaks for the patch author guide.  The first clarifies the context for load hooks (stop_machine and module notifier).  The second adds a shadow variable - data semantic example.
I left the locking example todo in place -- @jpoimboe -- would `0010-CVE-2014-2706-2.patch` that you mailed me last week work here?  If so I can include that as well.
> Author guide fixups

- kpatch-build/kpatch-elf.c
SUSE-based kernels have a DWARF unwinder, so they build with the gcc
'-fasynchronous-unwind-tables' flag, which adds .eh_frame and
.eh_frame_hdr sections.  Treat those sections like the other debug
sections.
Fixes: #703
> elf: add .eh_frame* sections to debug section list

- kpatch-build/lookup.c
On Debian/Ubuntu, the `vmlinux` from `-dbg` package has a version number
appended to it. For example:
`/usr/lib/debug/boot/vmlinux-3.13.0-117-generic`. Make it work
nonetheless.
> create-diff-object: only check if kernel object starts with "vmlinux"

- README.md
- kpatch-build/kpatch-build
On Ubuntu Trusty, HWE kernels don't come with a linux-source
package. Use dget to retrieve the source package instead. This is not
the case anymore with Xenial as the linux-source package is also
provided for the HWE kernels. For Debian, backports always come with the
linux-source package.
> kpatch-build: retrieve source package instead of linux-source

- kpatch-build/lookup.c
With #650, we found that using -ffunction-sections and -fdata-sections
sometimes causes GCC to output the local symbols in a different order in
the symbol table.  So don't assume they're in the same order, and
instead search all the locals.
This requires two passes: once going through the lookup table symbols
and once going through the .o symbols.  This is needed to make sure
there aren't any extra symbols in one of the files.
I also reorganized the code a bit to simplify it.
/cc @kamalesh-babulal
> lookup: allow local symbols to be in any order

- kpatch-build/kpatch-build
useful if you need a dynamic output folder instead of the static $PWD folder
> added output argument for choose where to save the livepatch file

- kmod/core/core.c
Starting with kernel 4.11, CONFIG_DEBUG_SET_MODULE_RONX has been
replaced with CONFIG_ARCH_HAS_SET_MEMORY.  This fixes the following
error:
kpatch: write to 0xffffffffc0d7650e failed for symbol copy_mnt_ns
Fixes #721.
> kmod/core: fix dynrela writes for kernel 4.11+

- kpatch-build/kpatch-build
If you give kpatch-build a bad argument for the '-s' option, it shows
the following error:
$ kpatch-build/kpatch-build -s foo
ERROR: source dir  not found.
The supplied 'foo' argument isn't printed as intended.
Also fix some other options which have a similar issue.
> kpatch-build: fix errors messages for missing files/dirs

- kpatch-build/kpatch-build
Without this option kpatch-build dies with "ERROR: can't find special
struct alt_instr size.".
I just noticed this when trying to build a patch for a custom kernel which didn't have this option enabled. This error message would've helped.
> kpatch-build: check if DEBUG_INFO is enabled

- Makefile.inc
- kmod/patch/Makefile
uname -p returns "unknown" on many systems effectively breaking the
build. Replace it with uname -m which yields the correct architecture.
I didn't touch kmod/patch/Makefile because I don't know what values uname -m will return on non-x86 architectures.
> Makefile.inc: replace uname -p with uname -m

- kpatch-build/Makefile
Helps applying compiler flags from distributions, e.g. Debian.
> kpatch-build: respect CPPFLAGS

- kpatch-build/create-diff-object.c
When building the patch from PR #727, kpatch-build thought a .LC0 string
symbol moved to a different section.  In fact, its section got renamed
due to the GCC IPA SRA optimization.
Original object:
```
[12] .rodata.__ip_append_data.isra.46.str1.1 PROGBITS     0000000000000000 000002e7 0000002e  1 AMS    0   0  1
[13] .rodata.__ip_append_data.isra.46.str1.8 PROGBITS     0000000000000000 00000318 0000002a  1 AMS    0   0  8
[14] .text.__ip_append_data.isra.46 PROGBITS     0000000000000000 00000350 00000a6d  0 AX     0   0 16
[15] .rela.text.__ip_append_data.isra.46 RELA         0000000000000000 00053598 000001b0 24 I     110  14  8
```
Patched object:
```
[12] .rodata.__ip_append_data.isra.47.str1.1 PROGBITS     0000000000000000 000002e7 0000002e  1 AMS    0   0  1
[13] …
```
> create-diff-object: rename mangled string sections

- kpatch-build/kpatch-build
Instead of always using the maximum number of CPUs available, allow
user to tune the number of make jobs using the environment variable
CPUS.
> kpatch-build: allow the number of make jobs to be specified using CPUS

- kpatch-build/create-diff-object.c
Normally, kpatch doesn't complain if you remove or rename a function.
This is a feature, because sometimes you have to rename a function in
order to patch it, if for example it doesn't have an fentry call.  In
the object code, it's treated as a new function.  You could get the same
result by copying/pasting the original function and giving the copy a
new name.  But renaming it makes it much easier to review the patch.
In RHEL 7.4, I tried to rename l2cap_config_rsp() to
l2cap_config_rsp_kpatch(), but it failed with:
ERROR: l2cap_core.o: reference to static local variable CSWTCH.347 in l2cap_config_rsp was removed
This particular error is an easy fix, because the CSWTCH.* symbols are
read-only and are created by GCC.  So they shouldn't be correlated
anyway.
In the future, we will need a …
> create-diff-object: treat "CSWTCH.*" as a special static local

- kpatch-build/kpatch-gcc
When there is a ".." in the source object path, kpatch-gcc can't handle
it correctly.  kpatch-gcc is called for objects which were recompiled
and writes the changed objects to "changed_objs". But if the path of the
input obj is something like:
arch/x86/kvm/../../../virt/kvm/.tmp_kvm_main.o
then it will fall into the "*.*.o" branch of the kpatch-gcc case
statement and kpatch-build will report "ERROR: no changed objects
found."
Use Joe's suggestion to revert d526805619de ("kpatch-gcc: update
ignorelist to avoid foo/.lib_exports.o files") and instead add a
"*/.lib_exports.o" pattern.
Fixes #735.
[ cleaned up changelog - jpoimboe@redhat.com ]
Cc: Joe Lawrence <joe.lawrence@redhat.com>
Signed-off-by: chen xiaoguang <xiaoggchen@tencent.com>
> kpatch: fix kpatch-build matching changed object bug

- kmod/patch/Makefile
- kpatch-build/kpatch-build
This a lightly tested, RFC for teaching kpatch-build to operate on multiple input patches.
The main motivation behind this is to avoid using tools like combinediff to aggregate a bunch of patch files into a single input file for kpatch-build.  I have seen combinediff create some odd output, especially when multiple patches modify the same file/functions.
This implementation applies each patch in order to the kernel tree.  I ditched the early patch test (I don't know how to --dry-run multiple patches), but I kept the APPLIEDPATCH logic (the program seems to want to restore the SRCDIR to an unpatched state).
Maybe it would be cleaner to move this functionality out to a helper utility?  Basically copy combinediff, but have it work against a real tree that it can apply against, gaining full …
> kpatch-build: support multiple .patch files

- kpatch-build/kpatch-elf.c
Valgrind complains about uninitialized bytes passed to pwrite64(buf)
from kpatch_write_output_elf()'s call to elf_update():
==32378== Syscall param pwrite64(buf) points to uninitialised byte(s)
==32378==    at 0x5141A03: __pwrite_nocancel (in /usr/lib64/libc-2.23.so)
==32378==    by 0x4E46846: ??? (in /usr/lib64/libelf-0.168.so)
==32378==    by 0x4E42B88: elf_update (in /usr/lib64/libelf-0.168.so)
==32378==    by 0x40C57A: kpatch_write_output_elf (kpatch-elf.c:895)
==32378==    by 0x40926F: main (create-diff-object.c:2851)
==32378==  Address 0x28d52300 is 0 bytes inside a block of size 56 alloc'd
==32378==    at 0x4C2BBAD: malloc (vg_replace_malloc.c:299)
==32378==    by 0x40B86A: create_section_pair (kpatch-elf.c:707)
==32378==    by 0x406CAE: kpatch_create_patches_sections …
> kpatch-build: clear Elf_Data d_buf buffer on allocation

- kpatch-build/create-klp-module.c
Valgrind complains about an uninitialized variable in
create-klp-module.c:
==4412== Conditional jump or move depends on uninitialised value(s)
==4412==    at 0x402846: main (create-klp-module.c:497)
This warning refers to main()'s struct arguments stack variable,
precisely its .no_klp_arch member.  Initialize it to zero to avoid the
complaint.
> kpatch-build: create-klp-module: set default arguments.no_klp_arch

- kpatch/kpatch
When running a kernel for a long period of time without rebooting, it's
possible that newer versions of the kpatch script may get installed.  So
new versions of the kpatch script need to support old versions of
kpatch.ko.
> kpatch: add ABI backwards compatibility

- Makefile
- kpatch-build/kpatch-build
- kpatch-build/kpatch-gcc
- kpatch/kpatch
Hi,
I tried to load a kpatch from a path containing spaces (it contained the output of `uname -v` to match only  a specific kernel) and it failed due to invalid quoting.
The first patch should correct this issue by quoting all necessary variables. The second is additional cleanup found be shellcheck. I'm not sure about the last one, as I don't know if the macro is a string (in that case I don't know how this could ever work) or if it's a number (then the quotes could be removed instead).
I didn't try every possible invocation of kpatch so I've might have missed some issues with this patch (shell quoting is quite delicate), please review carefully.
Regards
Simon
> Shell quoting improvements and additional cleanup

- kpatch-build/Makefile
Might result in build failures or unexpected behaviour otherwise.
> kpatch-build: Fix clean rule (remove insn/*.o)

- kpatch-build/kpatch-build
- kpatch-build/kpatch-gcc
Added --archversion commandline option conflict detection.
> kpatch-build cleanups

- .gitignore
- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
- kpatch-build/gcc-plugins/gcc-common.h
- kpatch-build/gcc-plugins/gcc-generate-rtl-pass.h
- kpatch-build/gcc-plugins/ppc64le-plugin.c
- kpatch-build/kpatch-build
- kpatch-build/kpatch-intermediate.h
This is a followup to #754.  This gets rid of the ppc64le-specific changes in create-klp-module, and fixes a regression which was introduced in #737.
This still needs a lot of testing on both x86 and ppc64le.  I recommend meminfo-string.patch, as well as a trivial patch to `load_elf_binary()` in fs/binfmt_elf.c, so that #700 gets tested properly.  It also needs integration testing on x86.
> Some ppc64le cleanups and fixes

- kpatch/kpatch
The first of the changes is to makes sure we get "Device or resource busy" message in English when it is output by insmod. kpatch does not expect it in any other language, so let us force "C" locale here.
The other change is rather small too, it just makes it easier to adjust the number of attempts to load the patches, as well as the interval between retries by putting them into easy to find variables. This is especially helpful for the "old-style" (not livepatch-based) patches when doing stress testing, etc. In such conditions, I often had to increase both the number of attempts and the interval.
> kpatch: a couple small enhancements in retry logic

- kpatch/kpatch
- man/kpatch.1
Kpatch no longer uses initrd to make sure the patch modules are loaded
at boot. The users could either install the provided systemd service
for that or come up with some other solution.
The messages mentioning initrd could confuse the users.
> Do not mention initrd in the help messages and in the man page

- kmod/core/Makefile
A cosmetic fix.
If KPATCH_BUILD ending with 'build/' is passed to 'make', KERNELRELEASE
will become 'build' and the error message will look like:
"<...> doesn't exist. Try installing the kernel-devel-build RPM or
linux-headers-build DEB."
Let us fix that.
> kmod/core: fix definition of KERNELRELEASE

- kpatch-build/create-diff-object.c
Found in the scope of https://github.com/dynup/kpatch/pull/755 but not
related to the main problem discussed there.
kpatch_create_patches_sections() and kpatch_create_intermediate_sections()
used 'hint' in error messages.
However, the string 'hint' refers to is owned by 'kelf_base' and is
freed before kpatch_create_*_sections() are called. As a result, if
these functions try to output errors and print 'hint',
create-diff-object will crash.
As suggested in the mentioned PR, 'hint' is actually no longer needed at
that stage, so I have removed it from kpatch_create_*_sections().
> kpatch-build: 'hint' is not needed in kpatch_create_*_sections()

- kpatch/kpatch
This is similar to how loading of the patches works now. Needed mostly
for the "old" kpatch, i.e. for the kernels that do not support livepatch.
If the patched functions are currently used, loading of the patch fails
with "Device or resource busy" error. kpatch script then retries the
operation several times.
In some cases, it could be convenient to do the same thing when
unloading or simply disabling the patches. One of the use cases is when
it is needed to replace a loaded cumulative patch with its previous
version, esp. if the patches have patch/unpatch hooks. It is often more
reliable to disable the loaded patches first and then load the new
patch. Disable operation may fail due to activeness safety check - so
let us retry it a few times.
> If kpatch fails to disable a patch, retry a few times

- kpatch-build/kpatch-build
Sometimes git doesn't see that the patches have been reverted, if that
happens during ./scripts/setlocalversion call the resulting patch module
is built with a wrong vermagic because the tree is still considered
dirty.
Fix by moving git update-index call into remove_patches function so that
it is called every time the patches are reverted, not only on cleanup.
> Fix resulting module vermagic when source dir is a git tree

- kpatch-build/create-diff-object.c
GCC 7.2.1 complains about the usage of the PPC64_LOCAL_ENTRY_OFFSET
macro:
create-diff-object.c: In function ‘is_gcc6_localentry_bundled_sym’:
create-diff-object.c:119:83: error: ‘<<’ in boolean context, did you mean ‘<’ ? [-Werror=int-in-bool-context]
(((1 << (((other) & STO_PPC64_LOCAL_MASK) >> STO_PPC64_LOCAL_BIT)) >> 2) << 2)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
create-diff-object.c:140:10: note: in expansion of macro ‘PPC64_LOCAL_ENTRY_OFFSET’
return (PPC64_LOCAL_ENTRY_OFFSET(sym->sym.st_other) &&
^~~~~~~~~~~~~~~~~~~~~~~~
Fix it by explicitly treating the macro as an integer instead of a bool.
/cc @kamalesh-babulal
> create-diff-object: Fix PPC64_LOCAL_ENTRY_OFFSET usage

- kpatch-build/create-diff-object.c
Commit f0518ef58afc ("create-diff-object: fix ppc64le kpatch_replace_sections_syms() bundling assumption"), subtractes sym.st_value for all bundled symbols on ppc64le and GCC6+ irrespective
of function or switch label.
As a side effect, the addend for switch labels were incorrect and call to local function executed TOC setup code. Fallback to the original behavior of subtracting sym.st_value only for the dynrela.
```
Example of wrong switch label:
------------------------------
0000000000000008 <register_netdevice>:
...
31c:   05 00 85 2b     cmplwi  cr7,r5,5
320:   7c 02 9d 41     bgt     cr7,59c <register_netdevice+0x594>
324:   00 00 e2 3c     addis   r7,r2,0
324: R_PPC64_TOC16_HA   .toc+0x580
328:   64 17 a5 78     rldicr  r5,r5,2,61
32c:   00 00 47 e9     ld      r10,0(r7)
32c: …
```
> ppc64le - Fix wrong addend value for switch labels

- kmod/patch/livepatch-patch-hook.c
- kpatch-build/create-diff-object.c
This patchset fixes couple of corner cases seen on POWER and one architecture independent fix for `.data.once` section, which gets created with recent upstream kernel changes. This patchset applies on top of #757.
> More ppc64le fixes

- kpatch-build/kpatch-build
- kpatch-build/kpatch-gcc
- test/difftree.sh
for-next branch of kbuild repo contains a "kbuild: rename built-in.o to
built-in.a" which renames all built-in.o instances. Filter on both .o
and .a in kpatch-gcc/kpatch-build to be prepared for this change.
Fixes #800.
> Prepare for built-in.o -> built-in.a rename

- README.md
- kpatch-build/kpatch-build
- test/integration/centos-7/remote-setup
- test/integration/fedora-25/remote-setup
It appears that since 0dec5136eef945aa086a0290b3a8de65393fdf5f nothing
has been used from the rpmdevtools package by kpatch-build.
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>
> drop unused rpmdevtools dependency

- .gitignore
> gitignore: ignore cache.mk from newer kernel builds

- kpatch-build/kpatch-build
Don't die outright when encountering an 'undefined reference' error,
instead write those down and check if needed symbols are provided by the
resulting module or core kpatch module.
Fixes #783.
> Undefined reference failure logic rework

- kpatch-build/gcc-plugins/ppc64le-plugin.c
On ppc64le, building drivers/media/i2c/cx25840/cx25840.ko with GCC 4.85,
the plugin triggers the following errors:
{standard input}: Assembler messages:
{standard input}:1078: Error: operand out of range (0x0000000000008fd4 is not between 0xffffffffffff8000 and 0x0000000000007ffc)
{standard input}:1288: Error: operand out of range (0x000000000000874c is not between 0xffffffffffff8000 and 0x0000000000007ffc)
{standard input}:3844: Error: operand out of range (0x00000000000080e8 is not between 0xffffffffffff8000 and 0x0000000000007ffc)
{standard input}:4028: Error: operand out of range (0x00000000000082b4 is not between 0xffffffffffff8000 and 0x0000000000007ffc)
{standard input}:4031: Error: operand out of range (0x00000000000080b4 is not between 0xffffffffffff8000 and 0x0000000000007ffc) …
> gcc-plugin: run the plugin at an earlier pass

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.h
It was observed by Evgenii Shatokhin in #755, that when the RCU callback was called on the patched function, from unloaded livepatch module triggered a kernel crash.
This patch implements the approach on Powerpc outlined in #755. With -mcmodel=large, like any other data, function pointers are also loaded relative to the current TOC base and are populated as relocation entries in .toc section. Every function call/passing such function as pointers needs to access them through .toc section + offset.
The simplest approach would be to convert the .toc + offset relocation into a dynamic rela referring to the original function address but the same function is also a patched function. Thus, on PowerPC we need to append a new relocation entry into .rela.toc, duplicating the entry used as a …
> [RFC] PC64le - do not use the patched functions as callbacks directly

- kpatch-build/kpatch-build
- kpatch/kpatch
Cleanup some of the new bash script code to appease 'make check':
- kpatch: Use integer comparison for $MAX_LOAD_ATTEMPTS
- kpatch-build: Quote ${TEMPDIR} variable
> scripts: small ShellCheck cleanups

- kmod/core/core.c
- kmod/patch/livepatch-patch-hook.c
Fixes sparse warnings:
kmod/core/core.c:142:20: warning: symbol 'trace' was not declared. Should it be static?
livepatch-patch-hook.c:73:18: warning: symbol 'lpatch' was not declared. Should it be static?
> sparse: quiet latest trivial complaints

- kpatch-build/create-diff-object.c
- test/integration/centos-7/gcc-static-local-var-6.patch
- test/integration/fedora-27/gcc-static-local-var-6.patch
- test/integration/ubuntu-16.04/gcc-static-local-var-6.patch
On ppc64le, the static local variable correlation doesn't take into
account the .toc rela indirection for data references, meaning that it's
basically broken in many cases.
Fix it by making the code .toc-aware.
Fixes #793.
Reported-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>
> create-diff-object: fix ppc64le static local variable correlation

- test/integration/centos-7/gcc-static-local-var-2.patch
- test/integration/fedora-27/gcc-static-local-var-2.patch
- test/integration/ubuntu-16.04/gcc-static-local-var-2.patch
The test case gcc-static-local-var-2 doesn't uses any macros
from kpatch-macros.h, so remove the hunk including it.
Cc: Joe Lawrence <jdl1291@gmail.com>
> Testcase: Clean up gcc-static-local-var-2

- kpatch-build/create-diff-object.c
Heavy lifting of reading .toc rela entries for rela symbols
referring to .toc + offset, can be simplified using toc_rela() in
rela_equal() and remove the #ifdery guarding PowerPC code.
This patch also trims the commentary related to PowerPC.
> create-diff-object: Refactor rela_equal() using toc_rela()

- Makefile.inc
- contrib/Makefile
- contrib/kpatch.conf
- contrib/kpatch.spec
Currently kpatch rely on systemd to load all kmods on startup.
This patch aims to enable kpatch to be used on upstart systems.
Limitations:
With systemd, it would be possible to unload all modules by issuing:
systemctl stop kpatch
It was not possible to make a reasonable upstart's equivalent of it, so
to unload the modules it will be necessary to call kpatch explicitly:
kpatch unload --all
I believe this it an non-issue, as it is still possible to unload
the modules by calling kpatch explicitly.
Instead of copying the upstart config file (kpatch.conf) directly
to /etc/init, it first copies it to /usr/share/kpatch/contrib,
and on post installation this file is copied to /etc/init if the
target host has upstart installed.
On my tests I have verified that all newly added files by this commit …
> Adding support to upstart systems.

- doc/patch-author-guide.md
Add a note about dealing with sleeping locks in callbacks.
> patch-author-guide: sleeping locks in callbacks

- kmod/core/core.c
The module notifier currently only handles newly loaded modules in the
MODULE_STATE_COMING state.  If target modules need to be unloaded, the
any kpatch module that patches it must first be disabled, releasing
module references held against the target module.  When the kpatch
modules are disabled, the target module is unpatched and the kpatch
core's data structures updated accordingly.
If a loading module happens to fail its init routine (missing hardware
for example), that module will not complete loading.  The kpatch core
doesn't properly account for this "phantom" target module, so when the
kpatch patch module is removed, it spews out an ugly warning when
attempting to remove a non-existing ftrace filter on the target module.
In the problematic case above, the module handler is …
> kmod/core: account for failing modules in notifier

- kpatch-build/create-diff-object.c
Because of signdness difference kpatch_check_relocations() would trigger
an error on any negative addend.
Fix by casting Elf_Data->d_size from size_t to long.
> Fix false-positives in kpatch_check_relocations

- kpatch-build/kpatch-build
If a patch failed a first time, kpatch-build is using the previous
cache directory on subsequent builds. The UBUNTU_KERNEL=1 variable is
not set in this case. Therefore, utsrelease.h is not updated correctly
and the appropriate structures are not used. Just check if distro is
Ubuntu and we didn't request our own specific directory.
Signed-off-by: Vincent Bernat <vincent@bernat.im>
> kpatch-build: fix Ubuntu kernel detection on successive retries

- doc/patch-author-guide.md
Elaborate on the difficulties in using locks/mutexes from the kpatch
callback routines and suggest a few workarounds.
> patch-author-guide: more on locks in callbacks

- test/unit/Makefile.include
Don't suppress stderr in the unit tests, so that create-diff-object
error messages will still be printed.
> unit: don't suppress stderr

- .travis.yml
- kpatch-build/Makefile
Because $PLUGIN variable is a part of $TARGETS we are trying to install
gcc-plugins twice which is treated as an error by install command:
```
/usr/bin/install create-diff-object create-klp-module create-kpatch-module gcc-plugins/ppc64le-plugin.so kpatch-gcc gcc-plugins/ppc64le-plugin.so /usr/local/libexec/kpatch
/usr/bin/install: will not overwrite just-created '/usr/local/libexec/kpatch/ppc64le-plugin.so' with 'gcc-plugins/ppc64le-plugin.so'
```
> ppc64le: fix gcc-plugin installation

- README.md
Update ccache link to point to current version/location.
> readme: fix outdated epel ccache link

- kpatch-build/create-diff-object.c
- test/unit/x86_64/function-ptr-new.ORIG.o
- test/unit/x86_64/function-ptr-new.PATCHED.o
With #755, we started using dynrelas for function pointers.  However,
this behavior only makes sense for function pointers to existing
functions.  For function pointers to *new* functions, just use a normal
rela.
The 'function-ptr-new' unit test is from the following patch:
https://github.com/dynup/kpatch/files/1927198/new-static-callback.patch.txt
Fixes #834.
Fixes: 495e6197508d ("kpatch-build, x86: do not use the patched functions as callbacks directly")
> create-diff-object: skip dynrelas for function pointers to new functions

- kmod/core/core.c
> kmod/core: add check for CONFIG_STACKTRACE

- kpatch/kpatch
I loaded a livepatch on an idle 112 CPU system, and it took over three
seconds for the patch transition to complete:
[1561551.584871] livepatch: 'livepatch_foo': starting patching transition
[1561554.867486] livepatch: 'livepatch_foo: patching complete
Presumably this is because more CPUS == more kthreads and idle tasks,
which are more likely to be running at any given time.
Currently the kpatch script will start signaling tasks if the transition
takes more than five seconds.  Increase that timeout a bit to 15
seconds, to give big/busy systems more time before we start signaling.
> kpatch: increase patch transition stall timeout

- test/unit/Makefile.include
Update submodule to 6774fbc "ppc64le: initial object files"
Remove CDO_ENV since it is moved to per-arch makefiles.
> unittests: object submodule update

- kpatch-build/create-klp-module.c
When a patch is composed of multiple .o files which have
.parainstructions sections, loading the patch causes a panic:
general protection fault: 0000 [#1] SMP
Modules linked in: livepatch_4_9_88_1_20180518_1(OK+) livepatch_4_9_88_1_20180510_1(OK) ...
CPU: 1 PID: 17257 Comm: insmod Tainted: G           O  K 4.9.0-6-amd64 #1 Debian 4.9.88-1
Hardware name: HP ProLiant MicroServer Gen8, BIOS J06 11/02/2015
task: ffff9ff3411a4480 task.stack: ffffac8f8271c000
RIP: 0010:[<ffffffff8ae2e1d0>]  [<ffffffff8ae2e1d0>] apply_paravirt+0xc0/0x140
RSP: 0018:ffffac8f8271f9a0  EFLAGS: 00010216
RAX: 00010749ffffffff RBX: ffffffffc0940658 RCX: 0000000000000085
RDX: 00000000bfebfbff RSI: ffffac8f8271f9a2 RDI: 0000000000000246
RBP: ffffac8f8271f9a2 R08: 0000000000000085 R09: ffffffff8ae5acb0
R10: …
> create-klp-module: Properly align merged .parainstructions sections

- kmod/patch/livepatch-patch-hook.c
The 'immediate' flag removal is going to be backported to RHEL 7.
Adjust the check accordingly.
> livepatch-patch-hook: add RHEL immediate check

- test/unit/Makefile
This fixes the following error with an older version of git
(1.8.3.1):
make -C test/unit
make[1]: Entering directory `/root/kpatch/test/unit'
git submodule update --init --rebase
You need to run this command from the toplevel of the working tree.
> test/unit: run submodule command from base git directory

- kpatch-build/gcc-plugins/gcc-common.h
plugin compilation fails on GCC 8:
In file included from gcc-plugins/gcc-common.h:100,
from gcc-plugins/ppc64le-plugin.c:1:
/usr/lib/gcc/powerpc64le-linux-gnu/8/plugin/include/attribs.h: In function ‘tree_node* canonicalize_attr_name(tree)’:
/usr/lib/gcc/powerpc64le-linux-gnu/8/plugin/include/attribs.h:118:11: error: ‘get_identifier_with_length’ was not declared in this scope
return get_identifier_with_length (s + 2, l - 4);
^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/powerpc64le-linux-gnu/8/plugin/include/attribs.h:118:11: note: suggested alternative: ‘get_attr_min_length’
return get_identifier_with_length (s + 2, l - 4);
^~~~~~~~~~~~~~~~~~~~~~~~~~
get_attr_min_length
Makefile:34: recipe for target 'gcc-plugins/ppc64le-plugin.so' failed
get_identifier_with_length() is defined under …
> gcc-plugin: Include additional header for GCC 8

- kpatch-build/create-diff-object.c
When I made a patch to the nfsd module on a ppc64le system with a RHEL 7
based kernel, livepatch prevented the target module from loading with:
livepatch: symbol '.TOC.' not found in symbol table
References to this symbol are treated specially by the kernel module
loader, so references to it should never be converted to dynrelas.
> create-diff-object: don't convert .TOC. references to dynrelas

- .travis.yml
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
- kpatch-build/lookup.c
- kpatch-build/lookup.h
- test/unit/Makefile.include
As discussed in #836 this pull request is a merge of mine and @jpoimboe's attempts to change create-diff-object to take symtable (`eu-readelf -s` output) as an input instead of an object-file.  This will make unit-tests more flexible and will allow us to cover more cases with them.
There is something to discuss though: when I tried to get a symtab that would work with preexisting test objectfiles I couldn't as I lost the config I used. Even if I rebuild all of those now so that they all work with a single vmlinux.symtab - it would be unreasonable to expect other contributors to rebuild their objectfiles using a specific config/kernel version. Should we just always use per-test symtab(and possibly symvers) files then? As I understand in most cases they can be generated from .ORIG.o (we can …
> create-diff-object symtab

- kpatch-build/create-klp-module.c
- kpatch-build/kpatch-elf.h
From Oracle's Linker and Libraries Guide [1]:
"The symbols in a symbol table are written in the following order ...
The global symbols immediately follow the local symbols in the symbol
table. The first global symbol is identified by the symbol table sh_info
value. Local and global symbols are always kept separate in this manner,
and cannot be mixed together."
[1] https://docs.oracle.com/cd/E19120-01/open.solaris/819-0690/chapter6-79797/index.html
Fixes #854.
> create-klp-module: group .kpatch.symbols with like-scope

- test/integration/kpatch-test
Since c0105ea46774 ("kpatch-build: set default module prefix
accordingly") kpatch-build has automatically named resulting patch
modules with a "kpatch-" or "livepatch-" prefix (depending on its type).
To avoid naming confusion, have kpatch-test name all of its patch
modules with a "test-" prefix.
Fixes #867.
> testing: kpatch-build should set all module names

- test/unit/Makefile
Don't try to call unittest clean if objfile dir is non-existant (e.g.
when objfile submodule wasn't cloned). Another solution would be to make
clean target dependant on objdir but that would mean downloading a lot
of unneeded data for users who don't run unit-tests.
Fixes: #872
> unittests: skip clean if objdir is not present

- kpatch-build/kpatch-build
"make mrproper" combined with the '-t' flag is dangerous, as it results
in the Module.symvers file getting truncated, which causes
create-diff-object to create some funky dynrelas.  Detect this condition
in kpatch-build and error out.
We will hopefully also be removing "make mrproper" soon, which will make
'-t' even more useful.
Fixes #589.
> kpatch-build: detect truncated Module.symvers

- kmod/patch/livepatch-patch-hook.c
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
Since the codeset supports just the 64 bit variant, lets move
to __powerpc64__ and use it. I checked the ABI doc as well
and the kernel/gcc.
Signed-off-by: Balbir singh <bsingharora@gmail.com>
> trivial: __powerpc__ should be __powerpc64__

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
Finally add support for processing the ORC unwinder sections.
The ORC unwinder sections are more special than the other special
sections, so they need their own dedicated function to process them,
though the code is similar to kpatch_regenerate_special_sections().
BTW, upstream livepatch still doesn't support the ORC unwinder.  That
change will be coming soon (probably Linux 4.19).
Fixes #785.
> create-diff-object: add ORC section support

- kpatch-build/kpatch-build
If $AWK_OPTIONS are blank gawk would treat "" as a blank script
resulting in none of the special struct being detected.
Fixes: 1330dcc "create-diff-object: add ORC section support"
> kpatch-build: fix find_special_section_data with blank AWK_OPTIONS

- kpatch-build/create-diff-object.c
Building with GCC 7.3.0 on Debian sid fails with the following error:
gcc -g -O2 -fdebug-prefix-map=/build/kpatch-0.6.0=. -fstack-protector-strong -Wformat -Werror=format-security -MMD -MP -I../kmod/patch -Iinsn -Wall -Wsign-compare -g -Werror -Wdate-time -D_FORTIFY_SOURCE=2  -c -c
create-diff-object.c: In function 'kpatch_compare_correlated_rela_section':
create-diff-object.c:316:20: error: 'toc_data1' may be used uninitialized in this function [-Werror=maybe-uninitialized]
return toc_data1 == toc_data2;
~~~~~~~~~~^~~~~~~~~~~~
create-diff-object.c:256:16: note: 'toc_data1' was declared here
unsigned long toc_data1, toc_data2;
^~~~~~~~~
cc1: all warnings being treated as errors
This is a false positive as the code only compares those two values
after initializing them. But lets keep GCC …
> create-diff-object: prevent "'toc_data1' may be used uninitialized" warning

- kpatch-build/kpatch-build
shellcheck 0.4.7 reported the following errors:
[  "$1" = "$(echo -e "$1\n$2" | sort -rV | head -n1)" ]
^-- SC1117: Backslash is literal in "\n". Prefer explicit escaping: "\\n".
grepname="$grepname\.o"
^-- SC1117: Backslash is literal in "\.". Prefer explicit escaping: "\\.".
grep "undefined reference" "$LOGFILE" | sed -r "s/^.*\`(.*)'$/\1/" \
^-- SC1117: Backslash is literal in "\1". Prefer explicit escaping: "\\1".
> kpatch-build: fix shellcheck warnings

- kpatch-build/kpatch-build
Some of the provisioned machines I sometimes use don't have enought
diskspace for a full kpatch-patch build in a home partitions, I usually
solve this by symlinking .kpatch(and .ccache) dirs to a different
partition, however this only works with -s option because of
clean_cache().
clean_cache() currently removes .kpatch directory completely, recreating
it from scratch, change it to only remove the contents of the directory
instead.
> kpatch-build: less agressive clean_cache()

- kpatch-build/kpatch-build
This PR started with a fixup for yumdownloader and CentOS and I noticed that `kpatch-build` was failing on my RHEL-ALT ppc64le setup.  Looking for ".el7a." in `$KVER` was failing as `$KVER` looked like `83.el7a`, so adjust the script to look for it in the unadulterated `$ARCHVERSION` string.
> Kpatch build misc fixes, round 2

- README.md
Update gcc-plugin-devel package dependency for livepatch
modules on ppc64le.
Suggested-by: Joe Lawrence <jdl1291@gmail.com>
> readme: Update gcc-plugin-devel dependency

- kpatch-build/create-diff-object.c
.text section addralign value might chance between original and
patched .o files, for a loop() such as:
for (i = 0; i < sections_per_block; i++) {
remove_memory(nid, base, MIN_MEMORY_BLOCK_SIZE);
base += MIN_MEMORY_BLOCK_SIZE;
}
On ppc64le, which translate to:
f0:   78 1b 7b 7c     mr      r27,r3
f4:   6c 00 9d 40     ble     cr7,160 <pseries_remove_memblock+0x158>
f8:   ff ff 9c 3b     addi    r28,r28,-1
fc:   38 00 a1 fb     std     r29,56(r1)
100:   00 01 bf 3f     addis   r29,r31,256
104:   08 c2 9c 7b     rldic   r28,r28,24,8
108:   14 ea 9c 7f     add     r28,r28,r29
10c:   14 00 00 48     b       120 <pseries_remove_memblock+0x118>
110:   00 00 00 60     nop
114:   00 00 00 60     nop
118:   00 00 00 60     nop
11c:   00 00 00 60     nop
120:   78 fb e4 7f     mr      r4,r31 …
> create-diff-object: Relax sh_addralign check for .text sections

- kpatch-build/kpatch-build
Commit d86c1113cc25 ("kpatch-build: less aggressive clean_cache()")
broke clean_cache().  Instead of expanding the wildcard, it tries to
delete a file named '*'.
> kpatch-build: fix clean_cache

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.h
This is my attempt at fixing #865 and #866. I tried to keep the commits small so that it would be easier to follow and fix if some of the approaches are sub-optimal.
Build/load/unload/run tested with [unlikely-likely.patch.txt](https://github.com/dynup/kpatch/files/2097337/unlikely-likely.patch.txt) on top of 4.17 which covers both cases. Also build-tested with all of the integration-tests we have and it now builds all of the patches gcc7 does successfully.
Note: if the patch causes a function to change subsections (.e.g. .text -> .text.unlikely) it will be marked as CHANGED and included in the output even if the actual contents of the function were not changed. This makes sense to me but can be a source of confusion I guess.
> gcc8 fixes

- kpatch-build/kpatch-build
- Future releases of RHEL / CentOS will provide the yumdownloader
program with the 'dnf-utils' package (not 'yum-utils').  Instead of
looking to see that the package is installed, just look for the
program itself.
- RHEL / CentOS 8 kernel release names (as returned by 'uname -r') may
not match the SRPM buildroot release subdirectory name.  Relax the
wildcard when moving this directory to $SRCDIR.
> kpatch-build: update for RHEL / CentOS 8

- kpatch-build/create-diff-object.c
GCC puts the constant variable requiring relocation into .data.rel. or
.data.rel.ro depending upon the bind type of the symbol. Extend
is_bundledable() to check these .data sections too.
> create-diff-object.c: Extend is_bundleable()

- contrib/kpatch.spec
- kpatch/kpatch
Create a minor release that includes fixes for:
- ppc64le: relax .text section addralign value check
- gcc8: unit-tests
- gcc8: support parent/child symbol relations
- gcc8: handle functions changing subsection
- gcc8: consider ".text.hot" sections bundleable
- kpatch-build: bugfix for less aggressive clean build-cache
- ubuntu: remove "-signed" substring from the kernel source package name
- ubuntu: explicitly note elfutils dependency
- upstream 4.18: unit-tests
- upstream 4.18: KCFLAGS -mcount-record support support
- RHEL-8: don't care who provides yumdownloader
- RHEL-8: account for quirky SRPM / release name conventions
> Patch release v0.6.2

- man/kpatch-build.1
The man page earlier said that kpatch-build only works for Fedora, so I
added all the other distros it works for based on the README.
Signed-off-by: Sanskriti Sharma <sansharm@redhat.com>
> Added distros to man page

- kpatch-build/create-diff-object.c
Sometimes due to config-dependency issues or other reasons whole
object-files would get optimized out from final vmlinux/module, in cases
like this create-diff-object would fail during symbol lookup table
creation in lookup_open(). Because lookup_open() call is situated before
we established that objectfile has changed this triggers not only on
real problems, but also during mass-rebulds caused by changes to
header-files. While it usually indicates a real issue with config this
should not prevent kpatch from building.
Move lookup_open() call so that it is called only for changed
object-files.
Fixes #910
> Move lookup_open() call to a later stage.

- kpatch-build/lookup.c
Starting with 1b1eeca7e4c1 "init: allow initcall tables to be emitted using
relative references" [1] __init functions are generating an "__addressable_"
symbol in a ".discarded.addressable" section so it does not show up in final
vmlinux triggering find_local_syms failures. Add "_addressable_" to the list
in maybe_discarded_sym().
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1b1eeca7e4c19fa76d409d4c7b338dba21f2df45
> Add "__addressable_" to maybe_discarded_sym().

- kpatch-build/kpatch-build
Without this patch the tests fail because shellcheck exits with an error.
Noticed with shellcheck 0.5.0 on Debian sid while trying to build 0.6.2.
Regards
Simon
> kpatch-build/kpatch-build: use `command -v` instead of `which`

- README.md
- kpatch-build/kpatch-build
- kpatch-build/kpatch-gcc
This PR is a first pass at implementing support for out-of-tree modules. The workflow is slightly different from the standard kpatch workflow for building in-tree modules, in large part because out of tree modules have a variety of ways that they are build and varied file structures that are hard to account for in a tool like this.  It requires an external source directory that is set up and ready to build, and it may require that a symlink be created to the Module.symvers file depending on where it is located in the external source directory.
If people have strong feelings about better ways to implement this feature, or ways to make it easier to use, I am happy to tweak the approach take in the PR, this is just the way that seemed easiest to me.
This PR passes make check and make unit, …
> Add support for building out-of-tree modules

- kmod/patch/Makefile
While adding proper linker script option my previous patch left the
linker script in the list of source files (on pre-4.20 kernels) for
ld somehow breaking kpatch callback sections. For this to work
properly kpatch.lds needs to be added to 'extra-y' instead of objs. And
for kbuild to process this option properly we need to call make without
the .ko target, i.e. let kbuild decide what to build.
Fixes: 17a97b4 ("kmod/patch: fix patch linking with 4.20")
P.S. I also don't think patch-hook.o target in this makefile does anything unless manually called as `make patch-hook.o` but that is a separate issue.
> kmod/patch: more linking fixes

- kpatch-build/create-diff-object.c
For fun I tried to create a livepatch of upstream patch
ad211f3e94b314a910d4af03178a0b52a7d1ee0a for my kernel. This
caused kpatch-build to fail with a NULL pointer derefence because
base_locals was NULL (returned via kpatch_elf_locals(), which
can return a NULL pointer). This patch fixes the SIGSEGV
via a NULL check. The end result is a live patch is created
and loaded.
Signed-off-by: Balbir singh <bsingharora@gmail.com>
> Fix NULL pointer deref in main due to base_locals

- test/integration/centos-7/shadow-newpid.patch
When quickly loading/unloading this patch multiple times it is possible
to hit "Duplicate shadow variable" warnings since the patch doesn't have
any cleanup hooks on unload.
Switch to klp_shadow_get_or_alloc to ignore these.
> integration/centos-7: fix shadow-newpid.patch warnings

- test/unit/Makefile.include
Add support for optional <test-name>.env files that contain additional
environment variables. This can also be used to override per-arch env
vars we have because last value assigned will be used.
> test/unit: add support for .env files

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
Add support for jump labels, also known as static jumps, static keys, static branches, and jump tables.  Luckily, kpatch_process_special_sections() is already generic enough to make this an easy fix.
Fixes #931.
> Add jump label support

- kpatch-build/create-diff-object.c
kpatch_mark_ignored_sections include .rodata.str1.1 section but does
not include its section symbol, causing its section symbol can not be
included any more in kpatch_include_standard_elements. After the
section symbol is freed in kpatch_elf_teardown, we got a segmentation
fault in kpatch_create_intermediate_sections.
Signed-off-by: Zhipeng Xie <xiezhipeng1@huawei.com>
> kpatch-build: include secsym in kpatch_mark_ignored_sections

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
This reverts commit 87c64519fce02424e00725ddaeff8b619d40d160.
The jump label support doesn't work with upstream livepatch.  Joe
Lawrence found the following ordering issue:
```
load_module
apply_relocations
/* Livepatch relocation sections are applied by livepatch */
if (info->sechdrs[i].sh_flags & SHF_RELA_LIVEPATCH)
continue;
post_relocation
module_finalize
jump_label_apply_nops        << crash
...
do_init_module
do_one_initcall(mod->init)
__init patch_init [kpatch-patch]
klp_register_patch
klp_init_patch
klp_init_object
klp_init_object_loaded
klp_write_object_relocations
```
So jump_label_apply_nops() is called *before*
klp_write_object_relocations() has had a chance to write the klp
relocations (.klp.rela.kvm_intel.__jump_table, for example).
We need to resolve this upstream first. …
> Revert "create-diff-object: add jump label support"

- test/unit/Makefile.include
Some unit tests may need debug symbols to reproduce problems (see
issue #928 for example), so skip the unit-test Makefile.include
check_stripped call for objects that include "NOSTRIP" in their
filename.
> test/unit: relax stripped object requirement

- README.md
- kpatch-build/kpatch-gcc
- man/kpatch-build.1
Two small changes to out-of-tree module support.  
@pcd1193182 : were we building out-of-tree module kpatches differently when working on #923?  I just want to make sure I'm not breaking another use case with this change
> Out of tree module fixes

- kpatch-build/kpatch-elf.c
> kpatch-build: fix memleak in function kpatch_write_output_elf

- contrib/kpatch.spec
- kpatch/kpatch
Create a minor release that includes fixes for:
- Lots of integration test work
- Better support for building out-of-tree modules
- Updated manpage options, drop deprecated distro specific mentions
- README.md updates for shadow variables, out-of-tree modules
- Fix core module compilation with CONFIG_HAVE_ARCH_PREL32_RELOCATIONS
- kpatch-build detects and abort on unsupported options
GCC_PLUGIN_LATENT_ENTROPY, GCC_PLUGIN_RANDSTRUCT
- Fix patch linking with 4.20+
- Other minor shellcheck and kpatch-build fixups
> Patch release v0.6.3

- kpatch-build/create-diff-object.c
- kpatch-build/lookup.c
reason: Firstly, in the function lookup_open use the malloc to
allocate some memory, but call the function lookup_close
to free the memory.
Secondly, table->obj_sym->name, table->exp_sym->name and
table->exp_sym->objname used the strdup, so them should
free also.
Thirdly, adjust the order of make_nodname, if not, it
will cause an exception when free(exp_sym->objname) in
lookup_close.
> create-diff-objject: fix memleak of the struct lookup_table

- kpatch-build/lookup.c
Fix memory leak in symtab_read(), by removing the duplicate strdup()
of obj_syms.name.
> lookup: Fix memleak in symtab_read()

- kpatch-build/create-klp-module.c
reason: The strdup() function returns a pointer to a new string
which is a duplicate of the string s.  Memory for the
new string is obtained with malloc, and can be freed
with free.
here, the name and objname do not use anymore, so it
should be free.
> fix memleak in the create-klp-module.c

- kmod/patch/livepatch-patch-hook.c
reason: after calling the function klp_unregister_patch in patch_exit,
the lpatch must be freed, otherwise, it would cause memory leak.
> kmod: fix memleak in the function patch_exit

- kmod/patch/livepatch-patch-hook.c
In v5.0, upstream kernel commit 958ef1e39d24 ("livepatch: Simplify API
by removing registration step") removed klp_(un)register_patch().  We
only need to call klp_enable_patch() now.
> livepatch-patch-hook: skip klp_(un)register_patch() for v5.0+ kernels

- kpatch-build/kpatch-build
reason:	when I make a livepatch for a out of module.Cause the error
as follow:
ERROR: invalid ancestor xxx/xxx.o for xxx/xxx.o.
The testcase is as follow:
wwheart@linux41:~/helloworld 0 > tree
├── hello.c
├── Makefile
├── test.patch
└── xxx
├── xxx.c
└── xxx.h
wwheart@linux41:~/helloworld 0 > cat test.patch
diff --git a/xxx/xxx.c b/xxx/xxx.c
index aab3c67..d81ad00 100644
--- a/xxx/xxx.c
+++ b/xxx/xxx.c
@@ -1,6 +1,7 @@
#include <linux/kernel.h>
void czf_test(void)
{
+       printk("livepatch test\n");
printk("xxx\n");
}
Makefile:
obj-m += buffer_overflow1.o
buffer_overflow1-y += hello.o xxx/xxx.o
> kpatch-build/kpatch-build: fix error of invalid ancestor

- kpatch/kpatch
We can no longer use klp_register_patch symbol to determine if the
kernel is livepatch-enabled. Use klp_enable_patch instead.
> Fix livepatch-enabled kernel detection in kpatch script

- kpatch/kpatch
Since commit c9614c429822b kpatch has support for upstart systems,
which means we should test the existence of `systemctl` before executing
it.
The command `command` is POSIX compliant, and should be widely
available.
Signed-of-by: Bruno Loreto <loretob@amazon.com>
> Testing systemctl existence before executing it

- kpatch-build/create-diff-object.c
The create-diff-object don't create .kpatch.dynrelas and
.rela.kpatch.dynrelas sections which are removed to
create-kpatch-module, so the condition is unneeded yet.
> create-diff-object: remove unneeded condition

- kpatch-build/kpatch-gcc
After changing the gcc name in a linux tree to gcc72, kpatch-build failed to
produce hotpatches with the error message "ERROR: no changed objects found."
This is due to a wrapper script called kpatch-gcc, called while kpatch-build
builds the kernel, which checks if the compiler name matches exactly gcc,
failing the check when comparing to gcc72, and thus not producing the expected
file changed_objs containing the list of changed objects.
This commit fixes this issue by loosening the check on the gcc name.
Signed-off-by: Bruno Loreto <loretob@amazon.com>
Reviewed-by: Bjoern Doebel <doebel@amazon.com>
Reviewed-by: Amit Shah <aams@amazon.com>
Reviewed-by: Pawel Wieczorkiewicz <wipawel@amazon.com>
> Making kpatch-build compatible with custom gcc names

- kpatch-build/kpatch-elf.c
kpatch-elf::kpatch_write_output_elf will call the gelf_getclass()
to acquire the output elf's class. But the input parameter kelf->elf
is NULL, the gelf_getclass(kelf->elf) will return ELFCLASSNONE, not
the value we expect ELFCLASS32 or ELFCLASS64.
the gelf_getclass function code:
int
gelf_getclass (Elf *elf)
{
return elf == NULL || elf->kind != ELF_K_ELF ? ELFCLASSNONE : elf->class;
}
the gelf_newehdr fuction code:
void *
gelf_newehdr (Elf *elf, int class)
{
return (class == ELFCLASS32
? (void *) INTUSE(elf32_newehdr) (elf)
: (void *) INTUSE(elf64_newehdr) (elf));
}
Luckily, when we create a patch for x86_64, if we pass the ELFCLASSNONE
for the function gelf_newehdr, it will return elf64_newehdr, so don't
cause the fault. But it's better to use the gelf_getclass(elf) instead of …
> kpatch-elf: fix the unexpected elf class

- kpatch-build/kpatch-build
- kpatch/kpatch
make check using shellcheck version 0.6.0 suggests following
improvements:
In kpatch/kpatch line 160:
if [[ ! -z "$checksum" ]] && [[ -e "$SYSFS/${modname}/checksum"]] ; then
^-- SC2236: Use -n instead of ! -z.
In kpatch-build/kpatch-build line 953:
[[ ! -z "$UNDEFINED" ]] && die "Undefined symbols: $UNDEFINED"
^-- SC2236: Use -n instead of ! -z.
'-n' and '! -z' are used interchangeably across the scripts, let's use
'-n' consistently to check a non-empty string instead of using negation.
> kpatch, kpatch-build: Use -n instead of ! -z

- test/integration/centos-7/fixup-section.patch
- test/integration/ubuntu-16.04/fixup-section.patch
These patches previously would try to dereference a userspace pointer
directly which can cause issue on some systems. Since the aim of these
patches is to check fixup section changes we can don't need to do any
meaningful changes to the function, so change the patches to just add
asm("nop") instead.
> Update fixup-section patches

- kpatch-build/kpatch-build
- kpatch-build/lookup.c
readelf is more standard, using readelf insteaded we should solve there
issues:
First, using "readelf -s", the symbol name would truncated by 25 chars,
to solve this issue, add option "--wide".
Second, the size may be mixed of decimal and hex, we get the size by "%s",
and use strtoul(size, NULL, 0) to convert the size.
Third, the symbol type is SHN_UNDE, the Ndx display "UND", so changed to
compare with "UND".
> kpatch-build: use readelf instead of eu-readelf

- test/difftree.sh
- test/unit/Makefile.include
readelf is more standard, using readelf insteaded
test/difftree.sh: the symbol name may be with "FILE", which may be
get a incorrect count, here add "awk".
test/unit/Makefile.include: use "readelf -s --wide" instead of
"eu-readelf -s".
> test: use readelf instead of eu-readelf

- kpatch-build/create-diff-object.c
.altinstr_replacement section may have relocation symbols which need to
be included, therefore we should call kpatch_include_symbol() to ensure
that its section is included as well.
The special section processing should also occur before
kpatch_print_changes() to provide accurate logging info.
> kpatch-build: ensure that .altinstr_replacement section is included

- kpatch-build/lookup.c
commit 767d9669bd13 ("kpatch-build: use readelf instead of eu-readelf")
replaced eu-readelf with readelf for constructing symbol table.  The
format of symbol table entries differs a little on Power when the symbol
is a function with binding type LOCAL.  For example, consider:
23: 0000000000000008    96 FUNC    LOCAL  DEFAULT [<localentry>: 8]    4 cmdline_proc_show
An extra column preceding index of the symbol denoting symbol value to
be local entry point offset of the function is printed, with the
current sscanf format string in lookup::symtab_read the values will
mismatch ending with in-accurate lookup table getting constructed. This
patch fixes it by introducing a Power specific format string for
function symbols with bind type LOCAL.
Fixes: 767d9669 ("kpatch-build: use readelf instead …
> lookup: Fix format string for symtab_read() on PPC64LE

- kpatch-build/kpatch-elf.c
kpatch-elf::create_section_pair would create new rela section, and the
relasec->data->d_type is not set, which is a random value, and it will
use in kpatch-elf::kpatch_write_output_elf
data->d_type = sec->data->d_type;
which would cause Segmentation fault in kpatch_write_output_elf::elf_update.
Program received signal SIGSEGV, Segmentation fault.
(gdb) bt
0  0x00007ffff7bcd8d2 in __elf64_updatefile at elf64_updatefile.c
1  0x00007ffff7bc9bed in write_file at elf_update.c
2  0x00007ffff7bc9f16 in elf_update at elf_update.c
3  0x000000000040ca3d in kpatch_write_output_elf at kpatch-elf.c
4  0x0000000000409a92 in main at create-diff-object.c
> kpatch-elf: fix Segmentation fault when d_type not set properly

- contrib/kpatch.service
The kpatch.service file shouldn't unload patch modules on service stop
(this is also executed by systemd on reboot).  Patch modules may not be
designed to be safely unloaded and/or may patch kernel routines that
need to continue to run throughout system bring down.
Suggested-by: disaster123
> contrib/service: don't unload modules on stop

- kpatch-build/kpatch-build
- kpatch-build/lookup.c
```
commit f8213c87f64a ("lookup: Fix format string for symtab_read() on
PPC64LE") fixed the symbol table lookup when readelf adds ppc64le
"[<localentry>: 8]" info for functions like so:
23: 0000000000000008    96 FUNC    LOCAL  DEFAULT [<localentry>: 8]    4 cmdline_proc_show
however, it seems that readelf 2.30-57.el8 displays this in a slightly
different format:
24493: c000000000587970    96 FUNC    LOCAL  DEFAULT    2 cmdline_proc_show    [<localentry>: 8]
Instead of adding more cases to kpatch-build's lookup.c scanf format,
let's just delete this information from the symtab file with a quick and
dirty sed regex.  This allows us to handle both observed cases (and
perhaps others) while removing the arch-specific scanf formatting in
lookup.c
Fixes: f8213c87f64a ("lookup: Fix format …
```
> kpatch-build: remove localentry data from ppc64le symtab

- kpatch/kpatch
For "kpatch load" invocations, don't set failing return status if the
kpatch module is already loaded and enabled.  This allows the user to
more gracefully restart the kpatch.service, or re-run "kpatch load
--all" commands to pick up new kpatch modules.
Fixes: #979
> kpatch script: don't fail if module already loaded+enabled

- kpatch-build/create-diff-object.c
This patch series implements the phase 1 and other powerpc related quirks discussed at #974.
1. First patch fixes the group size of lwsync fixup special section
2. Second patch add support for __barrier_nospec_fixup special section
3. The last patch adds checks to assert if the function being patched, calls any of the *_fixup section and error out for such patches.
> ppc64le: Feature fixup

- kmod/core/core.c
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
Starting with binutils 2.31, the Linux kernel may have R_X86_64_PLT32
relocations. Make sure we support them. This should be as simple as
treating R_X86_64_PLT32 exactly like R_X86_64_PC32 everywhere. For more
details see upstream commit torvalds/linux@b21ebf2.
This also fixes the following issue seen on Fedora 29:
```
$ kpatch-build/kpatch-build -t vmlinux ./test/integration/fedora-27/convert-global-local.patch
Using cache at /home/jpoimboe/.kpatch/src
Testing patch file(s)
Reading special section data
Building original source
Building patched source
Extracting new and modified ELF sections
ERROR: slub.o: 1 function(s) can not be patched
slub.o: function __kmalloc has no fentry/mcount call, unable to patch
/home/jpoimboe/git/kpatch/kpatch-build/create-diff-object: unreconcilable …
```
> Add support for R_X86_64_PLT32

- test/unit/Makefile
"make unit" automatically rebases the submodule, which causes a lot of
surprises.  Instead, just print a warning if it's out of date.
> test/unit: Don't automatically rebase submodule

- test/unit/Makefile.include
Make 3.8 doesn't support the "file" function, which is used by the unit
test Makefile to output the contents of a custom env file, if one
exists.  Use shell instead.
> test/unit: Fix env override for Make 3.x

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
Create an error if a patched function uses a jump label.  We need this
until upstream livepatch supports them with a .klp.arch section.
Fixes #946.
> create-diff-object: Don't allow jump labels

- contrib/kpatch.spec
- kpatch/kpatch
Increment version to v0.7.0 due to changed behavior of kpatch.service and
kpatch load subcommand. Full list of changes:
- Multiple memory leak fixes in kpatch-build
- livepatch-patch-hook compatability fixes for kernels 5.1+
- Making kpatch-build compatible with custom gcc names
- Added rhel-rebased integration tests
- kpatch.service will no longer unload modules on stop
- kpatch load will no longer fail if a module is already loaded and enabled
- kpatch-build will now check for *_fixup section changes on ppc64le and will
fail on such changes
- Add support for R_X86_64_PLT32
- don't allow jump labels
- ppc64le-specific kpatch-build fixes
> Bump version to v0.7.0

- test/unit/Makefile.include
The ppc64le unit tests are failing because the lookup code is getting
confused by the "[<localentry>: 8]" string in the readelf symbol table
output.
Remove the string so the lookup code can parse it correctly.
kpatch-build already uses the same sed, so they should match.
> test/unit: Fix symtab generation for ppc64le

- kpatch-build/kpatch-build
The list of prerequsite RPMs which are needed to build the kernel RPM is
constantly growing.  But at least some of those RPMs aren't strictly
necessary for building the kernel, at least for kpatch-build's purposes.
Requiring them all to be installed is a bit overkill, and sometimes
causes kpatch-build to fail when it doesn't need to.
If the build does fail, we can always check the kpatch.log file and
update the dependencies listed in the README as needed.
> kpatch-build: Use rpmbuild --nodeps

- kpatch-build/kpatch-build
Apply a sed filter to remove "[<localentry>: 8] " info from
readelf --wide --symbols output.  This ensures consistent column
data for the awk script creating the new_symbols file.
Fixes #994
> kpatch-build: remove localentry info from ppc64le new_symbols file

- kpatch-build/create-diff-object.c
- test/integration/rhel-7.5/new-function.patch
- test/integration/rhel-7.6/new-function.patch
Before doing a sibling call, the patched function restores the stack to
its caller's stack.  The kernel-generated call stub then writes the
patch module's r2 (toc) value to the caller's stack, corrupting it,
eventually causing a panic after it returns to the caller.
Fix it by disallowing sibling calls from patched functions on ppc64le.
In theory we could instead a) generate a custom stub, or b) modify the
kernel livepatch_handler code to save/restore the stack r2 value, but
this is easier.
> create-diff-object/ppc64le: Don't allow sibling calls

- test/unit/Makefile.include
Use make's .DELETE_ON_ERROR special target to make sure we don't have
any .OUTPUT.o leftovers for failed tests.
Fixes: #999
> tests/unit: fix inconsistent FAIL test failures

- contrib/kpatch.spec
- kpatch/kpatch
- Fix several powerpc-specific bugs, including two which can result in
kernel panics
- Use rpmbuild --nodeps for installing srpm on Fedora/RHEL
- Fix inconsistent unit test failures for FAIL tests
> Bump version to v0.7.1

- kpatch-build/kpatch-build
On some systems the linker produces compressed debug sections by
default. It is not supported by create-diff-object for now.
Fixes: #877
Signed-off-by: Stefan Strogin <steils@gentoo.org>
> create-diff-object: disable DWARF compression explicitly

- kpatch-build/kpatch-build
The flag -gz[=type] was added in GCC 5. To support older GCC versions
check if the flag is supported before adding it to KCFLAGS.
Fixes: #1012
Signed-off-by: Stefan Strogin <steils@gentoo.org>
> kpatch-build: check if gcc supports -gz=none

- test/integration/lib.sh
Standard centos7 repos don't contain ccache so we have to install it
from epel just like we do on rhel7.
> tests/integration: fix dependency ccache on centos 7

- kmod/core/core.c
Virtuozzo uses the old KPatch core (kpatch.ko) for binary patches for the older kernels and relies on atomic replacement of patches.
When I was trying to replace a loaded binary patch (P1) with a new one (P2) that changed a smaller set of kernel functions (a faulty part was removed in P2), kernel crashed in certain cases.
Assume that patch P1 changes functions F1(), F2() and F3() while patch P2 - F1() only. I saw in the crash reports that the kernel was executing its original variant of F2() and the variant of F3() from P1 at that moment. This inconsistency caused problems because F2() and F3() were dependent on one another.
kpatch_apply_patch() does check if the functions from the patch to be replaced are currently running. However, the functions are removed from
'kpatch_func_hash' in …
> Patch replacement fixes for the old KPatch core

- kpatch-build/create-diff-object.c
We saw the following panic on ppc64le when loading the macro-callbacks
integration test:
```
livepatch: enabling patch 'kpatch_macro_callbacks'
Oops: Exception in kernel mode, sig: 4 [#1]
LE SMP NR_CPUS=2048 NUMA pSeries
Modules linked in: kpatch_macro_callbacks(OEK+) rpcsec_gss_krb5 auth_rpcgss nfsv4 dns_resolver nfs lockd grace fscache sunrpc sg pseries_rng xts vmx_crypto xfs libcrc32c sd_mod ibmvscsi scsi_transport_srp ibmveth dm_mirror dm_region_hash dm_log dm_mod [last unloaded: kpatch_gcc_static_local_var_6]
CPU: 2 PID: 17445 Comm: insmod Kdump: loaded Tainted: G           OE K  --------- -  - 4.18.0-128.el8.ppc64le #1
NIP:  d00000000bb708e0 LR: c0000000001fd610 CTR: d00000000bb708e0
REGS: c00000040e98f640 TRAP: 0700   Tainted: G           OE K  --------- -  - …
```
> create-diff-object: Don't strip callback symbols

- kpatch/kpatch
Ever since upstream v5.1 (specifically commits 0b3d52790e1c ("livepatch:
Remove signal sysfs attribute") and cba82dea3061 ("livepatch: Send a
fake signal periodically") the kpatch utility script's
signal_stalled_processes() functionality has been redundant.
Remove this code from the script to avoid user confusion or potentially
weird user vs. kernel signalling race conditions.
Fixes: #1022
> kpatch: remove manual signaling logic

- contrib/kpatch.spec
- kpatch/kpatch
Increment version to v0.8.0 due to manual signaling logic being removed
from kpatch util. Full list of changes:
- kpatch.ko atomic replace fixes
- Fixes for potential problems found by covscan
- Remove manual signaling logic from kpatch utility
- Don't strip callback symbols
- Allow dynamic debug static keys
> Bump version to v0.8.0

- kpatch-build/kpatch-build
Recent distros don't require you to set 'ulimit -c unlimited'.  Instead
they place core files in a distro-specific location.  Update the SIGSEGV
error message accordingly.
Fixes: #1025
> kpatch-build: update core file error message

- README.md
- kpatch-build/kpatch-build
Run the input patch(es) through lsdiff and then verify that no obviously
unsupported files are directly modified (e.g. assembly .S files).
> kpatch-build: sanity check patched filenames

- kpatch-build/kpatch-build
Somewhere starting with 5.3 (probably with 9f69a496f100 "kbuild: split
out *.mod out of {single,multi}-used-m rules", but that is not
confirmed) .mod and correcponding .mod.cmd files started showing up
during module builds throwing off kpatch-build's find_parent_obj() func.
Filter out any files ending with .mod.cmd as they are definitely not the
parent.
> Fix parent matches for kernels newer than 5.3

- kpatch-build/create-diff-object.c
We are seeing the following error on a real world patch:
unsupported reference to special section __barrier_nospec_fixup
The kpatch commit bb444c2168d1 ("create-diff-object: Check for *_fixup
sections changes") created this error because we were trying to be
future proof.  However, that may have been overly paranoid, as it
doesn't seem likely that those fixup sections will need relocations
anytime soon, because the replacement instructions are manually
generated in code.  And anyway that "future proof" commit breaks the
present.
Also we decided at LPC that we are going to remove .klp.arch sections
anyway, so once that happens we will be fully future-proof anyway.
This reverts commit bb444c2168d17ba7a67a2329ea7ed6f9b37b45cc.
Fixes #974.
> Revert "create-diff-object: Check for *_fixup sections changes"

- test/integration/rhel-7.4/multiple.test
- test/integration/rhel-7.5/multiple.test
- test/integration/rhel-7.6/multiple.test
- test/integration/rhel-7.7/multiple.test
When these from internal depths of Red Hat upstream paths changed and
now we are one level deeper in directory tree.
The issue probably also exist in rhel8.0 rebase pr #993.
> integration/rhel-*: fix multiple.test

- kpatch-build/kpatch-build
when I make a patch for a module, cause the error as follow:
ERROR: two parent matches for hello.o. Check /tmp/kpatch-build.log for more details.
The Makefile is as follow:
obj-m += m_hello.o
m_hello-y = hello.o
default:
$(MAKE) -C /lib/modules/4.4.21-69-default/build M=$(shell pwd) modules
clean:
$(MAKE) -C /lib/modules/4.4.21-69-default/build M=$(shell pwd) clean
and than cmd "grep -l hello.o ./.*.cmd | grep -Fv hello.o" would get two parant
.m_hello.ko.cmd
.m_hello.o.cmd
but the ".m_hello.ko.cmd" is the parant for "m_hello.o", and ".m_hello.o.cmd" is the
parant for "hello.o".
because the "hello.o" is a substring of "m_hello.o", which will cause the "m_hello.o"
matched for the "hello.o".
> kpatch-build: fix two parent matches error

- Makefile.inc
The stacktrace internal interface has been updated for v5.2. On x86,
among others, this means that stack_trace_save_tsk* is to be used
instead of instantiating a stack_trace struct. Those routines are
currently not exported for module use.
See linux kernel: <25e39e32b0a3> (livepatch: Simplify stack trace retrieval)
for more info about the stacktrace interface changes.
The kernel/livepatch subsystem is the way forward for using kpatch and
there are plans to phase out 'kmod' altogether in the near future.
It is still possible to build and use kmod by doing something like:
$ env BUILDMOD="yes" make
Closes #966
Signed-off-by: Yannick Cote <ycote@redhat.com>
> kmod: don't build module by default

- kpatch-build/kpatch-elf.c
Currently, only rela section get freed. This seems like a simple
scope mistake.
Free all sections regardless of their nature in kpatch_elf_teardown()
> kpatch-elf: Free sections in elf teardown

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
As mentioned on https://github.com/dynup/kpatch/pull/1043.
This change actually breaks some tests I was rebasing for rhel-8.0 with the following kind of error:
(this is on gcc-static-local-var-4.patch)
ERROR: aio.o: kpatch_create_patches_sections: 2708: lookup_local_symbol put_aio_ring_file.isra.19
The issue is due to the fact that we dropped symbol renaming when correlating. For symbols that end with status "SAME" there is no problem as we don't include those in the final object. For symbols that have status "CHANGED", we need to lookup the original symbols to know their address/position in the kernel/module getting patched, but at the point of the lookup, we only have the name from the patched object.
In the above example, put_aio_ring_file.isra.19 from the patched object gets …
> Correlation rename fixes

- doc/patch-author-guide.md
Referenced kernel documentation has moved from txt file to rst. Update
the hyperlink to point to the correct file.
> doc: Update broken hyperlink

- doc/patch-author-guide.md
A few minor updates to the author guide, including scrubbing kpatch.ko and the old stop_machine model from the doc:  link to upstream kernel API documentation where applicable.
> Author guide updates

- kpatch-build/kpatch-build
When patching kernel module dm-persistent-data, I found
that the KOBJFILE_NAME is incorrectly replaced to
dm_persistent-data while the module name in kernel is
dm_persistent_data.
Signed-off-by: Zhipeng Xie <xiezhipeng1@huawei.com>
> kpatch-build: replace all '-' to '_' in KOBJFILE_NAME

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
On x86_64, GCC generates the following instruction to compute
'empty_zero_page - __START_KERNEL_map' (__phys_addr_nodebug(), used in
the implementation of ZERO_PAGE()):
48 ba 00 00 00 00 00 00 00 00   movabs $0x0,%rdx
R_X86_64_64  empty_zero_page+0x80000000
__START_KERNEL_map is 0xffffffff80000000.
However, the relocation addend becomes wrong in the patch module:
48 ba 00 00 00 00 00 00 00 00   movabs $0x0,%rdx
R_X86_64_64  empty_zero_page-0x80000000
Note the sign of the addend.
As a result, ZERO_PAGE(0) returns a wrong value in any function touched
by the patch, which may lead to memory corruption and difficult-to-debug
kernel crashes.
The cause is that 'struct rela' uses 'int' for the addend, which is not
enough to store such values. r_addend from Elf64_Rela is int64_t
(Elf64_Sxword) …
> create-diff-object: fix relocations used for ZERO_PAGE(0)

- kmod/patch/kpatch-patch.h
- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
- kpatch-build/create-kpatch-module.c
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-intermediate.h
#1065 exposed a bug due to GCC's implicit conversion of data types.  Enable `-Wconversion` and `-Wno-sign-conversion` flags to warn about conversions.  This patch series, also adds explicit type casts to the warnings triggered by enabling the flags.
> [RFC] Enable -Wconversion/-Wno-sign-conversion flags

- kpatch-build/create-diff-object.c
Process the debug sections only after all the other inclusion logic has
finished, since it makes decisions based on what else has already been
included.
> create-diff-object: process debug sections last

- kpatch-build/create-diff-object.c
The current code to find the twin of a local static variable allows two
variables of the same name to be wrongly matched with the other's twin.
While there isn't a magic formula to avoid this, make stricter
requirements for twining static local from the original object with
a symbol from the patched object. This reduces the risk of erroneous
matches.
> kpatch-build: Make local static twining stricter

- kpatch-build/create-diff-object.c
Internal CI is reporting a SIGSEGV in create-diff-object when it
processes macro-callbacks.patch, starting with 19baa5b7c7f4
("create-diff-object: process debug sections last").
The problem is that, after changing the order between callback and debug
section inclusion, kpatch_include_debug_sections() now tries to include
the callback section symbols.  But kpatch_include_callback_elements()
inadvertently un-includes the callback section symbols (e.g.,
".kpatch.callbacks.pre_patch") when it un-includes the callback struct
symbols (e.g., "kpatch_pre_patch_data").
So after kpatch_elf_teardown(kelf_patched), the callback section symbols
get freed even though there are DWARF .debug_info relocations which
reference them.  Then kpatch_check_relocations() goes off into the weeds
when it accesses …
> create-diff-object: Don't strip callback section symbols

- test/integration/centos-7/gcc-static-local-var-4.test
- test/integration/rhel-7.4/gcc-static-local-var-4.test
- test/integration/rhel-7.5/gcc-static-local-var-4.test
- test/integration/rhel-7.6/gcc-static-local-var-4.test
- test/integration/rhel-7.7/gcc-static-local-var-4.test
- test/integration/rhel-8.0/gcc-static-local-var-4.test
- test/integration/ubuntu-16.04/gcc-static-local-var-4.test
The gcc-static-local-var-4.patch and test check that unmodified functions
that contain dynamic debugging printk's aren't incorrectly included in
the resulting livepatch .ko.
Note that on RHEL-7.7 ppc64le, the gcc-static-local-var-4.ko livepatch
module may include klp-relocation references to free_ioctx(), a function
that would match the above criteria.  These klp-relocation symbols are
OK as they are only used for referencing said functions, they are not
copies that the check should FAIL on.
Modify gcc-static-local-var-4.test in a few ways:
- Convert it to a LOADED test so that we can ...
- Search /proc/kallsyms instead of using binutils or elfutils (which
may have issues parsing klp-relocations).
- Instead of a grep regex, use awk to string compare exact function
and module names.  This …
> integration: update gcc-static-local-var-4.test

- test/integration/vm-integration-run
Fetch pull-request data before resetting to a specified commit. This
will allow us to run integration tests on pull-request using master
repo, without cloning the original.
> tests/integration: fetch pull-request data

- contrib/kpatch.service
A binary patch may be used to fix network-related issues, so it is better to
apply it before networking services have started.
We encountered a situation in Virtuozzo 7, when the older kernels
conflicted with a new NetworkManager, ip utility and other system
components (https://www.mail-archive.com/devel@openvz.org/msg35123.html).
Binary patches were provided for these kernels to fix the issue but were
loaded after networking services in some cases. As a result, NetworkManager
and some other system components failed to work properly.
Let us make sure the patches are applied earlier during boot.
> kpatch.service: make sure it starts before networking services

- kpatch-build/create-diff-object.c
When a ppcle64 ".toc" section contains only constants, the compiler
might not (won't?) create a corresponding ".rela.toc" section.
In such cases, create-diff-object crashes, assuming ".rela.toc" exists
whenever .toc exists. Simply report that no rela are available when
looking up possible relocations in .toc.
Fixes #1078.
> create-diff-object: Handle ppc64le toc with only constants

- contrib/kpatch.spec
- kpatch/kpatch
Bump version to v0.9.1
Increment version to v0.9.1 and update v0.9.0's changelog section
following many fixes and improvements.
*Note* that the tree has been tagged to v0.9.0 earlier at
(commit: fd8209aa0052).
> Bump version to v0.9.1

- test/integration/rebase-patches
Update the rebase_patches hack^H^H^H tool to make it easier to define
environment variables to drive it, rather than sourcing source
/etc/os-release for everything.  Fix a bunch of shellcheck warnings
along the way.
> testing/integration: update rebase_patches tool

- kpatch-build/create-diff-object.c
We have recently encountered a situation when a patched function
had more than one jump label (static branches with the same static key
used to turn on/off some debugging feature). As it is often the case
with jump labels, their locations were far from obvious in the source
code, hidden in the chains of inline functions.
create-diff-object, however, exits after it has reported one jump label.
This is inconvenient, because, after one updates the patch to avoid
that jump label, the next build of the binary patch reveals another
one and fails again, and so on. It can be very time-consuming.
Let us report all jump labels first.
Before this commit the messages looked like this:
kpatch-build/create-diff-object: ERROR: dev.o:
kpatch_regenerate_special_section: 2084:
Found a jump label at …
> create-diff-object: show all jump labels before reporting failure

- doc/patch-author-guide.md
In shadow-newpid.patch, a new structure member is created using the
klp_shadow_get_or_alloc() routine. The simplified and explained version
of it in the patch author guide has a typo that replaces
klp_shadow_get_or_alloc() with klp_shadow_get().
> patch-author-guide: fix typo in code

- test/integration/rhel-8.1/module.patch
ppc64le build currently fails dues to unused sched_clock variable. Move
it's declaration into ifdef block.
> tests/integration/module.patch: fix ppc64le build

- kmod/core/core.c
User stettberger noticed that the kpatch support module does not
apply the addend for R_X86_64_64 in kpatch_write_relocations().
The AMD64 ABI draft doc [1], Table 4.10: Relocation Types lists that
relocation type as:
Name         Value  Field   Calculation
R_X86_64_64  1      word64  S + A
where:
S : Represents the value of the symbol whose index resides in the
relocation entry.
A : Represents the addend used to compute the value of the relocatable
field.
[1] http://refspecs.linuxfoundation.org/elf/x86_64-abi-0.99.pdf
Fixes: #1093
Reported-by: Christian Dietrich <stettberger@dokucode.de>
> kmod/core: apply dynrela addend for R_X86_64_64

- kpatch/kpatch
- test/integration/kpatch-test
We can be a bit more verbose when reporting a stalled transition. These implement some of the suggestions on the topic.
> integration test: more debug info on stalled transition

- README.md
- test/integration/lib.sh
The `kpatch_depencies()` function does not work out of the box for RHEL-8.
These changes add the missing packages to install allowing to build & run kpatch-build on RHEL-8
> Rhel8 deps

- Makefile
- test/difftree.sh
- test/integration/kpatch-test
- test/integration/lib.sh
- test/integration/vm-integration-run
After realizing that some of the bash/sh code used in the kpatch tree is not checked by `make check`, here's a bunch of fixes or ignores on shellcheck warnings.
> Shellcheck fixes

- kpatch-build/gcc-plugins/gcc-common.h
Building on Fedora 32 with GCC 10.1.1, triggers build failures:
In file included from gcc-plugins/ppc64le-plugin.c:1:
gcc-plugins/gcc-common.h:37:10: fatal error: params.h: No such file or directory
37 | #include "params.h"
|          ^~~~~~~~~~
compilation terminated.
In file included from gcc-plugins/ppc64le-plugin.c:1:
gcc-plugins/gcc-common.h:841:13: error: redefinition of ‘static bool is_a_helper<T>::test(U*) [with U = const gimple; T = const ggoto*]’
841 | inline bool is_a_helper<const ggoto *>::test(const_gimple gs)
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gcc-plugins/gcc-common.h:124,
from gcc-plugins/ppc64le-plugin.c:1:
/usr/lib/gcc/ppc64le-redhat-linux/10/plugin/include/gimple.h:1037:1:
note: ‘static bool is_a_helper<T>::test(U*) [with U = const gimple; T = …
> gcc-plugin: Fix build failure with GCC 10

- kpatch-build/gcc-plugins/ppc64le-plugin.c
While trying to build a module for [cve-2020-8992](https://patchwork.ozlabs.org/project/linux-ext4/patch/20200211011752.29242-1-luoshijie1@huawei.com/), the gcc-plugin would report the error about the local/non-local calls code not found in `build.log` and continue building the livepatching module, which would not load due to expected `nop` instruction, missing after a call to a non-local function.   The `nop` instruction is replaced with `TOC` restore instruction by the kernel during to module load->relocation parsing.  The plugin would run as a gcc-pass, converting the local call to non-local call, resulting in a `nop` instruction inserted after the call, for more details on why this is required refer to the thread at https://lkml.kernel.org/r/1508217523-18885-1-git-send-email-kamalesh@l …
> gcc-plugin: ppc64le - GCC 10 fixes

- kpatch-build/create-diff-object.c
On x86, .altinstr_aux is used to store temporary code which allows static_cpu_has() to work before apply_alternatives() has run.  This code is completely inert for modules, because apply_alternatives() runs during module init, before the module is fully formed.  Any changed references to it (i.e. changed addend) can be ignored.  As long as they're both references to .altinstr_aux, they can be considered equal, even if the addends differ.
> Ignore changes to .altinstr_aux

- kpatch-build/create-diff-object.c
Improve logging of Jump label warnings with a new line between warnings.
> create-diff-object: improve jump label warnings

- kpatch-build/lookup.c
Linux kernel tristate config options allows selected feature, either to
be built-in to the kernel or to be built as a kernel module. When built
as a kernel module, it's expected that the module, will be built with
module information such as author, license, description and others.
For each of the modinfo, a corresponding __UNIQUE_ID_ symbol is
generated.  Their lookup succeeds in the case of module but fails when
selected to built-in to the kernel, the reason being that the kernel
discards these __UNIQUE_ID_ symbols during linking. Add __UNIQUE_ID_
symbols to maybe_discarded_sym list, to avoid failure in case of
table->object is vmlinux.
i.e.:
```# cat .config|grep IOSCHED_BFQ (can be compiled as module too)
CONFIG_IOSCHED_BFQ=y
219: 0000000000000000    54 OBJECT  LOCAL  DEFAULT  267 …
```
> lookup: Add __UNIQUE_ID_ to maybe_discarded_sym list

- test/integration/kpatch-test
RHELs older than 7.7 are missing 5279631271b3 "module: fix ddebug_remove_module()"
which leads to a crash if dynamic debug is used with livepatching.
Disable recent dynamic debug addition on those distros.
> Don't enable dynamic debug during integration tests on older rhels

- kpatch-build/kpatch-build
Before kpatch-build would only keep build.log with --debug option
specified, but it also makes sense to keep it if --skip-cleanup is
specified.
> Keep build.log on --skip-cleanup

- test/integration/kpatch-test
The commands used to build the livepatches and to load or unload them
are currently hard-coded in kpatch-test.
This patch adds 2 options to kpatch-test to make it easier to use custom
kpatch and kpatch-build commands:
*  --system-kpatch-tools - if set, 'sudo kpatch' will be used to
load/unload the patches; 'kpatch-build' - to build them.
To use custom tools here, the user can adjust $PATH.
If the option is not set, kpatch-test will assume it is in KPatch source
tree, same as before this commit, and will use the tools from there.
* --kpatch-build-opts="..." - additional options to pass to
kpatch-build.
Example:
```
./kpatch-test \
--system-kpatch-tools \
--kpatch-build-opts="-s ./linux-src -c ./config -v ./vmlinux" \
-d my_kpatch_tests/test/integration/v01
```
In this case, kpatch and …
> kpatch-test: make it easier to use custom kpatch and kpatch-build commands

- kpatch-build/Makefile
Fail the kpatch build, while attempted to build on unsupported
architecture. The build will eventually fail but with the error that
doesn't hint the user clearly about the support status of kpatch, on the
architecture.  This patch forces the build error with the message about
the unsupported status, avoiding confusion to the user.
> kpatch-build/Makefile: Fail build on unsupported architectures

- kpatch-build/kpatch-build
The modpost step complains about one of our generated files, output.o
and that it can't find a corresponding .cmd file for it (full path names
stripped):
WARNING: could not find .output.o.cmd for output.o
This was turned into an error in v5.8:
.output.o.cmd: No such file or directory
Avoid this by creating an empty .cmd file so that modpost acknowledges
that the file exists, but doesn't parse anything out of it.
Fixes #1125
Reported-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com> (for v5.8+)
> kpatch-build: avoid modpost .output.o.cmd complaints

- doc/patch-author-guide.md
Issue #1124 ("Jump label issues are triggered from an unrelated
function") was caused by a minor __LINE__ change in a pr_warn statement.
Reference it here in the author guide for future reference.
> patch-author-guide: mention issue #1124 __LINE__ shift

- doc/patch-author-guide.md
- kpatch-build/kpatch-build
- test/integration/rhel-7.6/symvers-disagreement-FAIL.patch
- test/integration/rhel-7.7/symvers-disagreement-FAIL.patch
- test/integration/rhel-7.8/symvers-disagreement-FAIL.patch
- test/integration/rhel-8.0/symvers-disagreement-FAIL.patch
- test/integration/rhel-8.1/symvers-disagreement-FAIL.patch
- test/integration/rhel-8.2/symvers-disagreement-FAIL.patch
These patches aim to warn when the result of a kpatch-build has a different version for an exported symbol and might cause a symbol version disagreement upon loading.
The solution isn't very sophisticated and just compares all versions of symbols in the old an new file symvers file. On the machine I tested (x86_64 with 8 processors), the time added by this is not very significant compared to the kernel builds done by kpatch-builds (both upstream and this branch were tested after an initial kpatch-build to get ccache filled).
I'm open to better suggestions.
> Fix symvers

- .travis.yml
- kpatch-build/create-diff-object.c
User disaster123 reports the following build errors:
create-diff-object.c: In function 'kpatch_process_special_sections':
create-diff-object.c:2215:41: error: 'key' may be used uninitialized in this function [-Werror=maybe-uninitialized]
code->sym->name, code->addend, key->sym->name);
^~
create-diff-object.c:2138:22: note: 'key' was declared here
struct rela *code, *key, *rela;
^~~
In file included from kpatch-elf.h:26,
from create-diff-object.c:53:
log.h:20:3: error: 'code' may be used uninitialized in this function [-Werror=maybe-uninitialized]
printf(format, ##__VA_ARGS__); \
^~~~~~
create-diff-object.c:2138:15: note: 'code' was declared here
struct rela *code, *key, *rela;
^~~~
cc1: all warnings being treated as errors
These are reproducible when building with 9.3.1 and 8.3.1 when …
> create-diff-object: cleanup maybe-uninitialized compiler complaints

- contrib/kpatch.spec
- kpatch/kpatch
Interesting changes since v0.9.1:
- Integration test support for rhel-7.8, rhel-7.9, rhel-8.1, centos-8
- Better support for gcc child functions
- Batch jump label errors to report all instances
- Dynrela code cleanup
- Remove .klp.arch and add support for jump labels in v5.8+ kernels
- Mark ignored sections earlier to support functions missing ftrace hook
- Minor README.md improvements
- Add ppc64le mcount support to patched functions
- Show additional stalled process information in kpatch script
- Increased shellcheck coverage and fixes
- ppc64le plugin fixes for gcc v10
- Ignore __UNIQUE_ID_ symbol from tristate config objects
- Don't clear dmesg during integration tests
- Detect and report MODVERSIONS symbol version CRC changes
> Bump to v0.9.2

- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
- kpatch-build/create-kpatch-module.c
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
Currently all the callers of kpatch_write_output_elf() are creating
.o object files or .ko kernel modules.  Neither of these filetypes are
executable on their own, so enhance kpatch_write_output_elf() to accept
file creation flags and update its callers to pass 0664 to match
the expected permissions.
> kpatch-elf: pass new ELF output file mode to kpatch_write_output_elf()

- kpatch-build/create-diff-object.c
These two patches fixes kpatch for a custom 5.9 kernel build.
> Linux 5.9 fixes

- kmod/patch/kpatch-macros.h
Convert __section to __kpatch_section to fix compile errors since
Linux 5.10, commit 33def8498fdd ("treewide: Convert macro and uses of
__section(foo) to __section("foo")").
Signed-off-by: WANG Chao <chao.wang@ucloud.cn>
> kmod: convert __section to __kpatch_section

- kpatch/kpatch
There exists a very small timing window in which "kpatch unload" gets to
its "rmmod" step before the kpatch-patch module's reference count has
cleared and the "rmmod" fails.
This is only a transient problem, but we can adopt code from upstream
livepatch kselftests which wait for the module refcounts to settle
before moving onto "rmmod".
A small wrinkle is that this is not supported by the older kpatch.ko
core.  The price for circumventing the activeness safety check via
KPATCH_FORCE_UNSAFE is that it must leave the kpatch patch modules in
place (see e1890e627a9b ("prevent rmmod of forced modules")).
> kpatch: wait for module ref counts on unload

- kmod/patch/Makefile
Starting with v5.10 kbuild no longer builds built-in targets for
external modules (including extra-y). Further it wasn't guaranteed that
extra-y targets were going to be built before linking.
Do a proper thing and add kpatch.lds as a dependency for $(KPATCH_NAME).o.
Fixes: #1148
> kmod/patch: add kpatch.lds as a dependency for $(KPATCH_NAME).o

- kpatch/kpatch
- man/kpatch.1
From Linux-5.1 onward, the sysfs interface to send signals to
processes stalling livepatch transitions is replace by a peridical
signal sent by the kernel.
On such systems, the kpatch signal subcommand does nothing. Just
let the user know they don't need to worry about it.
Fixes: #1151 
> kpatch: Inform user when signal subcommand is unnecessary

- kpatch-build/kpatch-gcc
Starting v5.11-rc, kpatch-build fails on powerpc with the error:
ERROR: invalid ancestor arch/powerpc/kernel/vdso64/vdso64.so.dbg for arch/powerpc/kernel/vdso64/vgettimeofday.o
the upstream commit ab037dd87a2f(powerpc/vdso: Switch VDSO to generic
implementation) introduced this breakage, lets skip vdso files. They are
not compatible with kpatch.
> kpatch-gcc: powerpc - skip vdso files

- kpatch-build/kpatch-build
kpatch-build requires gcc flags -f[function|data]-sections when building
original and patched targets.  These flags result in an ELF binary with
many sections, potentially requiring special extended ELF header
processing to parse correctly.
CONFIG_DEBUG_INFO_BTF invokes pahole as part of the kernel build and
unfortunately pahole cannot iterate through more than 65535 section
headers.  As result, the pahole program segfaults and fails the build
like so:
...
BTF     .btf.vmlinux.bin.o
scripts/link-vmlinux.sh: line 127: 718345 Segmentation fault      (core dumped) LLVM_OBJCOPY=${OBJCOPY} ${PAHOLE} -J ${1}
objcopy: --change-section-vma .BTF=0x0000000000000000 never used
objcopy: --change-section-lma .BTF=0x0000000000000000 never used
objcopy: error: the input file '.btf.vmlinux.bin' is empty …
> kpatch-build: workaround pahole and CONFIG_DEBUG_INFO_BTF

- Makefile
- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
- kpatch-build/kpatch-cc
- kpatch-build/lookup.c
- man/kpatch-build.1
- test/integration/lib.sh
- test/integration/linux-5.10.11/data-new-LOADED.test
- test/integration/linux-5.10.11/data-new.patch
- test/integration/linux-5.10.11/gcc-static-local-var-6.patch
- test/integration/linux-5.10.11/macro-callbacks.patch
- test/integration/linux-5.10.11/module-call-external.patch
- test/integration/linux-5.10.11/multiple.test
- test/integration/linux-5.10.11/new-function.patch
- test/integration/linux-5.10.11/new-globals.patch
- test/integration/linux-5.10.11/warn-detect-FAIL.patch
Support for building kpatches for kernels built with clang.
> clang support

- kpatch/kpatch
On module installation kpatch utility creates a directory with kernel version as a name in /var/lib/kpatch which is never removed. To address this check if any files are left in this directory after each 'uninstall' call and if not - remove it.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1930108
> kpatch: cleanup install directory

- kpatch-build/kpatch-build
With CONFIG_DEBUG_INFO_BTF_MODULES, the kernel build process adds BTF to
each in-tree modules. However, this process is broken with kpatch, with
error message like:
Failed to parse base BTF 'vmlinux': -4001
Unblock build with CONFIG_DEBUG_INFO_BTF_MODULES with similar workaround
as the one for CONFIG_DEBUG_INFO_BTF.
Signed-off-by: Song Liu <songliubraving@fb.com>
> kpatch-build: workaround pahole and CONFIG_DEBUG_INFO_BTF_MODULES

- kpatch-build/kpatch-build
It turns out there is a stretch of time in kernel's history when CONFIG_DEBUG_INFO_BTF was already added, but Makefile.modfinal wasn't split off yet. To address those we need to either check the file's existance or, as @liu-song-6 suggested initially, check config for CONFIG_DEBUG_INFO_BTF_MODULES=y.
> kpatch-build: check existance of Makefile.modfinal

- kpatch-build/create-diff-object.c
create-build-diff expects .cold functions to be suffixed by an id, which is not always the case. Drop the trailing '.' when searching for cold functions.
Fixes: #1160
> support for .cold functions with no id suffix

- .github/workflows/unit.yml
Add unit tests through github actions. This is exactly the same as our travis tests but using github actions instead.
I noticed that latest pull requests didn't have a notice from travis also when logging into travis-ci.org there is the following message:
```
Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information. 
```
travis-ci.com used to be their commercial offering, so there are some changes going on and I am not exactly sure what those mean for us. This commits enable github "actions" which are the same thing but first party. We can run both in parallel and retire travis at some point since it is third-party and is more likely to have issues.
> github actions: unit tests

- kpatch-build/kpatch-build
RHEL-8.4 backported the "livepatch,module: Remove .klp.arch and
module_disable_ro()" patchset [1], so update kpatch-build accordingly.
[1] https://lore.kernel.org/live-patching/nycvar.YFH.7.76.2005080016330.25812@cbobk.fhfr.pm/T/#t
> kpatch-build: drop klp.arch support in RHEL-8.4

- contrib/kpatch.spec
- kpatch/kpatch
Interesting changes since v0.9.2:
- Initial support for clang compiler
- Add support for rhel-8.4
- rhel-8.4: workaround pahole and extended ELF sections
- rhel-8.4: drop klp.arch support
- Kpatch command waits for module to fully unload
- Kpatch command informs user when signal subcommand is unnecessary
- kpatch-build skips ppc64le vdso files
Signed-off-by: Yannick Cote <ycote@redhat.com>
> Bump to v0.9.3

- README.md
Move the #kpatch channel to libera.chat due to the freenode implosion.
> README.md: Migrate #kpatch IRC channel to libera.chat

- kpatch/kpatch
Fixes: 1188
Signed-off-by: Joel Savitz <jsavitz@redhat.com>
> kpatch: Sync signal subcmd usage output with manpage

- kpatch/kpatch
Fixes #1187
Signed-off-by: xiejingfeng <xiejingfeng@linux.alibaba.com>
> kpatch: use /sys/kernel/kpatch/ to check whether core module is loaded

- doc/patch-author-guide.md
- kmod/patch/livepatch-patch-hook.c
- kpatch-build/kpatch-build
- man/kpatch-build.1
- test/integration/kpatch-test
Since 5.1 kernel, klp_patch supports a "replace" option, which does atomic
replace of cumulative patches. Enable building such patch with an option.
Signed-off-by: Song Liu <song@kernel.org>
> kpatch-build: enable option -R|--replace to build replace klp

- kpatch/kpatch
With klp->replace, when a patch is replaced, it is no longer an active
patch, but the module is still loaded with a refcount of 0. If the user
tries to load the patch again, insmod will fail with EEXIT. To avoid
such errors, run a proactive rmmod before loading the module. This is a
no-op if the module is not loaded or is actually in use.
Signed-off-by: Song Liu <song@kernel.org>
> kpatch: rmmod module of the same name before loading a module

- kpatch-build/create-diff-object.c
A STT_SECTION symbol is not needed if if it is not used as a relocation
target. Therefore, a section, in this case a debug section, may not have
a secsym associated with it.
Signed-off-by: Bill Wendling <morbo@google.com>
> create-diff-object: Check that the section has a secsym

- kpatch-build/kpatch-build
```
There are some Red Hat kernel NVR combinations like
"kernel-5.13.0-0.rc4.33.el9.x86_64" that don't work well with our srpm
localversion strategy and end up botching the utsrelease.h file... which
allows for kpatch builds, but the module loader rightly rejects the
vermagic mismatch.
An ordinary rpmbuild sets up the kernel Makefile with:
ShortRel=$(perl -e "print \"%{release}\" =~ s/\.pr\.[0-9A-Fa-f]{32}//r")
perl -p -i -e "s/^EXTRAVERSION.*/EXTRAVERSION = -${ShortRel}.%{_target_cpu}${Variant:++${Variant}}/" Makefile
The simplest fix is just adding the version string to the kernel
Makefile EXTRAVERSION as rpmbuild would do (minus the perl voodoo).
Fixes: #1196
```
> kpatch-build: set EXTRAVERSION and not localversion for RH kernels

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
As described in #1206.  See the commit messages for more info.  Will post unit tests momentarily.
> Support CONFIG_PRINTK_INDEX

- kmod/patch/Makefile
- kpatch-build/kpatch-build
- test/integration/Makefile
These two commits fix and extend the ability to build non atomic replace kpatches:
1. Fixes the --no-replace kpatch-build flag so that the kpatch module build honors the setting.
2. Requested by Red Hat QE, who reuse the integration test .ko modules for their own tests -- they were not prepared for atomic-replace style patches when loading multiple kpatches.  Provide a general facility to set the integration test kpatch-build options through the makefile.
> Makefile tweaks for handling non-replace kpatch building

- kpatch-build/kpatch-build
After commit 17dcebf077d69 ("kpatch-build: enable klp with replace option by default"),
building the old-style (kpatch.ko-based) patches fails with the following
error:
> "kpatch core module (kpatch.ko) does not support replace, please add -R|--non-replace"
kpatch.ko actually supports atomic replacement of patches but KLP_REPLACE
has nothing to do with that. Let us not break such builds and remove that check.
> kpatch-build: Do not check KLP_REPLACE for kpatch.ko-based patches

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.h
Building data-read-mostly.patch on rhel-9.0-beta for ppc64le leads to a
segmentation fault:
Program received signal SIGSEGV, Segmentation fault.
kpatch_check_relocations (kelf=0x10040490) at create-diff-object.c:2571
2571                                    sdata = rela->sym->sec->data;
(gdb) bt
(gdb) p rela->sym->sec->data
Cannot access memory at address 0x160000007e
Valgrind narrows the problem down to invalid reads through rela->sym in
kpatch-check-relocations().
The culprits are kpatch_create_intermediate_sections(), which marks
symbols referenced by rela sections that are now dynrelas to be
stripped, and kpatch_strip_unneeded_syms(), which removes and frees
them.
The problem with the symbol stripping is that multiple relas may
reference the same ELF symbol.  If any remaining …
> create-diff-object: fix use after free in kpatch-check-relocations()

- kpatch-build/kpatch-build
create-klp-module could error out and in this case ensure that
kpatch-build does not proceed further.
Fixes #1223
> kpatch-build: Handle error in create-klp-module

- kmod/patch/Makefile
- kmod/patch/livepatch-patch-hook.c
- kpatch-build/kpatch-build
These commits resulted from a debugging session with `livepatch-patch-hook.c`.  In that case, the `output.o` file was consistent, but I was testing changes to the livepatch API hook code.
This does neuter the `clean` target a bit, however the Makefile is already incapable of recreating `output.o` on its own anyway, so I figured the gain in debug-ability was worth it.  AFAIK `export -p` is POSIX, so hopefully not just a bash-ism.
> Hook hacking helpers

- test/integration/linux-5.10.11/module-call-external.patch
- test/integration/linux-5.10.11/new-function.patch
module-call-external.patch and new-function.patch fail to build on
ppc64le with "Found an unsupported sibling call". Add
fno-optimize-sibling-calls attributes to functions in question
> test/integration/linux-5.10.11: fix patches to build on ppc64le

- README.md
- kpatch-build/kpatch-build
- man/kpatch-build.1
This has two commits: one dealing with building OOT modules with non-distro kernels, this also includes some refactoring disambiguating `SRCDIR` since we now have 2 SRCDIRS - one for kernel and another one for oot-module. This superceeds #1234.
Second commit tries to deal with #1238.
> OOT-related updates

- kpatch-build/create-diff-object.c
Upstream v5.14+ kernel change a358f40600b3 ("once: implement
DO_ONCE_LITE for non-fast-path "do once" functionality") consolidated a
bunch of do-once macros into a common macro:
#define DO_ONCE_LITE_IF(condition, func, ...)				\
({								\
static bool __section(".data.once") __already_done;	\
...
which replaced static local variable __warned with __already_done.
Update any __warned static local checks to also look for the new
__already_done variable as well.
> create-diff-object: update for __already_done

- kpatch-build/kpatch-build
Previous commits added support for CONFIG_PRINTK_INDEX, but do not
actually read the option from the kernel configuration.  Implement that
now so the feature support will be active.
Fixes: 56471ffc7c0c ("kpatch-build: Support CONFIG_PRINTK_INDEX, part 2")
Fixes: 6cf50a6fca84 ("create-diff-object: Support CONFIG_PRINTK_INDEX, part 1")
> kpatch-build: refactor kernel config and special section parsing

- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
In kpatch_create_mcount_sections(), there is a section of code wherein
on x86-64 builds, if the rela type for a symbol is R_X86_64_NONE, a
buffer into which a writeable copy of the symbol's .text is allocated.
This is done so that the .text section may be copied into the buffer,
and the NOP call that is generated for the function entry (by older
versions of the kernel/gcc) can be updated to be a call to fentry.
In all other calls in kpatch-build, any allocation is checked for
failures, and gracefully failed with a call to ERROR(). This diff
corrects the one aforementioned spot where this was missed.
Signed-off-by: David Vernet <void@manifault.com>
> kpatch-build: Add missing malloc failure check

- kpatch-build/create-diff-object.c
Linux 5.16's objtool gathers retpoline thunk call sites in its own special section on x86_64 with `CONFIG_RETPOLINE=y`. This PR allows building live patches for this config.
I tested the change with kernels 5.15 and 5.16, each of them with a patch touching no code with indirect calls (and thus without the new `.retpoline_sites` section) and with a patch touching code with indirect calls (and thus with the new `.retpoline_sites` section). Without the change in this PR, building a live patch touching code with indirect calls for kernel 5.16 results in the following error:
```
ERROR: stacktrace.o: 1 unsupported section change(s)
stacktrace.o: changed function: arch_stack_walk_reliable
stacktrace.o: changed section .rela.retpoline_sites not selected for inclusion …
```
> create-diff-object: add support for .retpoline_sites section

- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
- test/unit/Makefile
This is a remix of @gwelymernans 's #1179 with a few slight tweaks:
1) Do not add an `--arch` command line argument to various tools and kpatch-build.  Detect the ELF architecture of the input files and pivot based on that.  This would allow for a (theoretical at this point) cross-arch-build to build a ppc64le reference/patched kernel and when processing its object files, rely on the ELF header to indicate the target architecture.
2) Modifications limited to create-diff-object for now.  Without testing full cross-arch-build support, this is still useful to the project as we can test the ppc64le unit tests (with a very small patch: [unit-objs-cross.diff.txt](https://github.com/dynup/kpatch/files/7916207/unit-objs-cross.diff.txt)):
``` bash
$ arch
x86_64
$ make -s unit OBJDIR=objs/ppc64le …
```
> Remove host / target architecture assumption from create-diff-object

- kpatch-build/lookup.c
Second loop in locals_match() checks table_sym->type instead of
sym->type.
Fixes: 7207687 Switch to per-file lookup table pointers.
> Fix sym->type condition in locals_match()

- kpatch-build/Makefile
- kpatch-build/kpatch-build
This PR fixes some issues discussed in #811 and #1224.
I decided to submit small changes sequentially and hold off on the --distro option.
This patch introduces ability to pick a CROSS_COMPILE
environment variable which can be used for
specifying cross-complier prefix.
It allows to build live patches not only on
target system, but also on hosts for a target other
than the one on which the compiler is running.
> kpatch-build: add cross-compilation support (#1224 fix)

- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
Symbol indexes over 64k don't fit into st_shndx and are stored in
extended symbol table. Make sure we properly handle these cases. It is
not normally useful during kpatch builds but will come up if we start
diffing linked objects.
> symtab_shndx support

- kpatch-build/kpatch-build
Previously, the name length was limited to 48 chars. This was then
prepended with "kpatch-" and a trailing NUL terminator to get to the 56
char limit for kernel module names. After some code rearrangement, the
48 char restriction was applied to the name after being prefixed with
kpatch-/livepatch-, limiting the length more than necessary. Increase
the name length limit back to 55 chars to restore the original limit.
Fixes: c0105ea46774 ("kpatch-build: set default module prefix accordingly")
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> kpatch-build: Increase name length limit to 55 chars

- kpatch-build/create-diff-object.c
Fixes for #1257.
I still need to make the unit test objects.  It would be really nice if we had some kind of automation which takes a patch and a kernel version and spits out the test objects for all the supported arches.
> Fix seg fault caused by missing .LCx symbol

- contrib/kpatch.spec
- kpatch/kpatch
v0.9.6:
- Allow OOT modules to be built with non-distro kernels
- Add cross-arch unit testing support
- Support ELF extended symbol section indexes
- Allow setting kernel version if --sourcedir and --vmlinux are used
- Cleanup and enhance __LINE__ macro detection for all arches
- Fix segfault on .LCx string literal symbols
- Include __dyndbg section when referenced by jump table
- Honor user provided KBUILD_EXTRA_SYMBOLS
- Support .retpoline_sites section
- Add native compiler selection via CROSS_COMPILE
> Bump to version v0.9.6

- doc/INSTALL.md
This seems to fix the doc linking problem.
Fixes #1267
> doc: fix internal link to supported arches

- doc/INSTALL.md
- kpatch-build/kpatch-build
- test/integration/lib.sh
As I noticed, commit eaaced191 has added
partial support for openEuler.
This patch enables usage in openEuler like:
kaptch-build xxxx.patch
I test it in openEuler 21.09, for people who
want to use kpatch in openEuler, two more steps
are needed.
1) add repo source
source rpm package of openEuler kernel are put in
two places. One is
https://repo.openeuler.org/openEuler-21.09/source/
Another one is
https://repo.openeuler.org/openEuler-21.09/update/source/
The latter one is not included in rpm repo lists by default.
2) compile kernel with CONFIG_LIVEPATCH_PER_TASK_CONSISTENCY enabled
openEuler has its own strategy when trying to apply patches.
We can only use klp_enable_patch function when
CONFIG_LIVEPATCH_PER_TASK_CONSISTENCY enabled.
Signed-off-by: anatasluo <luolongjuna@gmail.com>
> kpatch-build: add support for openEuler

- kpatch/kpatch
Currently "kpatch force unload <klp_some_version>" will fail to unload
an old kernel live patch module that is no longer seeing any use, when
the "enabled" file for that module is no longer present.
Check for the presence of such modules by checking /sys/module, and
return success from disable_patch() for a module that is already
disabled.
This allows "kpatch force unload <klp_some_version>" to succeed for
already disabled modules.
Signed-off-by: Rik van Riel <riel@surriel.com>
> kpatch: also unload a loaded, but no longer enabled kernel live patch

- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
- kpatch-build/kpatch-build
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
Several improvements for issues discovered in the review for #1203  .Mostly related to addend handling, but also some other cleanups and an endianness fix.
> Fix addend handling and other cleanups for s390

- Makefile
- doc/INSTALL.md
- test/integration/lib.sh
`yum-builddep kernel` has been bugging me for a _long_ time.  Sometimes it installs all kernel build dependencies, other times it leaves out obvious packages like bison, flex, bc, etc.  The RHEL kernel.spec file is not the most straightforward specfile and I think effort has gone into paring down a minimal dependency set (think about skipping debug builds, kABI, all the other things that the specfile can do).  Whether specfile complexity is the root cause or not, the result is that I have to often install additional packages after running test/integration/lib.sh's **kpatch_dependencies()** function.
This patchset modifies **kpatch_dependencies()**'s `yum-builddep` invocation to add `--skip-unavailable`, which in my limited tests, seems to render a more complete dependency install.  My …
> kpatch build dependency cleanup

- test/integration/linux-5.18.0/data-new-LOADED.test
- test/integration/linux-5.18.0/data-new.patch
- test/integration/linux-5.18.0/gcc-static-local-var-6.patch
- test/integration/linux-5.18.0/macro-callbacks.patch
- test/integration/linux-5.18.0/module-LOADED.test
- test/integration/linux-5.18.0/module.patch
- test/integration/linux-5.18.0/multiple.test
- test/integration/linux-5.18.0/new-function.patch
- test/integration/linux-5.18.0/new-globals.patch
- test/integration/linux-5.18.0/shadow-newpid-LOADED.test
- test/integration/linux-5.18.0/shadow-newpid.patch
- test/integration/linux-5.18.0/special-static.patch
- test/integration/linux-5.18.0/symvers-disagreement-FAIL.patch
- test/integration/linux-5.18.0/syscall-LOADED.test
- test/integration/linux-5.18.0/syscall.patch
- test/integration/linux-5.18.0/warn-detect-FAIL.patch
- test/integration/rhel-9.0/module.patch
- test/integration/rhel-9.0/syscall-LOADED.test
Update the integration tests:
1. Add patches for upstream kernel 5.18.0
2. Fix a warning generated by newer module.patch
3. Add missing syscall test for rhel-9.0 directory
> Integration updates

- README.md
- doc/s390-upstream-prerequisites.md
- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
- kpatch-build/kpatch-cc
- kpatch-build/kpatch-elf.c
- kpatch-build/lookup.c
Hi All,
Add s390x support for kpatch
Prerequisite gcc patches:
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=a1c1b7a888ade6f21bc7c7f05a2cbff290273fcc
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=0990d93dd8a4268bff5bbe48aa26748cf63201c7
https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=935b5226c385e34088c314374cbbe9e4995b9e44
Prerequisite kernel patches:
https://lore.kernel.org/live-patching/YObPhPkzRSqnzgK3@alley/T/#me6c2fcdbd4f582d5cc5c594bafb083ba814acdf9 - Yet to be upstream.
https://git.kernel.org/pub/scm/linux/kernel/git/s390/linux.git/commit/?h=for-next&id=7561c14d8a4d1a24a40b1839d927d488e2d6345a
Recommended Patches:
torvalds/linux@de5012b
torvalds/linux@67ccddf
Tested on kernel 5.14:
KPATCHBUILD_OPTS="-v /home/extend/vmlinux -s /home/extend/linux-devel/linux/  -d" ./kpatch-test  -d …
> S390x kpatch support

- kmod/patch/kpatch-syscall.h
Kernel version specific __KPATCH_SYSCALL_DEFINEx macros were added to
kpatch-syscall.h for x86, but only single versions for other arches.
This works out for s390x, but not ppc64le for which kpatch-build support
goes back to kernel versions that require slightly different macros.
Reorder the __KPATCH_SYSCALL_DEFINEx macros to define the arch-specific
ones first (arch/.../include/asm/syscall_wrapper.h) and then fall back
to using generic ones (include/linux/syscalls.h versions).
Fixes: #1278
Fixes: 9c0b678621b9 ("macros: add syscall patching macros")
> macros: tweak syscall patching macros

- kpatch-build/create-diff-object.c
Fixes https://github.com/dynup/kpatch/issues/1280
Simple test with this change applied:
```
[vagrant@fedora36 linux-5.18.11-200.local.fc36.x86_64]$ cat meminfo-string.diff 
diff --git a/fs/proc/meminfo.c b/fs/proc/meminfo.c
index 6fa761c9..c1a3ab6c 100644
--- a/fs/proc/meminfo.c
+++ b/fs/proc/meminfo.c
@@ -55,6 +55,7 @@ static int meminfo_proc_show(struct seq_file *m, void *v)
sreclaimable = global_node_page_state_pages(NR_SLAB_RECLAIMABLE_B);
sunreclaim = global_node_page_state_pages(NR_SLAB_UNRECLAIMABLE_B);
+       seq_printf(m, "I can haz kpatch?\n");
show_val_kb(m, "MemTotal:       ", i.totalram);
show_val_kb(m, "MemFree:        ", i.freeram);
show_val_kb(m, "MemAvailable:   ", available);
[vagrant@fedora36 linux-5.18.11-200.local.fc36.x86_64]$ kpatch-build -s . meminfo-string.diff …
```
> create-diff-object: add support for .return_sites section (x86)

- kpatch-build/kpatch-cc
To support building out-of-tree kernel modules, the source tree prefix
is attempted to be stripped from change object file paths to make them
relative. However, if the path is already relative, the change can
strip a substring instead, resulting in build errors.
Ensure just the prefix is stripped instead of any substring.
Fixes: #1282
Fixes: 51a8fad34ff3 ("Add support for building out-of-tree modules")
> kpatch-cc: fix stripping of source tree prefix

- kpatch-build/kpatch-build
For consistency with what the kernel does (and what we already do for
in-tree modules), if the file has any dashes ('-'), replace them with
underscores in the objname (aka KBUILD_MODNAME).
Fixes #1286.
> kpatch-build: fix KBUILD_MODNAME for OOT modules

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
- kpatch-build/log.h
- kpatch-build/lookup.c
Musl libc doesn't support error.h
Moving to err.h would allow using it on Musl system
> kpatch-build: use err.h instead of error.h for musl support

- kpatch-build/create-diff-object.c
Hi, guys. I meet a segment fault when I use the Kpatch.
My patch is
```
From d4238410bab5b907ee514c15ab4d9109d6da2796 Mon Sep 17 00:00:00 2001
From: Luo Longjun <luolongjuna@gmail.com>
Date: Wed, 14 Sep 2022 16:38:28 +0800
Subject: [PATCH] kpatch test
---
fs/proc/version.c | 6 +-----
1 file changed, 1 insertion(+), 5 deletions(-)
diff --git a/fs/proc/version.c b/fs/proc/version.c
index b449f186577f..734ddfc7d316 100644
--- a/fs/proc/version.c
+++ b/fs/proc/version.c
@@ -6,12 +6,8 @@
#include <linux/seq_file.h>
#include <linux/utsname.h>
-static int version_proc_show(struct seq_file *m, void *v)
+notrace noinline static int version_proc_show(struct seq_file *m, void *v)
{
-	seq_printf(m, linux_proc_banner,
-		utsname()->sysname,
-		utsname()->release,
-		utsname()->version);
return 0;
}
-- …
```
> kpatch-build: rela section could disappear after patched

- test/unit/Makefile.include
Update the unit test submodule reference to include ppc64le files w/o .eh_frame.  At the same time, give additional guidance on stripping these sections going forward.
> test/unit: update for .eh_frame removal

- kpatch-build/create-diff-object.c
Based on this [kpatch-build: rela section could disappear after patched](https://github.com/dynup/kpatch/pull/1301).
I found another problem, considering the following example in X86.
original code:
```
__noreturn noinline int kpatch_func(void)
{
while(1) { };
}
EXPORT_SYMBOL(kpatch_func);
```
patched code:
```
__noreturn notrace noinline int kpatch_func(void)
{
asm(".byte 0xe8, 0x00, 0x00, 0x00, 0x00");
while(1) { };
}
EXPORT_SYMBOL(kpatch_func);
```
These two functions are different, but the output of Kpatch is
`
ERROR: no functional changes found.
`
The problem is explained in the log:
------------------------------
If two sections want to be the same, they need to satisfy
two conditions:
1) the result of memcpy is zero, which means they have the same content.
2) they have the same …
> kpatch-build: strengthen conditions for changed sections

- contrib/kpatch.spec
- kpatch/kpatch
v0.9.7:
- S390x kpatch support
- Add support for openEuler + documentation (kpatch-build)
- Use err.h instead of error.h for musl support (kpatch-build)
- Add support for .return_sites section (kpatch-build x86)
- Create missing section symbol (kpatch-build)
- Fix symtab parsing lookup (kpatch-build)
- Many fixes and improvements in create-diff-object (kpatch-build)
- Unload already disabled modules (kpatch util)
- Add integration tests for: rhel-{8.6,9.0},5.18.0 (test)
- Add tests for patching a syscall (test)
- Combine and improve Fedora, CentOS with RHEL kpatch-build dependencies (test)
- Major revamp of README.md and documentation
- Add syscall patching macros (kmod)
> Bump to version v0.9.7

- kpatch-build/gcc-plugins/ppc64le-plugin.c
Fix build error seen on gcc (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1):
g++ -MMD -MP -I../kmod/patch -Iinsn -Wall -Wsign-compare -Wno-sign-conversion -g -Werror -shared -I/usr/lib/gcc/ppc64le-redhat-linux/12/plugin/include -Igcc-plugins -fPIC -fno-rtti -O2 -Wall gcc-plugins/ppc64le-plugin.c -o gcc-plugins/ppc64le-plugin.so
In file included from /usr/include/features.h:490,
from /usr/include/bits/libc-header-start.h:33,
from /usr/include/stdio.h:27,
from /usr/lib/gcc/ppc64le-redhat-linux/12/plugin/include/system.h:46,
from /usr/lib/gcc/ppc64le-redhat-linux/12/plugin/include/gcc-plugin.h:28,
from gcc-plugins/gcc-common.h:6,
from gcc-plugins/ppc64le-plugin.c:1:
/usr/include/bits/error-ldbl.h:23:1: error: type of ‘error’ is unknown
23 | __LDBL_REDIR_DECL (error)
| ^~~~~~~~~~~~~~~~~ …
> gcc-plugin: update headers for gcc-12

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
These are spun out of @swine's patchset #1302 in the interest of upstreaming sooner than the arm64 changes.  This set pulls out the non-arm64 specific llvm fixes.  I made minor changes along the way to align a little closer to the project commit/code conventions.  Internal x86 clang integration tests passed.
> Collection of small llvm fixes

- kpatch-build/kpatch-build
- kpatch-build/kpatch-cc
Rewrite kobj_find() to deal with Linux 5.19, where the .cmd files use
object file paths relative to the .cmd file rather than relative to the
root of the kernel tree.
Fixes #1277.
> kpatch-build: support Linux 5.19 .cmd file format

- examples/proc-version.patch
Create a simple kpatch test that should apply across a wide range of kernels.  The version_proc_show() is a good candidate as it's easy to verify and hasn't been touched upstream since 2008.
> examples: add /proc/version kpatch sample

- kpatch-build/kpatch-build
- kpatch-build/kpatch-cc
For some reason the github version of 'make check' just started complaining about these:
```
shellcheck kpatch/kpatch kpatch-build/kpatch-build kpatch-build/kpatch-cc
In kpatch-build/kpatch-build line 455:
while [[ "${filedir#$common/}" = "$filedir" ]]; do
^-----^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.
Did you mean:
while [[ "${filedir#"$common"/}" = "$filedir" ]]; do
In kpatch-build/kpatch-build line 460:
result="${result}${filedir#$common/}"
^-----^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.
Did you mean:
result="${result}${filedir#"$common"/}"
In kpatch-build/kpatch-cc line 26:
relobj=${obj##$KPATCH_GCC_SRCDIR/}
^----------------^ SC2295 (info): Expansions inside …
```
> kpatch-build: fix "make check"

- .github/workflows/unit.yml
Attempt to fix the following warning:
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
> github actions: fix warning with node 16

- doc/patch-author-guide.md
- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
- kpatch-build/kpatch-elf.h
Now that we have KPATCH_STATIC_CALL(), document its usage.  While at it, give a more thorough description for why jump labels and static calls aren't supported in some scenarios.
> patch-author-guide: update jump label / static call descriptions

- examples/cmdline-string.patch
This is a test example currently preferable to [proc-version.patch](https://github.com/dynup/kpatch/blob/master/examples/proc-version.patch) as crash utility has difficulty parsing /proc/version content after being altered.
Signed-off-by: Linqing Lu <lilu@redhat.com>
> examples: add cmdline-string.patch as a compatible example

- kpatch-build/create-diff-object.c
Like unsupported jump labels and static call sites, batch report all unsupported sibling calls so the kpatch developer doesn't need to iteratively find them all.
> create-diff-object: batch report unsupported sibling calls

- contrib/kpatch.spec
- kpatch/kpatch
v0.9.8:
- Clang fix ups from Pete Swain
- Support for gcc-12
- Support for Linux 5.19
- Added RHEL-8.7 and 9.1 integration tests
- Fixed __UNIQUE_ID() variable correlation
- Improved handling of unsupported static calls
> Bump to version v0.9.8

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
- kpatch-build/lookup.c
ubsan generates .data..Lubsan_data* sections as follows:
```
1. int main(int argc, char **argv) {
int arr[100]; 
arr[101] = 1; 
printf("arr[101] = %d", arr[101]); 
return 0; 
}
```
reloc:
```
2. 1a:   50 10 b0 ac          st      %r1,172(%r11)
int arr[100];
arr[101] = 1;
1e:   a7 39 00 65             lghi    %r3,101
22:   c0 20 00 00 00 00       larl    %r2,22 <main+0x22>
24: R_390_PC32DBL       .data..Lubsan_data1+0x2
28:   c0 e5 00 00 00 00       brasl   %r14,28 <main+0x28>
2a: R_390_PLT32DBL      __ubsan_handle_out_of_bounds+0x2
```
3. ubsan data section info:
``` 
0000000000000000 <.data..Lubsan_data1>:
0: R_390_64     .rodata              <=== source_location.location->file_name
8: 00 00 00 04  .long   0x00000004   <=== source_location.location->line
c: 00 00 00 05  .long …
```
> support ubsan for kpatch

- kpatch-build/kpatch-build
kpatch-build: Fix setlocalversion issue with 6.3 kernel
The kernel has a VERMAGIC_STRING, e.g. "6.2.0".  The module loader uses that string to ensure that all loaded modules' version strings match the kernel's.
If the kernel source is in a git tree, and if there are uncommitted changes, the version string will have a '+' or "-dirty" appended to it, like "6.1.0+" or "6.2.0-dirty".  This dirty tree detection is done by the setlocalversion script.
This affects kpatch-build in a few ways.  When it builds the original kernel, in some cases there are uncommitted changes to the makefiles.  When it builds the patched kernel, there are additional uncommitted changes due to the .patch file being applied.
We want to avoid the VERMAGIC_STRING changing between builds.  Otherwise it would cause …
> kpatch-build: Fix setlocalversion issue with 6.3 kernel

- kmod/patch/kpatch-syscall.h
Since linux 'commit 2213d44e140f ("s390/syscalls: get rid of system call alias functions")', s390 syscall wrappers are modified. Adjust it accordingly for kpatch
> kpatch-syscall: update syscall macros for s390

- doc/INSTALL.md
shrinks the size of the sub-section header below  
the OpenEuler section, reducing confusion as to  
what section that is a part of, as it is only  
necessary for OpenEuler machines
> INSTALL.md: update OpenEuler prereqs formatting

- test/integration/rhel-9.2/data-new-LOADED.test
- test/integration/rhel-9.2/data-new.patch
- test/integration/rhel-9.2/gcc-static-local-var-6.patch
- test/integration/rhel-9.2/macro-callbacks.patch
- test/integration/rhel-9.2/module-LOADED.test
- test/integration/rhel-9.2/module.patch
- test/integration/rhel-9.2/multiple.test
- test/integration/rhel-9.2/new-function.patch
- test/integration/rhel-9.2/new-globals.patch
- test/integration/rhel-9.2/shadow-newpid-LOADED.test
- test/integration/rhel-9.2/shadow-newpid.patch
- test/integration/rhel-9.2/special-static.patch
- test/integration/rhel-9.2/symvers-disagreement-FAIL.patch
- test/integration/rhel-9.2/syscall-LOADED.test
- test/integration/rhel-9.2/syscall.patch
- test/integration/rhel-9.2/warn-detect-FAIL.patch
RHEL-9.2 releases today, add integration tests.
> test/integration/rhel-9.2: add kernel-5.14.0-284.11.1.el9_2 tests

- kpatch-build/kpatch-build
- test/integration/lib.sh
VMware's Photon OS uses kpatch to build and load kernel livepatches, starting with 3.0.
Ref: https://github.com/vmware/photon/tree/master/SPECS/kpatch
It would be nice to have support for Photon OS in kpatch-build, so that kpatch-build works for
Photon out of the box. Ideally, this will work the same as for other supported distros,  where
kpatch-build can be invoked just as:
`kpatch-build <name>.patch.`
This commit handles setup of all kernel sources, vmlinux files, etc for Photon OS.
cc @sshedi
> kpatch-build: support Photon OS distribution

- .github/workflows/stale.yml
kpatch maintainers have limited time.  While we greatly appreciate all of our contributors, unfortunately it's not uncommon for kpatch issues and PRs to get ignored for years.
Add a github workflow which marks issues/PRs stale after 30/60 days, and then closes them after an additional week of inactivity.  Anybody who cares about a particular issue/PR is welcome to help keep it open by stating their case in a comment.
The stale tag gets cleared by adding a comment to the issue/PR, or by manually removing the stale tag.
An assignee can be added to a long-term issue/PR to prevent it from getting marked stale.
The action (which adds/removes stale tags, adds comments, and closes issues/PRs) runs daily at 10:00 UTC.
Suggested-by: Joe Lawrence <joe.lawrence@redhat.com>
> github actions: Add stale workflow

- kpatch-build/create-diff-object.c
PowerPC implements alternative instructions with __ftr_fixup and __ftr_alt_* sections, for example net/core/dev.o:
Disassembly of section __ftr_alt_97:
0000000000000000 <__ftr_alt_97>:
0: 3c 00 40 7c pause_short
4: 3c 00 40 7c pause_short
8: 3c 00 40 7c pause_short
c: 3c 00 40 7c pause_short
Disassembly of section __ftr_fixup:
0000000000000000 <__ftr_fixup>:
0: 00 00 00 00 .long 0x0
4: 00 00 04 00 .long 0x40000
...
10: R_PPC64_REL64 .text.napi_busy_loop+0x1cc
18: R_PPC64_REL64 .text.napi_busy_loop+0x1dc
20: R_PPC64_REL64 __ftr_alt_97+0x20
28: R_PPC64_REL64 __ftr_alt_97+0x2c
34: 00 00 04 00 .long 0x40000
...
40: R_PPC64_REL64 .text.napi_busy_loop+0x3c0
48: R_PPC64_REL64 .text.napi_busy_loop+0x3d0
50: R_PPC64_REL64 __ftr_alt_97+0x24
58: R_PPC64_REL64 __ftr_alt_97+0x30
64: 00 00 04 00 .long …
> kpatch-build: skip mangling for powerpc cpu feature relocations

- contrib/kpatch.spec
- kpatch/kpatch
v0.9.9:
- Support for gcc-13
- Support for Linux 6.2
- Support for UBSAN kernels
- Fix handling of PowerPC cpu features
- Added RHEL-8.8 and 9.2 integration tests
> Bump to version v0.9.9

- kpatch-build/kpatch-build
Verify_patch_files() use `lsdiff` to get patches' path and verify they are supported. To be consistent with apply_patches() which using `patch -p1`, `lsdiff` should use '--strip=1' paremeter.
Close: #1357
> kpatch-build: fix missed parameter of verify_patch_files

- kpatch-build/list.h
This upstream list.h offsetof implementation rely on undefined behavior implementation. I got SIGILL when building with flag -fsanitize=undefined by clang. Using __builtin_offsetof will fix this problem.
> Fix undefined behavior problem when using list_foreach_entry

- kpatch-build/kpatch-build
kpatch-build uses gawk to find special section's struct size, but gawk is not always installed. So check if gawk is installed.
> kpatch-build: check if gawk exist

- kpatch-build/kpatch-build
- test/integration/lib.sh
There are many different distribution of linux kernel. However, it may not be good to support one new distribution just by adding a judgment condition. Therefore, I move it into a function. In the future, if a new distribution need to be supported, it may be more elegant.
> Support Anolis OS in a more elegant way

- kmod/patch/kpatch-syscall.h
The KPATCH_SYSCALL_DEFINEn macros in kpatch-syscall.h do not provide the same syscall metadata (saved in the __syscalls_metadata and _ftrace_events ELF sections) as the kernel.  These same macros also instruct kpatch-build to ignore changes to these sections.  This works fine as long as there are other unmodified syscalls present in the object file.  However, if not, the kpatch syscall macros may result in either metadata ELF sections not appearing in the patched object file. The create-diff-object program expects to encounter any ELF section that has been marked by KPATCH_IGNORE_SECTION in the patched object file.
To avoid this limitation, create dummy __syscalls_metadata and _ftrace_events entries for the kpatch-modified syscall.  The specific values shouldn't matter since their …
> kmod: maintain syscall metadata sections in kpatch syscall macros

- kpatch-build/kpatch-build
- test/integration/lib.sh
OpenCloudOS is a centos-like Linux distribution.
I test kpatch in OpenCloudOS V8 and V9.
It works well in V9. But v8 itself has two problems:
1. no available epol repo, so kpatch can't install ccache.
2. executing 'uname -r' can't get an accurate kernel version.
Both problems have been notified to the OpenCloudOS community. After they fix these problems, kpatch will work well in all versions.
> kpatch-build: add support for OpenCloudOS

- test/integration/kpatch-test
If the kernel log is empty prior to running the integration tests, the following confusing status may be reported:
...
ERROR: dmesg overflow, try increasing kernel log buffer size
SUCCESS
This occurs because the script can't find an empty dmesg entry when the tests are complete.  Copy the upstream kernel livepatching kselftests to fix this by logging a canary message at the beginning of the integration tests.  This will ensure a "real" message than can be found at the end.
Fixes: de1d0c6e08e6 ("kpatch-test: don't clear dmesg during test")
> kpatch-test: add dmesg entry at start of test

- kpatch-build/kpatch-build
Adds linux kernel version checks to all functions pertaining to struct paravirt_patch_site as it is removed in Linux v6.8+
Fixes: https://github.com/dynup/kpatch/issues/1380
> kpatch-build: handle paravirt absence in Linux v6.8+

- kpatch-build/kpatch-build
When CONFIG_WERROR is set, CONFIG_LD_ORPHAN_WARN_LEVEL of "error" will fail for kernels built with KCFLAGS="-ffunction-sections" due to all the "unplaced orphan section .text.<function> <object-file.o>" errors.  This MR temporarily demotes ld --orphan-handling to a mere warning so that kpatch-build may complete.
> Fix builds with CONFIG_ERROR

- kpatch-build/kpatch-build
Make kpatch-build aware about the ID of Amazon Linux distributions. No other special changes are needed.
> Recognize Amazon Linux ID in kpatch-build

- kpatch-build/kpatch-build
s390/kpatch-build: add -fPIE flag with -mno-pic-data-is-text-relative
-mno-pic-data-is-text-relative compiler flag expects -fPIC/-fPIE flag
along with it.  Since kernel commit 778666df60f0 ("s390: compile
relocatable kernel without -fPIE"), the -fPIC/-fPIE flag is missing when
creating kpatch module and this can lead to the following error:
cc1: error: ‘-mno-pic-data-is-text-relative’ cannot be used without
‘-fpic’/‘-fPIC’.
Previously kpatch-build didnt show up this issue, as the previous kernel
was built with -fPIE.
However, kpatch build could fail with kernel commit 778666df60f0 ("s390:
compile relocatable kernel without -fPIE"), where -fPIE is not included.
Hence, include it in kpatch-build for all kernels < 6.10.0
Note:
Latest s390 kernel is built with -fPIC flag.
i.e. kernel commit …
> s390/kpatch-build: add -fPIC flag with -mno-pic-data-is-text-relative

- kpatch-build/kpatch-build
Three minor fix-ups for kpatch-build and upstream kernel trees:
1. The supported_{deb,rpm}_distro() functions are now called when running with `USERSRCDIR`.  Protect against indexing their associated arrays with empty strings
2. Set the correct `VMLINUX` path when `USERSRCDIR` is specified ($TEMPDIR vs. $KERNEL_BACKUPDIR)
3. Fix setlocalversion for pre-v6.3 kernels - we fixed this for newer kernels, but sometimes it's handy to run tests against older kernels... it's not too difficult to support both pre and post v6.3 kernels here.
> Small upstream kernel fixes

- doc/patch-author-guide.md
The official website says CVE users should reference CVE-2016-5696 instead of CVE-2016-5389.
> patch-author-guide: correct the example CVE ID information

- kpatch-build/kpatch-build
I'm currently experimenting with generating live patches for NixOS. These are some tiny fixes that make the script work for me.
There are two changes here:
- The first patch fixes the case where kpatch files are installed as read-only (which is the default on NixOS).
- ~~The second patch allows skipping the distro checks, which allows experimenting with new distros.~~ (not necessary)
> NixOS Fixes

- man/Makefile
Man pages for kpatch are created via gzip which includes timestamp of original file by default. This means the compressed file will change depending on the time at which the repository was cloned / updated, leading to non-deterministic builds. Pass option to disable this.
> man: fix reproducibility - remove file timestamps

- kpatch-build/kpatch-build
With IBT enabled, the kernel build runs objtool not on individual object files, but the post-linked vmlinux.o.  Kpatch-build does not currently and may not ever support binary comparison of vmlinux.o, so mark it as not supported for now.
> kpatch-build: fail CONFIG_X86_KERNEL_IBT as not supported

- kpatch-build/kpatch-build
Introduce an option to print the version of kpatch-build.
When kpatch-build is installed in to a system, we and run for some time. It will have some difficulty to find out the version of the kpatch-build in the system.
So, I introduce '--version' option for user to see it. The tag released now seems to be v0.9.9, so I set version to be 0.9.9 of master branch.
> kpatch-build: introduce version print option

- kpatch-build/Makefile
Add -std=gnu11 to CFLAGS for kpatch-build tooling.  This aligns with the kernel build and avoids confusion when older tooling may default to earlier versions.
Closes: #1416 ("C99 code vs. gcc defaults?")
> kpatch-build: set C language standard to gnu11

- kpatch-build/kpatch-build
- kpatch/kpatch
- test/integration/lib.sh
Fix the following:
In kpatch/kpatch line 358:
break
^-- SC2317 (info): Command appears to be unreachable. Check usage (or ignore if invoked indirectly).
In kpatch-build/kpatch-build line 1424:
"$TOOLSDIR"/create-diff-object $CDO_FLAGS "orig/$i" "patched/$i" "$KOBJFILE_NAME" \
^--------^ SC2086 (info): Double quote to prevent globbing and word splitting.
In kpatch-build/kpatch-build line 1494:
MAKEVARS[$idx]=${MAKEVARS[$idx]/${KPATCH_CC_PREFIX}/}
^--^ SC2004 (style): $/${} is unnecessary on arithmetic variables.
In kpatch-build/kpatch-build line 1510:
"$TOOLSDIR"/create-klp-module $extra_flags "$TEMPDIR/patch/tmp.ko" "$TEMPDIR/patch/$MODNAME.ko" 2>&1 | logger 1
^----------^ SC2086 (info): Double quote to prevent globbing and word splitting.
In test/integration/lib.sh line 119:
tdnf install …
> tree: fix latest shellcheck complaints

- kpatch-build/Makefile
create-kpatch-module.c is duplicated in kpatch-build/Makefile.
> kpatch-build/Makefile: remove duplicate entry for create-kpatch-module.c

- test/integration/amzn-2023/data-new-LOADED.test
- test/integration/amzn-2023/data-new.patch
- test/integration/amzn-2023/gcc-static-local-var-6.patch
- test/integration/amzn-2023/macro-callbacks.patch
- test/integration/amzn-2023/module-LOADED.test
- test/integration/amzn-2023/module.patch
- test/integration/amzn-2023/multiple.test
- test/integration/amzn-2023/new-function.patch
- test/integration/amzn-2023/new-globals.patch
- test/integration/amzn-2023/shadow-newpid-LOADED.test
- test/integration/amzn-2023/shadow-newpid.patch
- test/integration/amzn-2023/special-static.patch
- test/integration/amzn-2023/symvers-disagreement-FAIL.patch
- test/integration/amzn-2023/syscall-LOADED.test
- test/integration/amzn-2023/syscall.patch
- test/integration/amzn-2023/warn-detect-FAIL.patch
This commit adds tests for Amazon Linux 2023. All patches apply and integration tests pass.
> test/integration/amzn-2023: Add integration tests for AL2023

- test/integration/rhel-9.5/data-new-LOADED.test
- test/integration/rhel-9.5/data-new.patch
- test/integration/rhel-9.5/gcc-static-local-var-6.patch
- test/integration/rhel-9.5/macro-callbacks.patch
- test/integration/rhel-9.5/module-LOADED.test
- test/integration/rhel-9.5/module.patch
- test/integration/rhel-9.5/multiple.test
- test/integration/rhel-9.5/new-globals.patch
- test/integration/rhel-9.5/shadow-newpid-LOADED.test
- test/integration/rhel-9.5/shadow-newpid.patch
- test/integration/rhel-9.5/special-static.patch
- test/integration/rhel-9.5/syscall-LOADED.test
- test/integration/rhel-9.5/syscall.patch
- test/integration/rhel-9.5/warn-detect-FAIL.patch
Updates integration tests for rhel-9.5 to kernel-5.14.0-503.11.1.el9_5
> Integration tests rhel-9.5 final

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
The __mcount_loc section contains the addresses of patchable ftrace sites which is used by the ftrace infrastructure in the kernel to create a list of tracable functions and to know where to patch to enable tracing of them.  On some kernel configurations, section is called __patchable_function_entries and is generated by the compiler.  Either of __mcount_loc or __patchable_function_entries is recognised by the kernel but for these configurations, use __patchable_function_entries as it is what is expected.
The x86_64 arch is special (of course).  Unlike other arches (ppc64le and aarch64) a x86_64 kernel built with -fpatchable-function-entry will generate nops AND create rela__patchable_function_entries for functions even marked as notrace.  For this arch, always create __mount_loc sections …
> create-diff-object: __patchable_function_entries section support

- kmod/patch/kpatch-syscall.h
RHEL-9.6 backported upstream s390x syscall wrappers [1] that now need a distro-specific kernel version check.
[1] https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/5019/diffs?file=4c7281905bacd504a8205467bfd8e28ac241dbed#diff-content-4c7281905bacd504a8205467bfd8e28ac241dbed
> Update s390x syscall wrappers for RHEL-9.6

- kmod/patch/kpatch-syscall.h
When CONFIG_COMPAT is disabled (No 31 bit emulation support), macro __S390_SYS_STUBx() is nop.
(See arch/s390/include/asm/syscall_wrapper.h).
Also, __SC_COMPAT_CAST definition is not available, which leads to build error.
Hence, __KPATCH_S390_SYS_STUBx() inherited from __S390_SYS_STUBx() macro, should point also point to nop when CONFIG_COMPAT is disabled.
> kpatch-syscall: Fix kpatch s390 error when CONFIG_COMPAT is disabled

- kmod/patch/Makefile
Starting from linux commit 13b25489b6f8 ("kbuild: change working directory to external module directory with M="), the kpatch-build fails:
make -C /root/linux M=/root/.kpatch/tmp/patch CFLAGS_MODULE=''
make[1]: Entering directory '/root/linux'
make[2]: Entering directory '/root/.kpatch/tmp/patch'
LDS     kpatch.lds
make -C /root/linux M=/root/.kpatch/tmp/patch CFLAGS_MODULE='' patch-hook.o
***
*** The external module source tree is not clean.
*** Please run 'make -C /root/linux M=/root/linux clean'
***
The easiest and quickest way to fix the build is to remove the $(KPATCH_MAKE) patch-hook.o in Makefile.  Unfortunately this would mean make `patch-hook.o` cannot be performed directly.  However the Makefile still lists patch-hook.o's source dependencies, so if any are updated, the kpatch …
> kmod: fix OOT kpatch kmod build

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
These two patches are logically separate but are based on recent fixes for bugs I encountered recently in Photon OS. I think they can also be applicable to upstream kpatch.
The changes are:
1. Using the dynamically read prefix symbol size instead of hardcoding to 16 (fixes cases with non-standard padding for __cfi)
2. Refactor definitions of callback structs in kpatch-patch.h to compile with the correct input type for the callback function. Fixes a "bad function cast" gcc error that I ran into, which occurs during the final livepatch module compilation.
> Patches from Photon OS

- contrib/kpatch.spec
- kpatch/kpatch
v0.9.10:
- Support for Amazon Linux, Anolis OS, and OpenCloudOS distros
- Fix cleanup when kpatch is installed in read-only location
- Added RHEL-8.9, 9.3, 8.10, 9.4, and 9.5 integration tests
- Added AL2023 integration tests
- Support for __patchable_function_entries sections
> Bump to version v0.9.10

- kpatch-build/create-kpatch-module.c
create-kpatch-module.c can't compile because limits.h is not included by other file with musl libc.
Adding the import permits the build to work on musl system.
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/78844/diffs
> kpatch-build: add missing include for musl

- kpatch-build/lookup.c
When building a livepatch, we assume symbols from "readelf -s" is the same as the order observed in kallsyms. We calculate sympos of a symbol based on this order (readelf -s). However, with gcc-14, "readelf -s" may present the symbols in a different order. For example:
With gcc 13:
32951: ffff8000802edf20   172 FUNC    LOCAL  DEFAULT    2 zero_user_segments.constprop.0
33497: ffff8000802fb798   236 FUNC    LOCAL  DEFAULT    2 zero_user_segments.constprop.0
47034: ffff80008044b250   172 FUNC    LOCAL  DEFAULT    2 zero_user_segments.constprop.0
51466: ffff8000804be260   236 FUNC    LOCAL  DEFAULT    2 zero_user_segments.constprop.0
51483: ffff8000804bf6a8   172 FUNC    LOCAL  DEFAULT    2 zero_user_segments.constprop.0
52287: ffff8000804cb098   172 FUNC    LOCAL  DEFAULT    2 …
> Fix sympos for gcc-14

- kpatch-build/create-diff-object.c
Typically, symbols within the same object file can be referenced directly for better performance. However, when the patched code stores a function pointer (R_390_GOTENT and rela symbol type is STT_FUNC), using a dynrela is a safer approach. This ensures that if the function is used as a asynchronous callback, the kernel does not attempt to execute an invalid pointer after the module is unloaded. Instead, with a dynrela, the kernel will invoke the original function, preventing potential crashes.
Test program: Test if the original function ptr address is printed during patch load / unload.
https://github.com/iii-i/linux/commit/0f400db024fb3faaeb2bc39f114ea5805ad8c963
`Patched code (function ptr rela):`
`void *patchme(void) { printk(KERN_NOTICE "patched\n"); return patchme; }`
`  0:   c0 04 …
> create-diff-object: Fix function pointer rela on s390

- kpatch-build/create-diff-object.c
- kpatch-build/create-klp-module.c
- kpatch-build/create-kpatch-module.c
- kpatch-build/kpatch.h
Hi Joe,
It‘s better  to show full paths in ~/.kpatch/build.log for changed object files.
For examble:
Now output in build.log:
tcp.o: changed function: tcp_sendmsg
Improved output in build.log:
net/ipv4/tcp.o: changed function: tcp_sendmsg
> create-diff-object: Include full paths in build.log output for changed object files

- kpatch-build/create-diff-object.c
Upstream commit [1] renamed .data.once section as .data..once. Handle it the same as .data.once sections.
[1] dbefa1f31a91 ("Rename .data.once to .data..once to fix resetting WARN*_ONCE")
Signed-off-by: Song Liu <song@kernel.org>
> CDO: Handle .data..once sections.

- kmod/patch/kpatch-syscall.h
- test/integration/rhel-9.6/data-new-LOADED.test
- test/integration/rhel-9.6/data-new.patch
- test/integration/rhel-9.6/gcc-static-local-var-6.patch
- test/integration/rhel-9.6/macro-callbacks.patch
- test/integration/rhel-9.6/module-LOADED.test
- test/integration/rhel-9.6/module.patch
- test/integration/rhel-9.6/multiple.test
- test/integration/rhel-9.6/new-globals.patch
- test/integration/rhel-9.6/shadow-newpid-LOADED.test
- test/integration/rhel-9.6/shadow-newpid.patch
- test/integration/rhel-9.6/special-static.patch
- test/integration/rhel-9.6/syscall-LOADED.test
- test/integration/rhel-9.6/syscall.patch
- test/integration/rhel-9.6/warn-detect-FAIL.patch
* Fix an s390x system call macro compilation error
* Rebase RHEL-9.5 integration tests, no modifications needed
> Add integration tests for RHEL-9.6 release

- kpatch-build/create-diff-object.c
Upstream kernel commit [1] renamed .data.unlikely section as .data..unlikely. Handle it the same as .data.unlikely sections.
[1] bb43a59944f4 ("Rename .data.unlikely to .data..unlikely")
Signed-off-by: Song Liu <song@kernel.org>
> CDO: Handle .data..unlikely sections.

- kpatch-build/create-diff-object.c
- kpatch-build/log.h
log_normal() is used in some critical errors, such as:
"changed section XXXX not selected for inclusion".
It is not very obvious this is a fatal error.
Introduce log_error() and use it for critical messages.
Note that we are not using ERROR() here, because ERROR() will terminate CDO immediately, which is not the desired behavior.
> CDO: Introduce log_error()

- kpatch-build/kpatch-build
The Fedora rpm download web allow the https only.
> Fix the Fedora download source code fail

- kpatch-build/lookup.c
STB_LOCAL is a bind attribute, not a type attribute. Just fix it.
> lookup: fix local bind check

- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
Roberto Bergantinos Corpas <rbergant@redhat.com> reported a problem when building a kpatch for:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/patch/?id=021ba7f1babd029e714d13a6bf2571b08af96d0f
```
MODPOST /root/.kpatch/tmp/patch/Module.symvers
ERROR: modpost: module livepatch-021ba7f1babd029e714d13a6bf2571b08af96d0f uses symbol dma_buf_export from namespace DMA_BUF, but does not import it.
ERROR: modpost: module livepatch-021ba7f1babd029e714d13a6bf2571b08af96d0f uses symbol dma_buf_put from namespace DMA_BUF, but does not import it.
ERROR: modpost: module livepatch-021ba7f1babd029e714d13a6bf2571b08af96d0f uses symbol dma_buf_fd from namespace DMA_BUF, but does not import it.
```
The problem is that the livepatch needs to access symbols exported via the "DMA_BUF" …
> kpatch-build: Add support for module symbol namespaces

- doc/patch-author-guide.md
Now that kpatch-build passes along .modinfo "import_ns" key/value pairs, add a hint in the patch author guide about using MODULE_IMPORT_NS.  The most likely use case will be formerly built-in code that now needs the import when extracted out into a kpatch.ko.
> patch-author-guide: add a blurb about module namespaces

- .gitignore
- .packit.yml
This MR adds a packit [1] configuration to enable integration testing of upstream commits and downstream kernel combinations. The initial version would test upstream kernels and manually triggered.  It will be later enhanced by Red Hat QE to test RHEL composes, etc.
[1] https://packit.dev/docs/about
> packit: initial commit

- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-cc
kpatch-build: fix ppc64le trampoline handling after BPF changes
Starting from linux commit eec37961a56a (powerpc64/ftrace: Move
ftrace sequence out of line) the kpatch-build fails
Extracting new and modified ELF sections
create-diff-object: ERROR: fs/proc/cmdline.o: kpatch_create_ftrace_callsite_sections: 3860: cmdline_proc_show: unexpected instruction in patch section of function
fs/proc/cmdline.o: changed function: cmdline_proc_show
doing "deep find" for parent object
ERROR: invalid ancestor arch/powerpc/tools/vmlinux.arch.o for arch/powerpc/tools/vmlinux.arch.o. Check /root/.kpatch/build.log for more details.
Moving the ftrace stubs out-of-line modified the prologue on ppc64le
and it now uses a single nop instead of two.
Update the nop check in create-diff-object.c accordingly.
Also …
> kpatch-build: fix ppc64le trampoline handling after BPF changes

- README.md
- kmod/patch/kpatch-syscall.h
- kpatch-build/Makefile
- kpatch-build/create-diff-object.c
- kpatch-build/kpatch-build
- kpatch-build/kpatch-elf.c
- kpatch-build/kpatch-elf.h
- test/unit/Makefile
This is a rebase of #1302 with some more changes and some already merged patches removed.
It is supposed to work with the `sframe` based reliable stack unwinder posted upstream: 
[[PATCH 0/8] unwind, arm64: add sframe unwinder for kernel](https://lore.kernel.org/all/20250127213310.2496133-1-wnliu@google.com/)
NOTE:
- The sframe sections are skipped for now in the livepatch module because the above series doesn't support modules yet. I am trying to make that work both from the kernel side and also in Kpatch and will add a patch later.
Building and testing a livepatch on a 6.12 arm64 kernel for the following basic patch:
```
[ec2-user@ip-172-31-32-86 ~]$ cat CVE-1234-5678.patch
From 9c372fa658da9ac55e3acb7c3e4f3035f9241c1d Mon Sep 17 00:00:00 2001
From: Puranjay Mohan <pjy@amazon.com>
Date: …
```
> Add support for Arm64 including all changes in PR #1302 (@swine, @surajjs95, @t-msn, and others)
