dynup/kpatch

kpatch-build/kpatch-build
Fixes #480 
Signed-off-by: Seth Jennings <sjenning@redhat.com>
=> ensure scmversion consistency across builds

kmod/patch/patch-hook.c
Change the config name to match today's upstream change.
=> CONFIG_LIVE_PATCHING -> CONFIG_LIVEPATCH

kmod/core/core.c
In recent kernels, set_memory_ro() and set_memory_rw() are no longer
exported.  Call them anyway :-)
Fixes #496.
=> kmod/core: call unexported set_memory_[ro|rw]

kpatch-build/kpatch-gcc
Add a couple of entries to the kpatch-gcc ignore list.
Fixes: #518 
Fixes: #530
=> kpatch-gcc: update ignore list

kpatch-build/create-diff-object.c
=> CSWTCH fix, take 2

kpatch-build/create-diff-object.c
Deal with a special case where gcc needs a pointer to the address at the end of
a data section.
This is usually used with a compare instruction to determine when to end a
loop.  The code doesn't actually dereference the pointer so this is "normal"
and we just replace the section reference with a reference to the last symbol
in the section.
Note that this only catches the issue when it happens at the end of a section.
It can also happen in the middle of a section.  In that case, the wrong symbol
will be associated with the reference.  But that's ok because:
1) This situation only occurs when gcc is trying to get the address of the
symbol, not the contents of its data; and
2) Because kpatch doesn't allow data sections to change, &(var1+sizeof(var1))
will always be the same as &var2.
Fixes: …
=> create-diff-object: handle reference to end of section

kpatch-build/create-diff-object.c
Refine the static local variable handling again.  This builds on a
previous patch by Zhou Chengming.
This fixes the following bugs reported by Zhou:
1.          xxx.123 ---> xxx.123 (previous correlation by coincidence)
xxx.256 ---> xxx.256 (previous correlation by coincidence)
But real xxx.123 ---> xxx.256
In this case, the code doesn't work. Because when find patched_sym for
xxx.123, the xxx.256 in patched_object hasn't been de-correlated.
2. old-object | new-object
func1 | func1
xxx.123 | xxx.123 (inline)
func2 | func2
xxx.256 | xxx.256
xxx.123 | xxx.123 (inline)
When find patched_sym for xxx.123, first find xxx.123 in func1 of new-object,
But then find xxx.256 in func2 of new-object.
So I think should not iterate the base-sections, when find one, just go out to next symbol.
Both of …
=> create-diff-object: more static local variable rework

README.md, doc/patch-author-guide.md
Been wanting to write this forever, have to start somewhere...
/cc @euspectre
=> doc: patch author guide, first take

kmod/core/core.c
Pretty painless change. Fix up the kpatch core module to use the new core_layout fields. It compiles and I tested a few patch modules with the core module.
Fixes #578.
=> kmod: core: use new module core_layout struct

kmod/core/core.c
When a patch module is loaded, the kernel facilities like alternatives
and paravirt may alter some of its instructions. This happens before
Kpatch core module is notified and tries to apply dynrelas to it. If an
instruction to apply a dynrela to has already been changed by these
facilities, an incorrect instruction might be written as a result.
The core module now detects such conditions and does not apply dynrela
to the changed instructions.
Suggested by Josh Poimboeuf in the discussion of
https://github.com/dynup/kpatch/issues/580.
Changes in v.2:
* Used pr_notice to give more emphasis to the messages.
* Added an explanation message.
=> kmod/core: Skip relocations of already altered instructions

kpatch-build/create-diff-object.c
This fixes the detection of WARN_ON_ONCE, WARN_ONCE, and WARN_TAINT_ONCE
on Linux 4.6 and newer.
The signature for those macros changed with upstream Linux commit
dfbf2897d004 ("bug: set warn variable before calling WARN()").
Fixes #602.
=> create-diff-object: fix WARN*_ONCE detection on newer kernels

doc/patch-author-guide.md
Update the patch author guide to reflect some recent experiences (with
upstream commits 19be0eaffa3a and 906c55579a63).
=> doc: some patch author guide updates

kpatch-build/create-diff-object.c
When pruning entries from the fixup table, update the offsets in
.rela__ex_table otherwise the relas might point to the wrong fixup entry
or even out of the .fixup section.
Fixes #615.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
=> create-diff-object: Update fixup offsets in .rela__ex_table

kmod/core/core.c
If an activeness safety check fails for kernels newer than 4.6, the
error is silently ignored because the newer version of
kpatch_backtrace_address_verify() doesn't set args.ret on error.
It would be an easy fix to just set args->ret on error, but I think a
better approach is just to combine the two versions of the function into
a single function with the use of a little macro trickery.
=> kmod/core: fix activeness safety checks for kernels >= 4.6

kmod/core/core.c, kmod/core/shadow.c
These are mostly trivial, but really simple to clean up.  With a clean slate, we can monitor future pull requests that may introduce new complaints  (I have a script in the works).
=> Fix static code analyzer complaints

kpatch-build/create-diff-object.c
When CONFIG_DEBUG_ATOMIC_SLEEP is enabled, __might_sleep calls will add
the line number to the instruction stream.  Detect and revert any such
changes.
Fixes: #657.
=> detect and ignore __might_sleep line number changes

doc/patch-author-guide.md
Since I was researching how kpatch implemented these features, I figured I could document them along the way in the patch authoring guide.
(Un)load hooks - stop_machine context -- is it worth mentioning the `kpatch_module_config` case?  In that case, are the hooks called in process context (ie, interrupts may occur) under some module mutex?
Shadow variables - I didn't see any kpatch examples outside of the integration tests.  Are there any interesting pitfalls that we should point out?
=> Add author guide examples

README.md, doc/patch-author-guide.md
More odds and ends for the patch writer's guide (and one for the top level readme).
=> Author guide notes

README.md
=> readme: add Ubuntu apt-security 404 note

doc/patch-author-guide.md
I couldn't find a good place in the document for this, so I just added
an "Other issues" section at the end.
Fixes #738.
=> doc: document workaround for printk_once() and friends

kpatch-build/create-diff-object.c
=> kpatch-build: ignore .discard sections

README.md, doc/patch-author-guide.md
Fixes a few minor typos/inconsistencies and adds installation instructions for Stretch.
=> Documentation updates

kpatch-build/create-diff-object.c
The paravirt_patch_site struct has 12 bytes of data and 4 bytes of
padding, for a total of 16 bytes.  However, when laying out the structs
in the .parainstructions section, the vmlinux script only aligns before
each struct's data, not after.  So the last entry doesn't have the
4-byte padding, which breaks kpatch_regenerate_special_section()'s
assumption of a 16-byte struct, resulting in a memcpy past the end of
the section.
Fixes #747.
=> create-diff-object: handle missing padding at end of special section

README.md
Switching dnf to yum under RHEL, CentOS, and oracle.
=> dnf to yum

kpatch-build/lookup.c
Fix discarded symbol handling for all kernel versions.
Fixes #765.
=> lookup: fix discarded symbol handling for all kernel versions

kpatch-build/create-diff-object.c
kpatch_include_symbol() is confusing.  Refactor it:
- Remove the "inclusion tree" debug messages.  I never use them, and
they just help make the code more confusing and the debug output more
cluttered.
- Split it up into two functions: kpatch_include_symbol() and
kpatch_include_section(), so that kpatch_include_section() can be used
elsewhere.
- Call kpatch_include_section() from kpatch_include_standard_elements().
This covertly fixes #702, by also including the .rela.rodata section.
- Add a bunch of comments to clarify some of the trickier points.
Fixes #702.
Fixes #807.
=> create-diff-object: refactor symbol/section inclusion logic

kpatch-build/create-diff-object.c
Check that none of the relocations are out-of-range of their
corresponding sections before writing the output elf.
Fixes: #618
=> create-diff-object: check for out-of-range relocations

kpatch-build/create-diff-object.c
ppc64le lacked kpatch_line_macro_change_only() implementation. Add one
based on x86_64 version and available unit tests.
Fixes: #843 
---
Tested on objectfiles available in our unit tests and this works fine, it might not cover other cases, but I guess it is still better than nothing.
=> ppc64le: add WARN detection

kpatch/kpatch
Show just modules in ``kpatch list``
=> Show just modules in kpatch list

kpatch-build/lookup.c
Before we were adding the undefined symbols to the lookup table, but we
were skipping them by setting the sym.skip flag.
With 3aa5abb8072c ("kpatch-build: use symbol table instead of kobject"),
the skip flag was removed but the undefined symbol check was removed
with it.
The skip flag can remain gone.  Instead of adding undefined symbols to
the table and skipping them when iterating the table, just don't add
them to start with.
Also make the sscanf conditional lines identical, to ease maintenance.
Fixes #869.
Fixes: 3aa5abb8072c ("kpatch-build: use symbol table instead of kobject")
=> lookup: don't add undefined symbols to the lookup table

kpatch-build/create-diff-object.c, kpatch-build/kpatch-gcc, kpatch-build/kpatch.h, kpatch-build/log.h, kpatch-build/lookup.c
Collection of small changes to cover some issues that popped up as part of #876.
=> kpatch-build misc fixups

contrib/kpatch.spec, kpatch/kpatch
Create a patch release that includes fix(es) for:
* Increase the transition timeout, helpful for large CPU count systems
* Miscellaneous unit testing, ppc64, etc. fixes
=> Patch release v0.6.1

test/integration/kpatch-test
Couple of small improvements:
- saving build logs for failed tests
- include -FAIL tests in "quick" target
=> Integration test improvements

kpatch-build/lookup.c
A couple of small fixes for symtab_read function.
=> Symtab read fixes

man/kpatch.1
Added option version to man page, under commands, based on usage function in
kpatch/kpatch usage()
Signed-off-by: Sanskriti sharma <sansharm@redhat.com>
=> Added option to kpatch man page

README.md
Noticed this while looking at recent issues (#880).
Regards
Simon
=> README.md: mention callbacks/shadow variables in limitations

Makefile, test/integration/Makefile, test/integration/lib.sh, test/integration/test-vagrant, test/integration/vm-integration-run
A bunch of scripts to run integration tests on vagrant vms for main distros (f27/ubuntu1604/centos7).
=> Scripts for running integration tests within vagrant vms

kmod/core/core.c, kmod/patch/Makefile
Found a couple of issues while building dummy-patches for 4.20-rc kernels.
=> 4.20 updates

kpatch-build/create-diff-object.c
After Linux commit 47cdd64be483 ("dynamic_debug: refactor
dynamic_pr_debug and friends"), the name of the static local variable
used for dynamic printks is no longer "descriptor".
Make the is_special_static() check broader such that it doesn't care
about the variable name, and just whitelists any variable in the
__verbose section.
Fixes #990.
=> create-diff-object: Support dynamic debug on newer kernels

kpatch-build/create-diff-object.c, kpatch-build/create-klp-module.c, kpatch-build/create-kpatch-module.c, kpatch-build/kpatch-elf.c, kpatch-build/lookup.c
A bunch of small fixes of issues found by covscan. Please note that some of these are harmless or very unlikely so we might want to drop some of them, I just opted to clean-up the scan log as much as possible.
There are still some outstanding issues it still finds with these changes but I think all of those (except maybe list ones) are false positives. Here is the full covscal log: [scan-results.log](https://github.com/dynup/kpatch/files/3456376/scan-results.log)
Fixes: #984
=> Covscan fixes

kpatch-build/create-diff-object.c
While static keys (jump labels) are currently broken in livepatch, a
broken dynamic debug static key is harmless since it just disables
dynamically enabled debug printks in the patched code.
Fixes: #1021
=> create-diff-object: allow dynamic debug static keys

test/integration/vm-integration-run
Add an ability to run vagrant integration tests on specified
repos/commits.
=> test/integration: add an ability to check specific repo/commit

kpatch-build/create-diff-object.c
Some suggestion of cleanups I stumbled upon while trying to understand the code.
=> Misc cleanups

kpatch-build/create-diff-object.c
The RHEL powerpc kernel is compiled with -O3, which triggers some
"interesting" new optimizations.  One of them, which seems to be
relatively common, is the replacing of a function with two separate
"constprop" functions.
Previously we only ever saw a single constprop clone, so we just renamed
the patched version of the function to match the original version.  Now
that we can have two such clones, that no longer makes sense.
Instead of renaming functions, just improve the correlation logic such
that they can be correlated despite having slightly different symbol
names.  The first clone in the original object is correlated with the
first clone in the patched object; the second clone is correlated with
the second clone; and so on.
This assumes that the order of the symbols and sections …
=> create-diff-object: simplify mangled function correlation

kpatch/kpatch, test/integration/centos-7/multiple.test, test/integration/common/multiple.template, test/integration/fedora-27/multiple.test, test/integration/kpatch-test, test/integration/rhel-7.4/multiple.test, test/integration/rhel-7.5/multiple.test, test/integration/rhel-7.6/multiple.test, test/integration/rhel-7.7/multiple.test, test/integration/ubuntu-16.04/multiple.test
Couple of fixes for missing/failing module unloading found while running kpatch testsuite.
=> Unload fixes

kpatch-build/lookup.c
Kernel commit cb9b55d21fe0 modpost: add support for symbol namespaces
adds a new namespace column to Module.symvers file which can be blank.
fscanf is no longer a viable solution to parse that. Switch to the way
scripts/mod/modpost.c handles this and try to support both versions with
and without namespace column.
=> Make symvers reading code more flexible.

test/integration/rhel-8.1/cmdline-string-LOADED.test, test/integration/rhel-8.1/data-new-LOADED.test, test/integration/rhel-8.1/gcc-static-local-var-4.test.disabled, test/integration/rhel-8.1/meminfo-string-LOADED.test, test/integration/rhel-8.1/multiple.test, test/integration/rhel-8.1/shadow-newpid-LOADED.test
Add the missing *.test files in test/integration/rhel-8.1
=> test/integration: rhel-8.1 Add missing *.test files

kpatch-build/create-diff-object.c, kpatch-build/create-klp-module.c, kpatch-build/create-kpatch-module.c, kpatch-build/kpatch-intermediate.h, kpatch-build/lookup.c, kpatch-build/lookup.h
Some long overdue cleanups to the dynrela and lookup code.  In theory this should be no functional change.
=> dynrela cleanups

contrib/kpatch.spec
Prior to this commit, the kpatch.spec was not building because of #1042.
The kernel module is not built by default, but the spec was not updated accordingly.
With this commit, the kpatch.spec supports building the module or not using a %bcond.
Like the Makefile, it does not build the module by default.
Cheers,
=> Fix kpatch.spec

kpatch-build/create-kpatch-module.c
Or, to be exact, with addend values which cannot be represented by
a signed int variable.
This only applies to the old KPatch core.
Commit 15067fcd "kmod/core: apply dynrela addend for R_X86_64_64" fixed
calculation of the values for R_X86_64_64 dynrelas. This revealed
another issue, similar to https://github.com/dynup/kpatch/issues/1064.
Dynrelas are stored as 'struct kpatch_patch_dynrela' instances in the
patch module but both the patch module and kpatch.ko use
'struct kpatch_dynrela' to work with the dynrelas. 'addend' has type
'long' in kpatch_patch_dynrela but 'int' in kpatch_dynrela, so this
value can be truncated when read.
R_X86_64_64 dynrela can be created, for example, if a patch for vmlinux
refers to something like `(unsigned long)&idt_table+0x80000000` (a global
variable which …
=> kpatch-build: Detect R_X86_64_64 dynrelas with large addends

README.md
- Added Supported Architectures category to avoid confusion (for example https://github.com/dynup/kpatch/issues/1099#issuecomment-625913876).
- Updated Prerequisites category
=> Added Supported Architectures category

kmod/core/core.c
we remove the pre_patch_callback/post_unpatch_callback from the
stop_machine context. If a schedule/sleep happend in callbacks while the
process to be scheuded later will send IPI, because all interrupts
are disabled, the machine will trap into a  deadlock in such situation.
So we remove the pre_patch_callback and post_unpatch_callback from
the stop_machine to avoid such situation. On the other hand, to avoid
the race between the patched code and post-patch/pre-unpatch callbacks when
run in parallel, we didn't remove  the post_patch_callback and
pre_unpatch_callback from stop_machine.
=> deal with the deadlock may occur in stop_machine context.

kpatch-build/create-diff-object.c, kpatch-build/kpatch-build
Add the new .static_call_sites special section.
Fixes #1165.
=> kpatch-build: add support for static calls

kpatch-build/create-diff-object.c
A couple of minor fixes for the out-of-range relocation check.   These were found by inspection, so I don't have any unit tests.
=> A couple of fixes for the out-of-range relocation check

kpatch-build/create-diff-object.c
Fix for #1193. Posting as draft as it is supposed to be merged after #1186 and https://github.com/dynup/kpatch-unit-test-objs/pull/32
=> Make sure section symbols exist

test/integration/kpatch-test
I've got "Permission denied" error when /sys/kernel/debug/dynamic_debug/control setting.
=> kpatch-test: Change DYNDEBUG_CONTROL setting to use sudo

.gitignore, kpatch-build/create-diff-object.c, kpatch-build/kpatch-elf.h
Fix a couple of issues reported in #1253.
=> Multiple `__LINE__` macro detection fixes and improvements

README.md, doc/INSTALL.md
Update a lot of the old cruft and move the boring installation stuff to
a separate file.
=> readme: bring README.md into the 21st century

doc/patch-author-guide.md, kmod/patch/kpatch-macros.h, kmod/patch/kpatch-syscall.h, test/integration/linux-5.10.11/syscall-LOADED.test, test/integration/linux-5.10.11/syscall.patch, test/integration/rhel-7.9/syscall-LOADED.test, test/integration/rhel-7.9/syscall.patch, test/integration/rhel-8.4/syscall-LOADED.test, test/integration/rhel-8.4/syscall.patch
Add macros for patching syscalls, and a corresponding integration test.
=> Add syscall macros

kpatch-build/create-diff-object.c
Recent toolchains only create a section symbol if it's needed, i.e. if
there's a reference to it.  If there's a missing section symbol in
kpatch_create_intermediate_sections(), create one instead of erroring
out.
Fixes #1272.
=> create-diff-object: Create missing section symbol

README.md
This gets asked from time to time and Josh provided a good answer to #1296, so how about we add it to the FAQ.
=> README: Add arch porting question

test/integration/rhel-9.1/data-new-LOADED.test, test/integration/rhel-9.1/data-new.patch, test/integration/rhel-9.1/gcc-static-local-var-6.patch, test/integration/rhel-9.1/macro-callbacks.patch, test/integration/rhel-9.1/module-LOADED.test, test/integration/rhel-9.1/module.patch, test/integration/rhel-9.1/multiple.test, test/integration/rhel-9.1/new-function.patch, test/integration/rhel-9.1/new-globals.patch, test/integration/rhel-9.1/shadow-newpid-LOADED.test, test/integration/rhel-9.1/shadow-newpid.patch, test/integration/rhel-9.1/special-static.patch, test/integration/rhel-9.1/symvers-disagreement-FAIL.patch, test/integration/rhel-9.1/syscall-LOADED.test, test/integration/rhel-9.1/syscall.patch, test/integration/rhel-9.1/warn-detect-FAIL.patch
=> test/integration/rhel-9.1: add kernel-5.14.0-162.6.1.el9_1 tests

kpatch-build/create-diff-object.c
kpatch_mangled_strcmp() only ignores the digits after the period, but in the case of __UNIQUE_ID(), the symbol names have random digits before the period due to the use of `__COUNTER__`.  Make sure such symbols are properly correlated.
=> create-diff-object: fix __UNIQUE_ID() variable correlation

kmod/patch/kpatch-syscall.h, kpatch-build/create-diff-object.c, kpatch-build/gcc-plugins/gcc-common.h, kpatch-build/kpatch-build, kpatch-build/kpatch-cc, kpatch-build/kpatch-elf.c, kpatch-build/kpatch-elf.h, test/integration/linux-6.2.0/data-new-LOADED.test, test/integration/linux-6.2.0/data-new.patch, test/integration/linux-6.2.0/gcc-static-local-var-6.patch, test/integration/linux-6.2.0/macro-callbacks.patch, test/integration/linux-6.2.0/module-LOADED.test, test/integration/linux-6.2.0/module.patch, test/integration/linux-6.2.0/multiple.test, test/integration/linux-6.2.0/new-function.patch, test/integration/linux-6.2.0/new-globals.patch, test/integration/linux-6.2.0/shadow-newpid-LOADED.test, test/integration/linux-6.2.0/shadow-newpid.patch, test/integration/linux-6.2.0/special-static.patch, test/integration/linux-6.2.0/symvers-disagreement-FAIL.patch, test/integration/linux-6.2.0/syscall-LOADED.test, test/integration/linux-6.2.0/syscall.patch, test/integration/linux-6.2.0/warn-detect-FAIL.patch
Collection of changes to support up to v6.2.
=> Upstream kernel v6.2 support

kpatch-build/lookup.c
If the file doesn't have local object/func symbols, any empty match will do, and duplicate matching local symbol lists aren't a problem.
Fixes #1345.
Reported-by: lzwycc <lzw32321226@163.com>
=> lookup: skip duplicate local symbol table check for files without locals

README.md
=> readme: remove IRC references

kmod/patch/kpatch-macros.h
When we call printk in the context, it may cause
dead lock in the context of scheduler:
sched_func -> rq_lock -> warning -> console_print
-> soft_cursor -> drm_fb_helper_sys_imageblit ->
drm_fb_helper_dirty -> schedule_work -> queue_work (select current cpu) -> try_to_wake_up -> rq_lock (hard lockup)
Every console printing level greater than 4 may
cause this problem in the path of the scheduler.
Using printk_deferred can avoid this situation,
because printk_deferred will use irq_work_queue
instead of schedule_work.
So, we support printk_deferred for kpatch print
macros, because printk_deferred is annotated with
the __cold attribute as printk.
=> kpatch-macros: Add KPATCH_PRINTK_DEFERRED macros
